Diana: SysYParser::FuncDefContext Class Reference
SysYParser::FuncDefContext Class Reference
#include <SysYParser.h>
Public Member Functions
FuncDefContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
FuncTypeContext * funcType ()
antlr4::tree::TerminalNode * Ident ()
antlr4::tree::TerminalNode * LBRA ()
antlr4::tree::TerminalNode * RBRA ()
BlockContext * block ()
FuncFParamsContext * funcFParams ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FuncDefContext()
SysYParser::FuncDefContext::FuncDefContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::FuncDefContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
block()
SysYParser::BlockContext * SysYParser::FuncDefContext::block ()
Referenced by sysy::SysYVisitor::visitFuncDef().
funcFParams()
SysYParser::FuncFParamsContext * SysYParser::FuncDefContext::funcFParams ()
Referenced by sysy::SysYVisitor::visitFuncDef().
funcType()
SysYParser::FuncTypeContext * SysYParser::FuncDefContext::funcType ()
Referenced by sysy::SysYVisitor::visitFuncDef().
getRuleIndex()
size_t SysYParser::FuncDefContext::getRuleIndex () const override virtual
References SysYParser::RuleFuncDef.
Ident()
tree::TerminalNode * SysYParser::FuncDefContext::Ident ()
References SysYParser::Ident.
Referenced by sysy::SysYVisitor::visitFuncDef().
LBRA()
tree::TerminalNode * SysYParser::FuncDefContext::LBRA ()
References SysYParser::LBRA.
RBRA()
tree::TerminalNode * SysYParser::FuncDefContext::RBRA ()
References SysYParser::RBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp