Diana: sysy::ir::Constant Class Reference
sysy::ir::Constant Class Reference abstract
#include <Constant.h>
Public Member Functions
Constant (Type *_type, std::vector< Value * > _operands)
Constant (Type *_type)
virtual bool isZero ()=0
void setZero ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
virtual std::string getSignature ()=0
Static Public Member Functions
static Constant * getZero (Type *_type)
static Constant * getString (const std::string &str)
Protected Attributes
bool zeroinitializer = false
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Constructor & Destructor Documentation
Constant() [1/2]
sysy::ir::Constant::Constant (Type * _type, std::vector< Value * > _operands) inline
Constant() [2/2]
sysy::ir::Constant::Constant (Type * _type) inline
Member Function Documentation
getString()
Constant * sysy::ir::Constant::getString (const std::string & str) static
References sysy::ir::ConstantString::get().
Referenced by sysy::ir::irEmit().
getZero()
Constant * sysy::ir::Constant::getZero (Type * _type) static
References sysy::ir::ConstantInt::getZero(), sysy::ir::ConstantFP::getZero(), sysy::ir::ConstantArray::getZero(), sysy::ir::Type::isArrayTy(), sysy::ir::Type::isFloatTy(), and sysy::ir::Type::isIntegerTy().
Referenced by sysy::ir::createGlobal(), and sysy::ir::irEmit().
isZero()
virtual bool sysy::ir::Constant::isZero () pure virtual
Implemented in sysy::ir::ConstantString, sysy::ir::ConstantArray, sysy::ir::ConstantFP, and sysy::ir::ConstantInt.
setZero()
void sysy::ir::Constant::setZero () inline
References zeroinitializer.
Referenced by sysy::ir::ConstantArray::getZero().
Member Data Documentation
zeroinitializer
bool sysy::ir::Constant::zeroinitializer = false protected
Referenced by sysy::ir::ConstantArray::getSignature(), sysy::ir::ConstantArray::isZero(), and setZero().
The documentation for this class was generated from the following files:
include/sysy/IR/Constant.h
lib/IR/Constant.cpp