Diana: sysy::ir::LoopInfo Class Reference
sysy::ir::LoopInfo Class Reference
#include <LoopInfo.h>
Public Member Functions
LoopInfo ()
std::string getName ()
void run (Function *func) override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Static Public Member Functions
static int getLoopDepth (BasicBlock *bb)
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Private Member Functions
void discoverAndMapSubloop (Loop *loop, Function *func, std::stack< BasicBlock * > &BackedgeTo)
void computeExitingBlocks (Function *func)
void computeExitBlocks (Function *func)
void computePreHeader (Function *func)
void computeLatch (Function *func)
void computeLoopIndVar (Function *func)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Constructor & Destructor Documentation
LoopInfo()
sysy::ir::LoopInfo::LoopInfo ()
References sysy::Pass< Opt >::getRelated().
Member Function Documentation
computeExitBlocks()
void sysy::ir::LoopInfo::computeExitBlocks (Function * func) private
References sysy::ir::Function::getAllLoops().
computeExitingBlocks()
void sysy::ir::LoopInfo::computeExitingBlocks (Function * func) private
References sysy::ir::Function::getAllLoops(), and sysy::ir::BrInstruction::getCond().
computeLatch()
void sysy::ir::LoopInfo::computeLatch (Function * func) private
References sysy::ir::Function::getAllLoops().
computeLoopIndVar()
void sysy::ir::LoopInfo::computeLoopIndVar (Function * func) private
References sysy::ir::Function::getAllLoops().
computePreHeader()
void sysy::ir::LoopInfo::computePreHeader (Function * func) private
References sysy::ir::Function::getAllLoops(), and getLoopDepth().
discoverAndMapSubloop()
void sysy::ir::LoopInfo::discoverAndMapSubloop (Loop * loop, Function * func, std::stack< BasicBlock * > & BackedgeTo) private
References sysy::ir::Loop::getHeader(), sysy::ir::Function::getLoopOfBB(), sysy::ir::Function::linkBBToLoop(), and sysy::ir::parent.
Referenced by run().
getLoopDepth()
int sysy::ir::LoopInfo::getLoopDepth (BasicBlock * bb) static
References sysy::ir::BasicBlock::getParent().
Referenced by computePreHeader().
getName()
std::string sysy::ir::LoopInfo::getName () inline virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::LoopInfo::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfsPost(), sysy::ir::Function::clearLinkOfBBToLoop(), discoverAndMapSubloop(), sysy::ir::BasicBlock::DomTreeDfsPost(), sysy::ir::Function::getAllLoops(), sysy::ir::Function::getEntryBlock(), sysy::ir::Function::getTopLoops(), and PrintMsg.
The documentation for this class was generated from the following files:
include/sysy/Analysis/LoopInfo.h
lib/Analysis/LoopInfo.cpp