Diana: sysy::mc Namespace Reference
sysy::mc Namespace Reference
Classes
class Bic
class BinaryImm
class BinaryReg
class Block
class Branch
class Call
class CompareImm
class CompareReg
class ComplexMul
class Convert
class Function
class GlobalObject
class Instruction
class LoadFP
class LoadGlobal
class LoadImm
class LoadReg
class Module
class MoveImm
class MoveReg
class Pop
class Push
class Reg
class Regallocator
struct RegAllocStat
class Return
class Shift
class ShiftInstr
struct StackObject
class StoreImm
class StoreReg
Typedefs
using Inst = Instruction
using Kind = ir::Instruction::InstrKind
using CondType = Instruction::CondType
Functions
void analyseType (Function *func)
void remove_top_to_bottom (Function *func)
void remove_bottom_to_top (Function *func)
void remove_same_move (Function *func)
void remove_multi_store (Function *func)
void remove_multi_load (Function *func)
void remove_redundant_move (Function *func)
void merge_block (Function *func)
void remove_branch (Function *func)
bool allocable (int reg_id)
static bool cmp (const std::pair< ir::Value *, int > &a, const std::pair< ir::Value *, int > &b)
std::string gen_threads ()
bool is_necessary (Instruction *instr)
bool is_compare (Instruction *instr)
bool may_effect_load (Instruction *instr)
bool may_effect_store (Instruction *instr)
bool is_unconditional_jump (Instruction *inst)
void calculate_pre_succ (Function *func)
Variables
constexpr bool FLOAT = true
std::map< ir::Instruction::InstrKind, Instruction::CondType > cond_map
int REGISTER_USAGE [16]
Typedef Documentation
CondType
using sysy::mc::CondType = typedef Instruction::CondType
Inst
using sysy::mc::Inst = typedef Instruction
Kind
using sysy::mc::Kind = typedef ir::Instruction::InstrKind
Function Documentation
allocable()
bool sysy::mc::allocable (int reg_id)
References REGISTER_USAGE.
Referenced by sysy::mc::Regallocator::build(), sysy::mc::Function::calc_live(), remove_bottom_to_top(), and sysy::mc::Regallocator::run().
analyseType()
void sysy::mc::analyseType (Function * func)
References sysy::mc::Function::AllFloat, sysy::mc::Function::AllInt, sysy::mc::Function::blocks, sysy::mc::Function::IntFloat, and sysy::mc::Function::type.
Referenced by sysy::mc::Module::run().
calculate_pre_succ()
void sysy::mc::calculate_pre_succ (Function * func)
References sysy::mc::Function::blocks, sysy::mc::Function::entry, and sysy::mc::Block::predecessor.
Referenced by merge_block().
cmp()
static bool sysy::mc::cmp (const std::pair< ir::Value *, int > & a, const std::pair< ir::Value *, int > & b) static
gen_threads()
std::string sysy::mc::gen_threads ()
Referenced by sysy::mc::Module::gen_asm().
is_compare()
bool sysy::mc::is_compare (Instruction * instr)
Referenced by remove_bottom_to_top().
is_necessary()
bool sysy::mc::is_necessary (Instruction * instr)
References sysy::mc::BinaryImm::ADD.
Referenced by remove_bottom_to_top().
is_unconditional_jump()
bool sysy::mc::is_unconditional_jump (Instruction * inst)
References sysy::mc::Instruction::AL.
Referenced by merge_block(), and remove_branch().
may_effect_load()
bool sysy::mc::may_effect_load (Instruction * instr)
Referenced by remove_multi_load().
may_effect_store()
bool sysy::mc::may_effect_store (Instruction * instr)
Referenced by remove_multi_store().
merge_block()
void sysy::mc::merge_block (Function * func)
References sysy::mc::Function::blocks, calculate_pre_succ(), sysy::mc::Block::instructions, is_unconditional_jump(), sysy::mc::Block::name, and sysy::mc::Block::predecessor.
Referenced by sysy::mc::Module::run().
remove_bottom_to_top()
void sysy::mc::remove_bottom_to_top (Function * func)
References sysy::mc::Instruction::AL, allocable(), sysy::mc::Function::blocks, sysy::mc::Function::calc_live(), is_compare(), is_necessary(), sysy::mc::Reg::PHY, sysy::mc::Reg::SREG, sysy::mc::Reg::VIRTUAL, and sysy::mc::Reg::VREG.
Referenced by sysy::mc::Module::run().
remove_branch()
void sysy::mc::remove_branch (Function * func)
References sysy::mc::Function::blocks, and is_unconditional_jump().
Referenced by sysy::mc::Module::run().
remove_multi_load()
void sysy::mc::remove_multi_load (Function * func)
References sysy::mc::Function::blocks, sysy::mc::LoadImm::dst, sysy::mc::Reg::id, and may_effect_load().
remove_multi_store()
void sysy::mc::remove_multi_store (Function * func)
References sysy::mc::Function::blocks, and may_effect_store().
Referenced by sysy::mc::Module::run().
remove_redundant_move()
void sysy::mc::remove_redundant_move (Function * func)
remove_same_move()
void sysy::mc::remove_same_move (Function * func)
References sysy::mc::Function::blocks.
remove_top_to_bottom()
void sysy::mc::remove_top_to_bottom (Function * func)
References sysy::type.
Variable Documentation
cond_map
std::map<ir::Instruction::InstrKind, Instruction::CondType> sysy::mc::cond_map
Initial value:
= {
    {Kind::ICmpEQ, CondType::EQ}, {Kind::ICmpNE, CondType::NE}, {Kind::ICmpSGE, CondType::GE}, {Kind::ICmpSGT, CondType::GT}, {Kind::ICmpSLE, CondType::LE}, {Kind::ICmpSLT, CondType::LT},
    {Kind::FCmpUEQ, CondType::EQ}, {Kind::FCmpUNE, CondType::NE}, {Kind::FCmpUGE, CondType::GE}, {Kind::FCmpUGT, CondType::GT}, {Kind::FCmpULE, CondType::LE}, {Kind::FCmpULT, CondType::LT}
}
Referenced by sysy::mc::Block::instSelection().
FLOAT
constexpr bool sysy::mc::FLOAT = true constexpr
REGISTER_USAGE
int sysy::mc::REGISTER_USAGE
Initial value:
= {
    1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3
}
Referenced by allocable(), sysy::mc::Function::reg_alloc(), and sysy::mc::Regallocator::run().