Diana: SysYParser::StmtContext Class Reference
SysYParser::StmtContext Class Reference
#include <SysYParser.h>
Public Member Functions
StmtContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
LValContext * lVal ()
antlr4::tree::TerminalNode * AGN ()
ExpContext * exp ()
std::vector< antlr4::tree::TerminalNode * > SEMI ()
antlr4::tree::TerminalNode * SEMI (size_t i)
BlockContext * block ()
antlr4::tree::TerminalNode * IF ()
antlr4::tree::TerminalNode * LBRA ()
CondContext * cond ()
antlr4::tree::TerminalNode * RBRA ()
std::vector< StmtContext * > stmt ()
StmtContext * stmt (size_t i)
antlr4::tree::TerminalNode * ELSE ()
antlr4::tree::TerminalNode * FOR ()
std::vector< Stmt_inContext * > stmt_in ()
Stmt_inContext * stmt_in (size_t i)
VarDecl_inContext * varDecl_in ()
antlr4::tree::TerminalNode * WHILE ()
antlr4::tree::TerminalNode * BREAK ()
antlr4::tree::TerminalNode * CONTINUE ()
antlr4::tree::TerminalNode * RETURN ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
StmtContext()
SysYParser::StmtContext::StmtContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::StmtContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
AGN()
tree::TerminalNode * SysYParser::StmtContext::AGN ()
References SysYParser::AGN.
Referenced by sysy::SysYVisitor::visitStmt().
block()
SysYParser::BlockContext * SysYParser::StmtContext::block ()
Referenced by sysy::SysYVisitor::visitStmt().
BREAK()
tree::TerminalNode * SysYParser::StmtContext::BREAK ()
References SysYParser::BREAK.
Referenced by sysy::SysYVisitor::visitStmt().
cond()
SysYParser::CondContext * SysYParser::StmtContext::cond ()
Referenced by sysy::SysYVisitor::visitStmt().
CONTINUE()
tree::TerminalNode * SysYParser::StmtContext::CONTINUE ()
References SysYParser::CONTINUE.
Referenced by sysy::SysYVisitor::visitStmt().
ELSE()
tree::TerminalNode * SysYParser::StmtContext::ELSE ()
References SysYParser::ELSE.
exp()
SysYParser::ExpContext * SysYParser::StmtContext::exp ()
Referenced by sysy::SysYVisitor::visitStmt().
FOR()
tree::TerminalNode * SysYParser::StmtContext::FOR ()
References SysYParser::FOR.
Referenced by sysy::SysYVisitor::visitStmt().
getRuleIndex()
size_t SysYParser::StmtContext::getRuleIndex () const override virtual
References SysYParser::RuleStmt.
IF()
tree::TerminalNode * SysYParser::StmtContext::IF ()
References SysYParser::IF.
Referenced by sysy::SysYVisitor::visitStmt().
LBRA()
tree::TerminalNode * SysYParser::StmtContext::LBRA ()
References SysYParser::LBRA.
lVal()
SysYParser::LValContext * SysYParser::StmtContext::lVal ()
Referenced by sysy::SysYVisitor::visitStmt().
RBRA()
tree::TerminalNode * SysYParser::StmtContext::RBRA ()
References SysYParser::RBRA.
RETURN()
tree::TerminalNode * SysYParser::StmtContext::RETURN ()
References SysYParser::RETURN.
Referenced by sysy::SysYVisitor::visitStmt().
SEMI() [1/2]
std::vector< tree::TerminalNode * > SysYParser::StmtContext::SEMI ()
References SysYParser::SEMI.
SEMI() [2/2]
tree::TerminalNode * SysYParser::StmtContext::SEMI (size_t i)
References SysYParser::SEMI.
stmt() [1/2]
std::vector< SysYParser::StmtContext * > SysYParser::StmtContext::stmt ()
Referenced by sysy::SysYVisitor::visitStmt().
stmt() [2/2]
SysYParser::StmtContext * SysYParser::StmtContext::stmt (size_t i)
stmt_in() [1/2]
std::vector< SysYParser::Stmt_inContext * > SysYParser::StmtContext::stmt_in ()
Referenced by sysy::SysYVisitor::visitStmt().
stmt_in() [2/2]
SysYParser::Stmt_inContext * SysYParser::StmtContext::stmt_in (size_t i)
varDecl_in()
SysYParser::VarDecl_inContext * SysYParser::StmtContext::varDecl_in ()
Referenced by sysy::SysYVisitor::visitStmt().
WHILE()
tree::TerminalNode * SysYParser::StmtContext::WHILE ()
References SysYParser::WHILE.
Referenced by sysy::SysYVisitor::visitStmt().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp