Diana: sysy::ir::User Class Reference
sysy::ir::User Class Reference
#include <User.h>
Public Member Functions
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
virtual std::string getSignature ()=0
Protected Types
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
OprandList
using sysy::ir::User::OprandList = std::vector<std::shared_ptr<Use> > protected
Constructor & Destructor Documentation
User() [1/2]
sysy::ir::User::User (Type * _type, std::vector< Value * > _operands, std::string _name = "")
References addOperand().
User() [2/2]
sysy::ir::User::User (Type * _type, std::string _name = "") inline
Member Function Documentation
addOperand()
void sysy::ir::User::addOperand (Value * _value)
References sysy::ir::Value::addUse(), and operands.
Referenced by sysy::ir::BrInstruction::BrInstruction(), sysy::ir::CallInstruction::CallInstruction(), sysy::ir::DeadInstruction::DeadInstruction(), sysy::ir::GEPInstruction::GEPInstruction(), sysy::ir::MemPhiInstruction::MemPhiInstruction(), sysy::ir::MoveInstruction::MoveInstruction(), sysy::ir::PhiInstruction::PhiInstruction(), sysy::ir::BrInstruction::setConditional(), sysy::ir::PhiInstruction::setInComingValue(), sysy::ir::MemPhiInstruction::setInComingValue(), sysy::ir::LoadInstruction::setStore(), sysy::ir::simplifyInstruction(), and User().
getOprands()
OprandList& sysy::ir::User::getOprands () inline
References operands.
Referenced by sysy::ir::ADCE::findAliveCode(), sysy::ir::DCE::findAliveCode(), sysy::ir::MoveInstruction::getIncomingVal(), sysy::ir::PhiInstruction::getPredecessors(), sysy::ir::MemPhiInstruction::getPredecessors(), sysy::ir::DeadInstruction::getSignature(), sysy::ir::MoveInstruction::getTarget(), sysy::ir::CollectOccurrences::isSameExpr(), sysy::ir::PRE::rename1(), sysy::ir::GCM::schduleEarly(), sysy::ir::PhiInstruction::size(), and sysy::ir::MemPhiInstruction::size().
removeOperand()
void sysy::ir::User::removeOperand (const std::shared_ptr< Use > & use)
References operands.
replaceOperand()
void sysy::ir::User::replaceOperand (unsigned index, Value * _value)
References sysy::ir::Value::addUse(), and operands.
replaceOperandWith()
void sysy::ir::User::replaceOperandWith (unsigned index, Value * _value)
References sysy::ir::Value::addUse(), and operands.
Referenced by sysy::ir::BrInstruction::replaceTarget(), sysy::ir::LoopParallel::runOnLoop(), sysy::ir::BrInstruction::setConditional(), sysy::ir::PhiInstruction::setIncomingBB(), sysy::ir::MemPhiInstruction::setIncomingBB(), sysy::ir::LoadInstruction::setStore(), and sysy::ir::BrInstruction::setUnconditional().
UnUseAll()
void sysy::ir::User::UnUseAll ()
References operands.
Referenced by sysy::ir::replace(), and sysy::ir::simplifyInstruction().
Member Data Documentation
operands
OprandList sysy::ir::User::operands protected
Referenced by addOperand(), sysy::ir::ConstantArray::ConstantArray(), sysy::ir::CallInstruction::getArgs(), sysy::ir::CallInstruction::getCallee(), sysy::ir::BrInstruction::getCond(), sysy::ir::BrInstruction::getFalseBlock(), sysy::ir::GEPInstruction::getIndex(), sysy::ir::BinaryInstrcution::getLhs(), getOprands(), sysy::ir::PhiInstruction::getPredecessors(), sysy::ir::MemPhiInstruction::getPredecessors(), sysy::ir::StoreInstruction::getPtr(), sysy::ir::LoadInstruction::getPtr(), sysy::ir::GEPInstruction::getPtr(), sysy::ir::RetInstruction::getRet(), sysy::ir::BinaryInstrcution::getRhs(), sysy::ir::LoadInstruction::getStore(), sysy::ir::BrInstruction::getTrueBlock(), sysy::ir::UnaryInstruction::getValue(), sysy::ir::StoreInstruction::getValue(), sysy::ir::PhiInstruction::removeIncomingByBB(), removeOperand(), sysy::ir::LoadInstruction::removeStore(), replaceOperand(), replaceOperandWith(), sysy::ir::LoadInstruction::setStore(), sysy::ir::BrInstruction::setUnconditional(), sysy::ir::CallInstruction::size(), sysy::ir::GEPInstruction::size(), and UnUseAll().
The documentation for this class was generated from the following files:
include/sysy/IR/User.h
lib/IR/User.cpp