Diana: SysYParser::IntConstContext Class Reference
SysYParser::IntConstContext Class Reference
#include <SysYParser.h>
Public Member Functions
IntConstContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * DEC ()
antlr4::tree::TerminalNode * OCT ()
antlr4::tree::TerminalNode * HEX ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
IntConstContext()
SysYParser::IntConstContext::IntConstContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::IntConstContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DEC()
tree::TerminalNode * SysYParser::IntConstContext::DEC ()
References SysYParser::DEC.
Referenced by sysy::SysYVisitor::visitIntConst().
getRuleIndex()
size_t SysYParser::IntConstContext::getRuleIndex () const override virtual
References SysYParser::RuleIntConst.
HEX()
tree::TerminalNode * SysYParser::IntConstContext::HEX ()
References SysYParser::HEX.
Referenced by sysy::SysYVisitor::visitIntConst().
OCT()
tree::TerminalNode * SysYParser::IntConstContext::OCT ()
References SysYParser::OCT.
Referenced by sysy::SysYVisitor::visitIntConst().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp