Diana: sysy::ir::IRBuilder Class Reference
sysy::ir::IRBuilder Class Reference
#include <Builder.h>
Public Member Functions
IRBuilder (BasicBlock *BB=nullptr, BasicBlock::iterator _insertPoint={})
void SetInsertPoint (BasicBlock *BB, BasicBlock::iterator _insertPoint)
void SetInsertPoint (BasicBlock *BB)
BasicBlock * GetInsertBlock ()
void insertInstr (Instruction *instr)
Value * CreateInBoundsGEP (Type *_type, Value *ptr, const std::vector< Value * > &index, const std::string &name="")
Value * CreateSIToFP (Value *val, Type *destTy, const std::string &name="")
Value * CreateFPToSI (Value *val, Type *destTy, const std::string &name="")
StoreInstruction * CreateStore (Value *val, Value *ptr)
CallInstruction * CreateCall (Function *callee, const std::vector< Value * > args={}, const std::string &name="")
RetInstruction * CreateRetVoid ()
RetInstruction * CreateRet (Value *ret)
LoadInstruction * CreateLoad (Type *type, Value *ptr, const std::string &name="")
BrInstruction * CreateCondBr (Value *cond, BasicBlock *trueBB, BasicBlock *falseBB)
BrInstruction * CreateBr (BasicBlock *dest)
AllocaInstruction * CreateAlloca (Type *type, const std::string &name="")
Value * CreateAdd (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateSub (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateMul (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateSDiv (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateSRem (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpEQ (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpNE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpSLT (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpSGT (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpSLE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateICmpSGE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFAdd (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFSub (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFMul (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFDiv (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFRem (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpUNE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpULT (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpUGT (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpULE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpUGE (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateFCmpUEQ (Value *lhs, Value *rhs, const std::string &name="")
Value * CreateNeg (Value *val, const std::string &name)
Value * CreateNot (Value *val, const std::string &name)
Value * CreateFNeg (Value *val, const std::string &name)
Value * CreateSIToFP (Value *val, const std::string &name)
Value * CreateFPToSI (Value *val, const std::string &name)
Value * CreateBitCast (Value *val, Type *destTy, const std::string &name)
Value * CreateMemCpyInline (Value *dst, unsigned dstAlign, Value *src, unsigned srcAlign, Value *size)
Private Attributes
BasicBlock * curBB
BasicBlock::iterator insertPoint
Constructor & Destructor Documentation
IRBuilder()
sysy::ir::IRBuilder::IRBuilder (BasicBlock * BB = nullptr, BasicBlock::iterator _insertPoint = {}) inline
Member Function Documentation
CreateAdd()
Value * sysy::ir::IRBuilder::CreateAdd (Value * lhs, Value * rhs, const std::string & name = "")
References sysy::ir::Instruction::Add, curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateAlloca()
AllocaInstruction * sysy::ir::IRBuilder::CreateAlloca (Type * type, const std::string & name = "")
References curBB, insertInstr(), sysy::name, and sysy::type.
Referenced by sysy::ir::CreateEntryBlockAlloca().
CreateBitCast()
Value * sysy::ir::IRBuilder::CreateBitCast (Value * val, Type * destTy, const std::string & name)
References sysy::ir::Instruction::BitCast, curBB, insertInstr(), and sysy::name.
Referenced by CreateMemCpyInline().
CreateBr()
BrInstruction * sysy::ir::IRBuilder::CreateBr (BasicBlock * dest)
References curBB, sysy::ir::BasicBlock::getPredecessor(), sysy::ir::BasicBlock::getSuccessor(), and insertInstr().
Referenced by sysy::ir::irEmit().
CreateCall()
CallInstruction * sysy::ir::IRBuilder::CreateCall (Function * callee, const std::vector< Value * > args = {}, const std::string & name = "")
References curBB, insertInstr(), and sysy::name.
Referenced by sysy::ir::createGlobalInit(), CreateMemCpyInline(), sysy::ir::emitInitial(), sysy::ir::globalInit(), and sysy::ir::irEmit().
CreateCondBr()
BrInstruction * sysy::ir::IRBuilder::CreateCondBr (Value * cond, BasicBlock * trueBB, BasicBlock * falseBB)
References curBB, sysy::ir::BasicBlock::getPredecessor(), sysy::ir::BasicBlock::getSuccessor(), and insertInstr().
Referenced by sysy::ir::irEmit().
CreateFAdd()
Value * sysy::ir::IRBuilder::CreateFAdd (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FAdd, sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpUEQ()
Value * sysy::ir::IRBuilder::CreateFCmpUEQ (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpUEQ, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpUGE()
Value * sysy::ir::IRBuilder::CreateFCmpUGE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpUGE, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpUGT()
Value * sysy::ir::IRBuilder::CreateFCmpUGT (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpUGT, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpULE()
Value * sysy::ir::IRBuilder::CreateFCmpULE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpULE, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpULT()
Value * sysy::ir::IRBuilder::CreateFCmpULT (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpULT, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFCmpUNE()
Value * sysy::ir::IRBuilder::CreateFCmpUNE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FCmpUNE, sysy::ir::Type::getInt1Ty(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFDiv()
Value * sysy::ir::IRBuilder::CreateFDiv (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FDiv, sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFMul()
Value * sysy::ir::IRBuilder::CreateFMul (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FMul, sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFNeg()
Value * sysy::ir::IRBuilder::CreateFNeg (Value * val, const std::string & name)
References curBB, sysy::ir::Instruction::FSub, sysy::ir::ConstantFP::get(), sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFPToSI() [1/2]
Value * sysy::ir::IRBuilder::CreateFPToSI (Value * val, const std::string & name)
References curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::name, and sysy::ir::Instruction::SIToFP.
CreateFPToSI() [2/2]
Value * sysy::ir::IRBuilder::CreateFPToSI (Value * val, Type * destTy, const std::string & name = "")
References curBB, sysy::ir::Instruction::FPToSI, insertInstr(), and sysy::name.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::emitInitial(), sysy::ir::getElementPtr(), sysy::ir::getPtrPtr(), and sysy::ir::irEmit().
CreateFRem()
Value * sysy::ir::IRBuilder::CreateFRem (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FRem, sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateFSub()
Value * sysy::ir::IRBuilder::CreateFSub (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Instruction::FSub, sysy::ir::Type::getFloatTy(), insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateICmpEQ()
Value * sysy::ir::IRBuilder::CreateICmpEQ (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpEQ, insertInstr(), and sysy::name.
Referenced by CreateNot(), and sysy::ir::irEmit().
CreateICmpNE()
Value * sysy::ir::IRBuilder::CreateICmpNE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpNE, insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateICmpSGE()
Value * sysy::ir::IRBuilder::CreateICmpSGE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpSGE, insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateICmpSGT()
Value * sysy::ir::IRBuilder::CreateICmpSGT (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpSGT, insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateICmpSLE()
Value * sysy::ir::IRBuilder::CreateICmpSLE (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpSLE, insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateICmpSLT()
Value * sysy::ir::IRBuilder::CreateICmpSLT (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt1Ty(), sysy::ir::Instruction::ICmpSLT, insertInstr(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateInBoundsGEP()
Value * sysy::ir::IRBuilder::CreateInBoundsGEP (Type * _type, Value * ptr, const std::vector< Value * > & index, const std::string & name = "")
References sysy::ir::cnt, curBB, sysy::ir::PointerType::get(), sysy::ir::Type::getInnerType(), insertInstr(), sysy::ir::Type::isPointerTy(), and sysy::name.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::emitInitial(), sysy::ir::getElementPtr(), sysy::ir::getPtrPtr(), and sysy::ir::irEmit().
CreateLoad()
LoadInstruction * sysy::ir::IRBuilder::CreateLoad (Type * type, Value * ptr, const std::string & name = "")
References curBB, insertInstr(), sysy::name, and sysy::type.
Referenced by sysy::ir::getPtrPtr(), and sysy::ir::irEmit().
CreateMemCpyInline()
Value * sysy::ir::IRBuilder::CreateMemCpyInline (Value * dst, unsigned dstAlign, Value * src, unsigned srcAlign, Value * size)
References CreateBitCast(), CreateCall(), sysy::ir::ConstantInt::get(), sysy::ir::Type::getInnerType(), sysy::ir::Module::getInstance(), sysy::ir::Type::getInt8PtrTy(), sysy::ir::Value::getType(), and sysy::type.
CreateMul()
Value * sysy::ir::IRBuilder::CreateMul (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::ir::Instruction::Mul, and sysy::name.
Referenced by sysy::ir::irEmit().
CreateNeg()
Value * sysy::ir::IRBuilder::CreateNeg (Value * val, const std::string & name)
References curBB, sysy::ir::ConstantInt::get(), sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::name, and sysy::ir::Instruction::Sub.
Referenced by sysy::ir::irEmit().
CreateNot()
Value * sysy::ir::IRBuilder::CreateNot (Value * val, const std::string & name)
References CreateICmpEQ(), sysy::ir::ConstantInt::get(), sysy::ir::Value::getType(), and sysy::name.
Referenced by sysy::ir::irEmit().
CreateRet()
RetInstruction * sysy::ir::IRBuilder::CreateRet (Value * ret)
References curBB, and insertInstr().
Referenced by sysy::ir::irEmit().
CreateRetVoid()
RetInstruction * sysy::ir::IRBuilder::CreateRetVoid ()
References curBB, and insertInstr().
Referenced by sysy::ir::createGlobalInit(), and sysy::ir::irEmit().
CreateSDiv()
Value * sysy::ir::IRBuilder::CreateSDiv (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::name, and sysy::ir::Instruction::SDiv.
Referenced by sysy::ir::irEmit().
CreateSIToFP() [1/2]
Value * sysy::ir::IRBuilder::CreateSIToFP (Value * val, const std::string & name)
References curBB, sysy::ir::Type::getFloatTy(), insertInstr(), sysy::name, and sysy::ir::Instruction::SIToFP.
CreateSIToFP() [2/2]
Value * sysy::ir::IRBuilder::CreateSIToFP (Value * val, Type * destTy, const std::string & name = "")
References curBB, insertInstr(), sysy::name, and sysy::ir::Instruction::SIToFP.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::emitInitial(), and sysy::ir::irEmit().
CreateSRem()
Value * sysy::ir::IRBuilder::CreateSRem (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::name, and sysy::ir::Instruction::SRem.
Referenced by sysy::ir::irEmit().
CreateStore()
StoreInstruction * sysy::ir::IRBuilder::CreateStore (Value * val, Value * ptr)
References curBB, and insertInstr().
Referenced by sysy::ir::createGlobalInit(), sysy::ir::emitInitial(), and sysy::ir::irEmit().
CreateSub()
Value * sysy::ir::IRBuilder::CreateSub (Value * lhs, Value * rhs, const std::string & name = "")
References curBB, sysy::ir::Type::getInt32Ty(), insertInstr(), sysy::name, and sysy::ir::Instruction::Sub.
Referenced by sysy::ir::irEmit().
GetInsertBlock()
BasicBlock* sysy::ir::IRBuilder::GetInsertBlock () inline
References curBB.
Referenced by sysy::ir::irEmit().
insertInstr()
void sysy::ir::IRBuilder::insertInstr (Instruction * instr)
References curBB, sysy::ir::BasicBlock::end(), sysy::ir::BasicBlock::insertBack(), sysy::ir::BasicBlock::insertInstr(), and insertPoint.
Referenced by CreateAdd(), CreateAlloca(), CreateBitCast(), CreateBr(), CreateCall(), CreateCondBr(), CreateFAdd(), CreateFCmpUEQ(), CreateFCmpUGE(), CreateFCmpUGT(), CreateFCmpULE(), CreateFCmpULT(), CreateFCmpUNE(), CreateFDiv(), CreateFMul(), CreateFNeg(), CreateFPToSI(), CreateFRem(), CreateFSub(), CreateICmpEQ(), CreateICmpNE(), CreateICmpSGE(), CreateICmpSGT(), CreateICmpSLE(), CreateICmpSLT(), CreateInBoundsGEP(), CreateLoad(), CreateMul(), CreateNeg(), CreateRet(), CreateRetVoid(), CreateSDiv(), CreateSIToFP(), CreateSRem(), CreateStore(), and CreateSub().
SetInsertPoint() [1/2]
void sysy::ir::IRBuilder::SetInsertPoint (BasicBlock * BB) inline
References curBB, sysy::ir::BasicBlock::end(), and insertPoint.
SetInsertPoint() [2/2]
void sysy::ir::IRBuilder::SetInsertPoint (BasicBlock * BB, BasicBlock::iterator _insertPoint) inline
References curBB, and insertPoint.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::globalInit(), and sysy::ir::irEmit().
Member Data Documentation
curBB
BasicBlock* sysy::ir::IRBuilder::curBB private
Referenced by CreateAdd(), CreateAlloca(), CreateBitCast(), CreateBr(), CreateCall(), CreateCondBr(), CreateFAdd(), CreateFCmpUEQ(), CreateFCmpUGE(), CreateFCmpUGT(), CreateFCmpULE(), CreateFCmpULT(), CreateFCmpUNE(), CreateFDiv(), CreateFMul(), CreateFNeg(), CreateFPToSI(), CreateFRem(), CreateFSub(), CreateICmpEQ(), CreateICmpNE(), CreateICmpSGE(), CreateICmpSGT(), CreateICmpSLE(), CreateICmpSLT(), CreateInBoundsGEP(), CreateLoad(), CreateMul(), CreateNeg(), CreateRet(), CreateRetVoid(), CreateSDiv(), CreateSIToFP(), CreateSRem(), CreateStore(), CreateSub(), GetInsertBlock(), insertInstr(), and SetInsertPoint().
insertPoint
BasicBlock::iterator sysy::ir::IRBuilder::insertPoint private
Referenced by insertInstr(), and SetInsertPoint().
The documentation for this class was generated from the following files:
include/sysy/IR/Builder.h
lib/IR/Builder.cpp