Diana: sysy::ir::AllocaInstruction Class Reference
sysy::ir::AllocaInstruction Class Reference
#include <Instructions.h>
Public Member Functions
AllocaInstruction (Type *_allocaType, BasicBlock *_father, std::string _name="")
Type * getAllocatedType ()
Value * getSize ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::MemoryInstruction
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Private Attributes
Type * allocaType
Additional Inherited Members
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
AllocaInstruction()
sysy::ir::AllocaInstruction::AllocaInstruction (Type * _allocaType, BasicBlock * _father, std::string _name = "") inline
Member Function Documentation
getAllocatedType()
Type* sysy::ir::AllocaInstruction::getAllocatedType () inline
References allocaType.
Referenced by sysy::ir::getElementPtr(), sysy::ir::getPtrPtr(), getSignature(), sysy::ir::irEmit(), sysy::ir::isAliasByGVToArg(), sysy::ir::Memory2Reg::isAllocaPromotable(), sysy::ir::isArgArray(), and sysy::ir::Memory2Reg::queuePhi().
getSignature()
std::string sysy::ir::AllocaInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References getAllocatedType(), sysy::ir::Type::getSignature(), and sysy::ir::getVariable().
getSize()
Value* sysy::ir::AllocaInstruction::getSize () inline
References sysy::ir::Type::getInt32Ty(), and sysy::ir::ConstantInt::getZero().
Member Data Documentation
allocaType
Type* sysy::ir::AllocaInstruction::allocaType private
Referenced by getAllocatedType().
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/IRDump.cpp