Diana: sysy::ast Namespace Reference
sysy::ast Namespace Reference
Classes
class AssignStmtNode
class AstNode
class BinaryExprNode
class BlockNode
class BreakStmtNode
class CompUnitNode
class ConstDeclNode
class ConstDefNode
class ContinueStmtNode
class DeclNode
class ExprNode
class ExprStmtNode
class ForStmtNode
class FuncDefNode
class FuncParamListNode
class FuncParamNode
class FunctionCallExprNode
class IfStmtNode
class Immediate
class InitValNode
class LvalNode
class NumberNode
class ReturnStmtNode
class StmtNode
class UnaryExprNode
class VarDeclNode
class VarDefNode
class WhileStmtNode
Enumerations
enum AstType {
VOID = 0, INT, FLOAT, DOUBLE,
STRING, UNKNOW
}
enum BinaryOp {
BOP_ADD = 0, BOP_SUB, BOP_MUL, BOP_DIV,
BOP_MOD, ROP_EQL, ROP_NEQ, ROP_LES,
ROP_GRT, ROP_LEQ, ROP_GEQ, ROP_OR,
ROP_AND, BOP_NONE
}
enum UnaryOp { UOP_ADD = 0, UOP_SUB, UOP_NOT, UOP_NONE }
Functions
void dump (AstNode *node)
void removeDeadStmts (BlockNode *block)
void optimizeAst (CompUnitNode *ast)
AstType operator&& (AstType x, AstType y)
AstType operator|| (AstType x, AstType y)
ir::Type * AstType2IrType (AstType type)
std::string getSignature (AstType type)
std::string getSignature (BinaryOp op)
std::string getSignature (UnaryOp op)
Enumeration Type Documentation
AstType
enum sysy::ast::AstType
Enumerator
VOID
INT
FLOAT
DOUBLE
STRING
UNKNOW
BinaryOp
enum sysy::ast::BinaryOp
Enumerator
BOP_ADD
BOP_SUB
BOP_MUL
BOP_DIV
BOP_MOD
ROP_EQL
ROP_NEQ
ROP_LES
ROP_GRT
ROP_LEQ
ROP_GEQ
ROP_OR
ROP_AND
BOP_NONE
UnaryOp
enum sysy::ast::UnaryOp
Enumerator
UOP_ADD
UOP_SUB
UOP_NOT
UOP_NONE
Function Documentation
AstType2IrType()
ir::Type * sysy::ast::AstType2IrType (AstType type)
References ErrorMsg, FLOAT, sysy::ir::Type::getFloatTy(), sysy::ir::Type::getInt32Ty(), INT, and sysy::type.
Referenced by sysy::ir::createGlobal(), and sysy::ir::irEmit().
dump()
void sysy::ast::dump (AstNode * node)
References sysy::ast::AstNode::getSignature().
Referenced by sysy::FrontendMain().
getSignature() [1/3]
std::string sysy::ast::getSignature (AstType type)
References FLOAT, INT, sysy::type, and VOID.
Referenced by sysy::ast::FuncDefNode::getSignature(), sysy::ast::FuncParamNode::getSignature(), sysy::ast::DeclNode::getSignature(), sysy::ast::ConstDeclNode::getSignature(), sysy::ast::VarDeclNode::getSignature(), sysy::ast::ExprNode::getSignature(), sysy::ast::UnaryExprNode::getSignature(), sysy::ast::BinaryExprNode::getSignature(), sysy::ast::FunctionCallExprNode::getSignature(), sysy::ast::LvalNode::getSignature(), and sysy::ast::NumberNode::getSignature().
getSignature() [2/3]
std::string sysy::ast::getSignature (BinaryOp op)
References BOP_ADD, BOP_DIV, BOP_MOD, BOP_MUL, BOP_SUB, ROP_AND, ROP_EQL, ROP_GEQ, ROP_GRT, ROP_LEQ, ROP_LES, ROP_NEQ, and ROP_OR.
getSignature() [3/3]
std::string sysy::ast::getSignature (UnaryOp op)
References UOP_ADD, UOP_NOT, and UOP_SUB.
operator&&()
AstType sysy::ast::operator&& (AstType x, AstType y)
operator||()
AstType sysy::ast::operator|| (AstType x, AstType y)
optimizeAst()
void sysy::ast::optimizeAst (CompUnitNode * ast)
removeDeadStmts()
void sysy::ast::removeDeadStmts (BlockNode * block)
References sysy::ast::AstNode::AST_breakStmt, sysy::ast::AstNode::AST_continueStmt, sysy::ast::AstNode::AST_returnStmt, and sysy::ast::BlockNode::blockItems.
Referenced by sysy::SysYVisitor::visitBlock().