Diana: sysy::ir::FunctionType Class Reference
sysy::ir::FunctionType Class Reference
#include <Type.h>
Public Member Functions
FunctionType (Type *_retType, std::vector< Type * > _argType, bool _isVarArg)
FunctionType (Type *_retType, bool _isVarArg)
Type * getInnerType () override
std::vector< Type * > & getArg ()
Type * getRet ()
std::string getSignature () override
size_t getAllocatedSize () override
Public Member Functions inherited from sysy::ir::Type
bool isFloatTy ()
bool isVoidTy ()
bool isLabelTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned width)
bool isFunctionTy ()
bool isPointerTy ()
bool isVectorTy ()
bool isArrayTy ()
bool isUndefTy ()
Static Public Member Functions
static FunctionType * get (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static FunctionType * get (Type *_retType, bool isVarArg)
Static Public Member Functions inherited from sysy::ir::Type
static Type * getFloatTy ()
static Type * getVoidTy ()
static Type * getUndefTy ()
static Type * getFunctionTy (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static Type * getLabelTy ()
static Type * getIntegerTy (unsigned width)
static Type * getInt1Ty ()
static Type * getInt32Ty ()
static Type * getInt8Ty ()
static Type * getPointerTy (Type *inner)
static Type * getArrayTy (Type *inner, unsigned size)
static Type * getInt8PtrTy ()
static Type * getInt32PtrTy ()
static Type * getFloatPtrTy ()
Private Attributes
Type * retType
std::vector< Type * > argType
bool isVarArg
Friends
bool operator< (const FunctionType &x, const FunctionType &y)
Additional Inherited Members
Public Types inherited from sysy::ir::Type
enum TypeID {
FloatTyID = 0, VoidTyID, LabelTyID, IntegerTyID,
FunctionTyID, PointerTyID, ArrayTyID, FixedVectorTyID,
ScalableVectorTyID, UndefTyID
}
Protected Member Functions inherited from sysy::ir::Type
Type (TypeID id)
TypeID getTypeId ()
unsigned getSize ()
Constructor & Destructor Documentation
FunctionType() [1/2]
sysy::ir::FunctionType::FunctionType (Type * _retType, std::vector< Type * > _argType, bool _isVarArg) inline
Referenced by get().
FunctionType() [2/2]
sysy::ir::FunctionType::FunctionType (Type * _retType, bool _isVarArg) inline
Member Function Documentation
get() [1/2]
FunctionType * sysy::ir::FunctionType::get (Type * _retType, bool isVarArg) static
References FunctionType(), and isVarArg.
get() [2/2]
FunctionType * sysy::ir::FunctionType::get (Type * _retType, std::vector< Type * > _argType, bool isVarArg = false) static
References FunctionType(), and isVarArg.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::Type::getFunctionTy(), sysy::ir::initRuntime(), and sysy::ir::irEmit().
getAllocatedSize()
size_t sysy::ir::FunctionType::getAllocatedSize () inline override virtual
Implements sysy::ir::Type.
getArg()
std::vector<Type*>& sysy::ir::FunctionType::getArg () inline
References argType.
Referenced by sysy::ir::Function::Function().
getInnerType()
Type* sysy::ir::FunctionType::getInnerType () inline override virtual
Implements sysy::ir::Type.
References retType.
getRet()
Type* sysy::ir::FunctionType::getRet () inline
References retType.
Referenced by sysy::ir::irEmit().
getSignature()
std::string sysy::ir::FunctionType::getSignature () inline override virtual
Implements sysy::ir::Type.
References sysy::ir::Type::getSignature(), and retType.
Friends And Related Function Documentation
operator<
bool operator< (const FunctionType & x, const FunctionType & y) friend
Member Data Documentation
argType
std::vector<Type*> sysy::ir::FunctionType::argType private
Referenced by getArg().
isVarArg
bool sysy::ir::FunctionType::isVarArg private
Referenced by get().
retType
Type* sysy::ir::FunctionType::retType private
Referenced by getInnerType(), getRet(), and getSignature().
The documentation for this class was generated from the following files:
include/sysy/IR/Type.h
lib/IR/Type.cpp