Diana: sysy::ir::ConstantString Class Reference
sysy::ir::ConstantString Class Reference
#include <Constant.h>
Public Member Functions
ConstantString (const std::string &_str)
bool isZero () override
std::string getStr ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Constant
Constant (Type *_type, std::vector< Value * > _operands)
Constant (Type *_type)
void setZero ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static ConstantString * get (const std::string &_str)
Static Public Member Functions inherited from sysy::ir::Constant
static Constant * getZero (Type *_type)
static Constant * getString (const std::string &str)
Private Attributes
std::string str
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::Constant
bool zeroinitializer = false
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
ConstantString()
sysy::ir::ConstantString::ConstantString (const std::string & _str) inline
Referenced by get().
Member Function Documentation
get()
ConstantString * sysy::ir::ConstantString::get (const std::string & _str) static
References ConstantString().
Referenced by sysy::ir::Constant::getString().
getSignature()
std::string sysy::ir::ConstantString::getSignature () override virtual
Implements sysy::ir::Value.
References str.
getStr()
std::string sysy::ir::ConstantString::getStr () inline
References str.
isZero()
bool sysy::ir::ConstantString::isZero () inline override virtual
Implements sysy::ir::Constant.
Member Data Documentation
str
std::string sysy::ir::ConstantString::str private
Referenced by getSignature(), and getStr().
The documentation for this class was generated from the following files:
include/sysy/IR/Constant.h
lib/IR/Constant.cpp
lib/IR/IRDump.cpp