Diana: sysy::ir::MemorySSA Class Reference
sysy::ir::MemorySSA Class Reference
#include <MemorySSA.h>
Public Member Functions
MemorySSA ()
void run (Function *func) override
std::string getName ()
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void analysisScalarGV (GlobalValue *gv)
void computeScalarGVInfo (Function *func)
void queueStoreMemPhi (GlobalValue *gv, BasicBlock *father)
void queueLoadMemPhi (GlobalValue *gv, BasicBlock *father)
void renameLoadOfGVInBB (GlobalValue *gv, BasicBlock *bb, BasicBlock *pred)
void renameStoreOfGVInBB (GlobalValue *gv, BasicBlock *bb, BasicBlock *pred)
void analysisArray (Value *array)
void computeArrayInfo (Function *func)
void queueStoreMemPhi (Value *array, BasicBlock *father)
void queueLoadMemPhi (Value *array, BasicBlock *father)
void renameLoadOfArrayInBB (Value *array, BasicBlock *bb, BasicBlock *pred)
void renameStoreOfArrayInBB (Value *array, BasicBlock *bb, BasicBlock *pred)
void UseDefCompute (Function *func)
void DefUseCompute (Function *func)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
MemorySSA()
sysy::ir::MemorySSA::MemorySSA ()
References sysy::Pass< Opt >::getRelated().
Member Function Documentation
analysisArray()
void sysy::ir::MemorySSA::analysisArray (Value * array) private
References sysy::ir::arrayDefUse, sysy::ir::arrayUseDef, sysy::ir::Instruction::getRank(), sysy::ir::info, and sysy::ir::less().
Referenced by run().
analysisScalarGV()
void sysy::ir::MemorySSA::analysisScalarGV (GlobalValue * gv) private
References sysy::ir::Instruction::getRank(), sysy::ir::globalValueDefUse, sysy::ir::globalValueInfo, sysy::ir::globalValueUseDef, and sysy::ir::less().
Referenced by run().
computeArrayInfo()
void sysy::ir::MemorySSA::computeArrayInfo (Function * func) private
References sysy::ir::alias(), sysy::ir::aliasAtCall(), sysy::ir::Function::getBasicBlockList(), sysy::ir::getOriginArray(), sysy::ir::GlobalValue::getValueType(), sysy::ir::info, and sysy::ir::Type::isArrayTy().
Referenced by run().
computeScalarGVInfo()
void sysy::ir::MemorySSA::computeScalarGVInfo (Function * func) private
References sysy::ir::Function::getBasicBlockList(), sysy::ir::StoreInstruction::getPtr(), sysy::ir::GlobalValue::getValueType(), and sysy::ir::globalValueInfo.
Referenced by run().
DefUseCompute()
void sysy::ir::MemorySSA::DefUseCompute (Function * func) private
References sysy::ir::UndefValue::Create(), sysy::ir::Function::getEntryBlock(), sysy::ir::globalValueInfo, sysy::ir::IncomingGVStoreInBB, sysy::ir::IncomingStoreInBB, sysy::ir::info, sysy::ir::LoadCoverLoad, PrintMsg, queueStoreMemPhi(), renameLoadOfArrayInBB(), and renameLoadOfGVInBB().
Referenced by run().
getName()
std::string sysy::ir::MemorySSA::getName () inline virtual
Implements sysy::Pass< Opt >.
queueLoadMemPhi() [1/2]
void sysy::ir::MemorySSA::queueLoadMemPhi (GlobalValue * gv, BasicBlock * father) private
References sysy::ir::Value::getName(), sysy::ir::Type::getVoidTy(), sysy::ir::globalValueInfo, and sysy::ir::BasicBlock::insertFront().
Referenced by UseDefCompute().
queueLoadMemPhi() [2/2]
void sysy::ir::MemorySSA::queueLoadMemPhi (Value * array, BasicBlock * father) private
References sysy::ir::Value::getName(), sysy::ir::Type::getVoidTy(), sysy::ir::info, and sysy::ir::BasicBlock::insertFront().
queueStoreMemPhi() [1/2]
void sysy::ir::MemorySSA::queueStoreMemPhi (GlobalValue * gv, BasicBlock * father) private
References sysy::ir::Value::getName(), sysy::ir::Type::getVoidTy(), sysy::ir::globalValueInfo, and sysy::ir::BasicBlock::insertFront().
Referenced by DefUseCompute().
queueStoreMemPhi() [2/2]
void sysy::ir::MemorySSA::queueStoreMemPhi (Value * array, BasicBlock * father) private
References sysy::ir::Value::getName(), sysy::ir::Type::getVoidTy(), sysy::ir::info, and sysy::ir::BasicBlock::insertFront().
renameLoadOfArrayInBB()
void sysy::ir::MemorySSA::renameLoadOfArrayInBB (Value * array, BasicBlock * bb, BasicBlock * pred) private
References sysy::ir::arrayUseDef, sysy::ir::UndefValue::Create(), sysy::ir::IncomingStoreInBB, and sysy::ir::info.
Referenced by DefUseCompute().
renameLoadOfGVInBB()
void sysy::ir::MemorySSA::renameLoadOfGVInBB (GlobalValue * gv, BasicBlock * bb, BasicBlock * pred) private
References sysy::ir::UndefValue::Create(), sysy::ir::globalValueInfo, sysy::ir::globalValueUseDef, and sysy::ir::IncomingGVStoreInBB.
Referenced by DefUseCompute().
renameStoreOfArrayInBB()
void sysy::ir::MemorySSA::renameStoreOfArrayInBB (Value * array, BasicBlock * bb, BasicBlock * pred) private
References sysy::ir::arrayDefUse, sysy::ir::UndefValue::Create(), sysy::ir::IncomingLoadInBB, sysy::ir::info, and sysy::ir::LoadCoverLoad.
Referenced by UseDefCompute().
renameStoreOfGVInBB()
void sysy::ir::MemorySSA::renameStoreOfGVInBB (GlobalValue * gv, BasicBlock * bb, BasicBlock * pred) private
References sysy::ir::UndefValue::Create(), sysy::ir::globalValueDefUse, sysy::ir::globalValueInfo, and sysy::ir::IncomingGVLoadInBB.
Referenced by UseDefCompute().
run()
void sysy::ir::MemorySSA::run (Function * func) override
References analysisArray(), analysisScalarGV(), sysy::ir::arrayDefUse, sysy::ir::arrayUseDef, computeArrayInfo(), computeScalarGVInfo(), DefUseCompute(), sysy::ir::Value::getName(), sysy::ir::globalValueDefUse, sysy::ir::globalValueInfo, sysy::ir::globalValueUseDef, sysy::ir::info, PrintMsg, and UseDefCompute().
UseDefCompute()
void sysy::ir::MemorySSA::UseDefCompute (Function * func) private
References sysy::ir::UndefValue::Create(), sysy::ir::Function::getEntryBlock(), sysy::ir::globalValueInfo, sysy::ir::IncomingGVLoadInBB, sysy::ir::IncomingLoadInBB, sysy::ir::info, PrintMsg, queueLoadMemPhi(), renameStoreOfArrayInBB(), and renameStoreOfGVInBB().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/MemorySSA.h
lib/Transform/Utils/MemorySSA.cpp