Diana: sysy::ir::CleanExitBasicBlock Class Reference
sysy::ir::CleanExitBasicBlock Class Reference
#include <VirtualExitBasicBlock.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
getName()
std::string sysy::ir::CleanExitBasicBlock::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::CleanExitBasicBlock::run (Function * func) override
References sysy::ir::dumpBasickBlock(), sysy::ir::dumpFunction(), sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Function::getBasicBlockList(), sysy::ir::Function::getExitBlock(), sysy::ir::Function::getReturnType(), sysy::ir::Type::isFloatTy(), sysy::ir::Type::isIntegerTy(), and sysy::ir::Function::setExitBlock().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/VirtualExitBasicBlock.h
lib/Transform/Utils/VirtualExitBasicBlock.cpp