Diana: sysy::ir::CallInstruction Class Reference
sysy::ir::CallInstruction Class Reference
#include <Instructions.h>
Classes
class ArgIterator
Public Types
using argRange = iterator_range< ArgIterator >
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Public Member Functions
CallInstruction (Function *_callee, std::vector< Value * > _args, BasicBlock *_father, std::string _name="")
Function * getCallee ()
argRange getArgs ()
Value * getArgs (unsigned index)
size_t size ()
bool isPureCall ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::TerminatorInstruction
TerminatorInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
TerminatorInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Public Attributes
bool hasAlias = false
Additional Inherited Members
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
argRange
using sysy::ir::CallInstruction::argRange = iterator_range<ArgIterator>
Constructor & Destructor Documentation
CallInstruction()
sysy::ir::CallInstruction::CallInstruction (Function * _callee, std::vector< Value * > _args, BasicBlock * _father, std::string _name = "")
References sysy::ir::User::addOperand().
Member Function Documentation
getArgs() [1/2]
CallInstruction::argRange sysy::ir::CallInstruction::getArgs ()
References sysy::make_range(), and sysy::ir::User::operands.
Referenced by sysy::ir::aliasAtCall(), getSignature(), and isPureCall().
getArgs() [2/2]
Value * sysy::ir::CallInstruction::getArgs (unsigned index)
References sysy::ir::User::operands.
getCallee()
Function * sysy::ir::CallInstruction::getCallee ()
References sysy::ir::User::operands.
Referenced by sysy::ir::aliasAtCall(), getSignature(), sysy::ir::FunctionInline::inlineAtCall(), and isPureCall().
getSignature()
std::string sysy::ir::CallInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References sysy::iterator_range< IteratorT >::begin(), sysy::iterator_range< IteratorT >::end(), getArgs(), getCallee(), sysy::ir::Value::getName(), sysy::ir::Type::getSignature(), sysy::ir::Value::getType(), sysy::ir::getVariable(), and sysy::ir::nameIs().
isPureCall()
bool sysy::ir::CallInstruction::isPureCall ()
References getArgs(), and getCallee().
Referenced by sysy::ir::ADCE::isUsefulInstr(), and sysy::ir::DCE::isUsefulInstr().
size()
size_t sysy::ir::CallInstruction::size () inline
References sysy::ir::User::operands.
Member Data Documentation
hasAlias
bool sysy::ir::CallInstruction::hasAlias = false
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/Instructions.cpp
lib/IR/IRDump.cpp