Diana: SysYParser::UnaryExpContext Class Reference
SysYParser::UnaryExpContext Class Reference
#include <SysYParser.h>
Public Member Functions
UnaryExpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
PrimaryExpContext * primaryExp ()
antlr4::tree::TerminalNode * Ident ()
antlr4::tree::TerminalNode * LBRA ()
antlr4::tree::TerminalNode * RBRA ()
FuncRParamsContext * funcRParams ()
UnaryOpContext * unaryOp ()
UnaryExpContext * unaryExp ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
UnaryExpContext()
SysYParser::UnaryExpContext::UnaryExpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::UnaryExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
funcRParams()
SysYParser::FuncRParamsContext * SysYParser::UnaryExpContext::funcRParams ()
Referenced by sysy::SysYVisitor::visitUnaryExp().
getRuleIndex()
size_t SysYParser::UnaryExpContext::getRuleIndex () const override virtual
References SysYParser::RuleUnaryExp.
Ident()
tree::TerminalNode * SysYParser::UnaryExpContext::Ident ()
References SysYParser::Ident.
Referenced by sysy::SysYVisitor::visitUnaryExp().
LBRA()
tree::TerminalNode * SysYParser::UnaryExpContext::LBRA ()
References SysYParser::LBRA.
primaryExp()
SysYParser::PrimaryExpContext * SysYParser::UnaryExpContext::primaryExp ()
Referenced by sysy::SysYVisitor::visitUnaryExp().
RBRA()
tree::TerminalNode * SysYParser::UnaryExpContext::RBRA ()
References SysYParser::RBRA.
unaryExp()
SysYParser::UnaryExpContext * SysYParser::UnaryExpContext::unaryExp ()
Referenced by sysy::SysYVisitor::visitUnaryExp().
unaryOp()
SysYParser::UnaryOpContext * SysYParser::UnaryExpContext::unaryOp ()
Referenced by sysy::SysYVisitor::visitUnaryExp().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp