Diana: sysy::ir::LoopUnrollAll Class Reference
sysy::ir::LoopUnrollAll Class Reference
#include <LoopUnroll.h>
Public Member Functions
LoopUnrollAll ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void runOnLoop (Loop *loop)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
LoopUnrollAll()
sysy::ir::LoopUnrollAll::LoopUnrollAll ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
getName()
std::string sysy::ir::LoopUnrollAll::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::LoopUnrollAll::run (Function * func) override
References sysy::ir::Function::getTopLoops(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::LoopUnrollAll::runOnLoop (Loop * loop) private
References sysy::ir::Loop::getExitBlocks(), sysy::ir::Loop::getExitingBlocks(), sysy::ir::Loop::getHeader(), sysy::ir::Loop::getLatchBlock(), sysy::ir::Loop::getLoopBasicBlocks(), sysy::ir::IRCopier::getLoopCopy(), sysy::ir::Loop::getPreHeader(), sysy::ir::Loop::getTripCount(), sysy::ir::maxTripCount, and sysy::ir::Value::replaceAllUseWith().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Loop/LoopUnroll.h
lib/Transform/Loop/LoopUnroll.cpp