Diana: sysy::ir::Function::Arg Class Reference
sysy::ir::Function::Arg Class Reference
#include <Function.h>
Public Member Functions
Arg (Type *_type)
Arg (Type *_type, std::string _name)
void setName (std::string _name)
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static Arg * make_arg (Type *_type, std::string _name)
Additional Inherited Members
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
Arg() [1/2]
sysy::ir::Function::Arg::Arg (Type * _type) inline
Referenced by make_arg().
Arg() [2/2]
sysy::ir::Function::Arg::Arg (Type * _type, std::string _name) inline
Member Function Documentation
getSignature()
std::string sysy::ir::Function::Arg::getSignature () override virtual
Implements sysy::ir::Value.
References sysy::ir::Type::getSignature(), sysy::ir::Value::name, and sysy::ir::Value::type.
make_arg()
static Arg* sysy::ir::Function::Arg::make_arg (Type * _type, std::string _name) inline static
References Arg().
setName()
void sysy::ir::Function::Arg::setName (std::string _name) inline
References sysy::ir::Value::name.
The documentation for this class was generated from the following files:
include/sysy/IR/Function.h
lib/IR/Function.cpp