Diana: sysy::ir::AllocaInfo Class Reference
sysy::ir::AllocaInfo Class Reference
#include <Memory2Reg.h>
Public Types
using iterator = std::unordered_map< BasicBlock *, std::set< StoreInst *, cmps > >::iterator
Public Member Functions
size_t storeSize ()
StoreInst * getOnlyStore ()
iterator_range< iterator > get ()
std::set< BasicBlock * > & getBlock ()
std::set< BasicBlock * > & getDefBlocks ()
std::set< BasicBlock * > & getUseBlocks ()
std::set< StoreInst *, cmps > & getStore (BasicBlock *bb)
std::set< LoadInst *, cmpl > & getLoad (BasicBlock *bb)
void setPhi (BasicBlock *bb, PhiInst *_phi)
PhiInst * getPhi (BasicBlock *bb)
size_t phiSize ()
Public Attributes
std::unordered_set< LoadInst * > unLockLoad
Private Attributes
std::set< BasicBlock * > defBlocks
std::set< BasicBlock * > useBlocks
std::set< BasicBlock * > block
std::unordered_map< BasicBlock *, std::set< StoreInst *, cmps > > store
std::unordered_map< BasicBlock *, std::set< LoadInst *, cmpl > > load
std::unordered_map< BasicBlock *, PhiInst * > phi
Member Typedef Documentation
iterator
using sysy::ir::AllocaInfo::iterator = std::unordered_map<BasicBlock*, std::set<StoreInst*, cmps> >::iterator
Member Function Documentation
get()
iterator_range<iterator> sysy::ir::AllocaInfo::get () inline
References sysy::make_range(), and store.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
getBlock()
std::set<BasicBlock*>& sysy::ir::AllocaInfo::getBlock () inline
References block.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
getDefBlocks()
std::set<BasicBlock*>& sysy::ir::AllocaInfo::getDefBlocks () inline
References defBlocks.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
getLoad()
std::set<LoadInst*, cmpl>& sysy::ir::AllocaInfo::getLoad (BasicBlock * bb) inline
References load.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
getOnlyStore()
StoreInst * sysy::ir::AllocaInfo::getOnlyStore ()
References store.
getPhi()
PhiInst* sysy::ir::AllocaInfo::getPhi (BasicBlock * bb) inline
References phi.
getStore()
std::set<StoreInst*, cmps>& sysy::ir::AllocaInfo::getStore (BasicBlock * bb) inline
References store.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
getUseBlocks()
std::set<BasicBlock*>& sysy::ir::AllocaInfo::getUseBlocks () inline
References useBlocks.
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
phiSize()
size_t sysy::ir::AllocaInfo::phiSize () inline
References phi.
setPhi()
void sysy::ir::AllocaInfo::setPhi (BasicBlock * bb, PhiInst * _phi) inline
References phi.
storeSize()
size_t sysy::ir::AllocaInfo::storeSize () inline
References store.
Member Data Documentation
block
std::set<BasicBlock*> sysy::ir::AllocaInfo::block private
Referenced by getBlock().
defBlocks
std::set<BasicBlock*> sysy::ir::AllocaInfo::defBlocks private
Referenced by getDefBlocks().
load
std::unordered_map<BasicBlock*, std::set<LoadInst*, cmpl> > sysy::ir::AllocaInfo::load private
Referenced by getLoad().
phi
std::unordered_map<BasicBlock*, PhiInst*> sysy::ir::AllocaInfo::phi private
Referenced by getPhi(), phiSize(), and setPhi().
store
std::unordered_map<BasicBlock*, std::set<StoreInst*, cmps> > sysy::ir::AllocaInfo::store private
Referenced by get(), getOnlyStore(), getStore(), and storeSize().
unLockLoad
std::unordered_set<LoadInst*> sysy::ir::AllocaInfo::unLockLoad
Referenced by sysy::ir::Memory2Reg::analysisAlloca().
useBlocks
std::set<BasicBlock*> sysy::ir::AllocaInfo::useBlocks private
Referenced by getUseBlocks().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/Memory2Reg.h
lib/Transform/Utils/Memory2Reg.cpp