Diana: sysy::ir::ScalarEvolutionClean Class Reference
sysy::ir::ScalarEvolutionClean Class Reference
#include <SCEV.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void runOnLoop (Loop *loop)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
getName()
std::string sysy::ir::ScalarEvolutionClean::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::ScalarEvolutionClean::run (Function * func) override
References sysy::ir::Value::getName(), sysy::ir::Function::getTopLoops(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::ScalarEvolutionClean::runOnLoop (Loop * loop) private
References sysy::ir::Loop::getSCEV(), and sysy::ir::Loop::getSubLoops().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Analysis/SCEV.h
lib/Analysis/SCEV.cpp