Diana: sysy::ir::LSR Class Reference
sysy::ir::LSR Class Reference
#include <LSR.h>
Public Member Functions
LSR ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void identifyAllInductiveMultiplication (Loop *loop)
void eraseSingleMul (Loop *loop, BinaryInst *mul)
void runOnLoop (Loop *loop)
Private Attributes
std::vector< BinaryInst * > Multiplies
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
LSR()
sysy::ir::LSR::LSR ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
eraseSingleMul()
void sysy::ir::LSR::eraseSingleMul (Loop * loop, BinaryInst * mul) private
References sysy::ir::Instruction::Add, sysy::ir::SCEV::at(), sysy::ir::Loop::getHeader(), sysy::ir::Loop::getLatchBlock(), sysy::ir::Value::getName(), sysy::ir::Loop::getPreHeader(), sysy::ir::Loop::getSCEV(), sysy::ir::BasicBlock::insertBeforeTerminal(), sysy::ir::BasicBlock::insertFront(), and sysy::ir::Value::replaceAllUseWith().
Referenced by runOnLoop().
getName()
std::string sysy::ir::LSR::getName () inline override virtual
Implements sysy::Pass< Opt >.
identifyAllInductiveMultiplication()
void sysy::ir::LSR::identifyAllInductiveMultiplication (Loop * loop) private
References sysy::ir::Instruction::getKind(), sysy::ir::Loop::getLoopBasicBlocks(), sysy::ir::Loop::hasSCEV(), sysy::ir::Instruction::Mul, and Multiplies.
Referenced by runOnLoop().
run()
void sysy::ir::LSR::run (Function * func) override
References sysy::ir::Value::getName(), sysy::ir::Function::getTopLoops(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::LSR::runOnLoop (Loop * loop) private
References eraseSingleMul(), sysy::ir::Loop::getSubLoops(), identifyAllInductiveMultiplication(), and Multiplies.
Referenced by run().
Member Data Documentation
Multiplies
std::vector<BinaryInst*> sysy::ir::LSR::Multiplies private
Referenced by identifyAllInductiveMultiplication(), and runOnLoop().
The documentation for this class was generated from the following files:
include/sysy/Transform/Loop/LSR.h
lib/Transform/Loop/LSR.cpp