Diana: sysy::ir::GCM Class Reference
sysy::ir::GCM Class Reference
#include <GCM.h>
Public Member Functions
GCM ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void schduleEarly (Instruction *instr)
void schduleLate (Instruction *instr)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
GCM()
sysy::ir::GCM::GCM ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
getName()
std::string sysy::ir::GCM::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::GCM::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::Function::getEntryBlock(), sysy::ir::Value::getName(), sysy::ir::instrSchduled, PrintMsg, schduleEarly(), and schduleLate().
schduleEarly()
void sysy::ir::GCM::schduleEarly (Instruction * instr) private
References sysy::ir::canBeSchduled, sysy::ir::Instruction::getBasicBlock(), sysy::ir::BasicBlock::getDoms(), sysy::ir::Function::getEntryBlock(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::User::getOprands(), sysy::ir::BasicBlock::getParent(), and sysy::ir::instrSchduled.
Referenced by run().
schduleLate()
void sysy::ir::GCM::schduleLate (Instruction * instr) private
References sysy::ir::best, sysy::ir::canBeSchduled, sysy::ir::Instruction::getBasicBlock(), sysy::ir::BasicBlock::getIdom(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getParent(), sysy::ir::Instruction::getRank(), sysy::ir::Value::getUses(), sysy::ir::instrSchduled, sysy::ir::lcaCompute(), and sysy::ir::Instruction::reSetBasicBlock().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/GCM.h
lib/Transform/Scalar/GCM.cpp