Diana: SysYParser::FuncFParamContext Class Reference
SysYParser::FuncFParamContext Class Reference
#include <SysYParser.h>
Public Member Functions
FuncFParamContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
BTypeContext * bType ()
antlr4::tree::TerminalNode * Ident ()
std::vector< antlr4::tree::TerminalNode * > LSBRA ()
antlr4::tree::TerminalNode * LSBRA (size_t i)
std::vector< antlr4::tree::TerminalNode * > RSBRA ()
antlr4::tree::TerminalNode * RSBRA (size_t i)
std::vector< ExpContext * > exp ()
ExpContext * exp (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
FuncFParamContext()
SysYParser::FuncFParamContext::FuncFParamContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::FuncFParamContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
bType()
SysYParser::BTypeContext * SysYParser::FuncFParamContext::bType ()
Referenced by sysy::SysYVisitor::visitFuncFParam().
exp() [1/2]
std::vector< SysYParser::ExpContext * > SysYParser::FuncFParamContext::exp ()
Referenced by sysy::SysYVisitor::visitFuncFParam().
exp() [2/2]
SysYParser::ExpContext * SysYParser::FuncFParamContext::exp (size_t i)
getRuleIndex()
size_t SysYParser::FuncFParamContext::getRuleIndex () const override virtual
References SysYParser::RuleFuncFParam.
Ident()
tree::TerminalNode * SysYParser::FuncFParamContext::Ident ()
References SysYParser::Ident.
Referenced by sysy::SysYVisitor::visitFuncFParam().
LSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::FuncFParamContext::LSBRA ()
References SysYParser::LSBRA.
Referenced by sysy::SysYVisitor::visitFuncFParam().
LSBRA() [2/2]
tree::TerminalNode * SysYParser::FuncFParamContext::LSBRA (size_t i)
References SysYParser::LSBRA.
RSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::FuncFParamContext::RSBRA ()
References SysYParser::RSBRA.
RSBRA() [2/2]
tree::TerminalNode * SysYParser::FuncFParamContext::RSBRA (size_t i)
References SysYParser::RSBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp