Diana: SysYParser::VarDefContext Class Reference
SysYParser::VarDefContext Class Reference
#include <SysYParser.h>
Public Member Functions
VarDefContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * Ident ()
std::vector< antlr4::tree::TerminalNode * > LSBRA ()
antlr4::tree::TerminalNode * LSBRA (size_t i)
std::vector< ConstExpContext * > constExp ()
ConstExpContext * constExp (size_t i)
std::vector< antlr4::tree::TerminalNode * > RSBRA ()
antlr4::tree::TerminalNode * RSBRA (size_t i)
antlr4::tree::TerminalNode * AGN ()
InitValContext * initVal ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
VarDefContext()
SysYParser::VarDefContext::VarDefContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::VarDefContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
AGN()
tree::TerminalNode * SysYParser::VarDefContext::AGN ()
References SysYParser::AGN.
constExp() [1/2]
std::vector< SysYParser::ConstExpContext * > SysYParser::VarDefContext::constExp ()
Referenced by sysy::SysYVisitor::visitVarDef().
constExp() [2/2]
SysYParser::ConstExpContext * SysYParser::VarDefContext::constExp (size_t i)
getRuleIndex()
size_t SysYParser::VarDefContext::getRuleIndex () const override virtual
References SysYParser::RuleVarDef.
Ident()
tree::TerminalNode * SysYParser::VarDefContext::Ident ()
References SysYParser::Ident.
Referenced by sysy::SysYVisitor::visitVarDef().
initVal()
SysYParser::InitValContext * SysYParser::VarDefContext::initVal ()
Referenced by sysy::SysYVisitor::visitVarDef().
LSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::VarDefContext::LSBRA ()
References SysYParser::LSBRA.
LSBRA() [2/2]
tree::TerminalNode * SysYParser::VarDefContext::LSBRA (size_t i)
References SysYParser::LSBRA.
RSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::VarDefContext::RSBRA ()
References SysYParser::RSBRA.
RSBRA() [2/2]
tree::TerminalNode * SysYParser::VarDefContext::RSBRA (size_t i)
References SysYParser::RSBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp