Diana: sysy::ir::GEPInstruction Class Reference
sysy::ir::GEPInstruction Class Reference
#include <Instructions.h>
Classes
class IndexIterator
Public Types
using indexRange = iterator_range< IndexIterator >
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Public Member Functions
GEPInstruction (Type *_type, Value *_ptr, std::vector< Value * > _idxList, BasicBlock *_father, std::string _name="")
Value * getPtr ()
Value * getIndex (unsigned i)
size_t size ()
indexRange getIndex ()
bool hasAllZeroIndices ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::MemoryInstruction
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Additional Inherited Members
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
indexRange
using sysy::ir::GEPInstruction::indexRange = iterator_range<IndexIterator>
Constructor & Destructor Documentation
GEPInstruction()
sysy::ir::GEPInstruction::GEPInstruction (Type * _type, Value * _ptr, std::vector< Value * > _idxList, BasicBlock * _father, std::string _name = "")
References sysy::ir::User::addOperand().
Member Function Documentation
getIndex() [1/2]
GEPInstruction::indexRange sysy::ir::GEPInstruction::getIndex ()
References sysy::make_range(), and sysy::ir::User::operands.
Referenced by getSignature(), and hasAllZeroIndices().
getIndex() [2/2]
Value* sysy::ir::GEPInstruction::getIndex (unsigned i) inline
References sysy::ir::User::operands.
Referenced by sysy::ir::GVN::getValueNumber().
getPtr()
Value* sysy::ir::GEPInstruction::getPtr () inline
References sysy::ir::User::operands.
Referenced by getSignature(), and sysy::ir::GVN::getValueNumber().
getSignature()
std::string sysy::ir::GEPInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References sysy::iterator_range< IteratorT >::begin(), sysy::iterator_range< IteratorT >::end(), sysy::ir::PointerType::get(), getIndex(), sysy::ir::Type::getInnerType(), getPtr(), sysy::ir::Type::getSignature(), sysy::ir::PointerType::getSignature(), sysy::ir::Value::getType(), sysy::ir::getVariable(), and sysy::ir::nameIs().
hasAllZeroIndices()
bool sysy::ir::GEPInstruction::hasAllZeroIndices ()
References getIndex().
size()
size_t sysy::ir::GEPInstruction::size () inline
References sysy::ir::User::operands.
Referenced by sysy::ir::GVN::getValueNumber().
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/Instructions.cpp
lib/IR/IRDump.cpp