Diana: sysy::ir::Memory2Reg Class Reference
sysy::ir::Memory2Reg Class Reference
#include <Memory2Reg.h>
Public Member Functions
Memory2Reg ()
std::string getName () override
void run (Function *func) override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
bool isAllocaPromotable (AllocaInst *alloca)
bool allocaSimplify (AllocaInst *alloca)
void analysisAlloca (AllocaInst *alloca)
void computeLiveIn (AllocaInst *alloca, std::set< BasicBlock * > &liveInBasicBlock)
void renameAllocaInBB (AllocaInst *alloca, BasicBlock *bb, BasicBlock *pred)
void queuePhi (AllocaInst *alloca, BasicBlock *father)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
Memory2Reg()
sysy::ir::Memory2Reg::Memory2Reg ()
References sysy::Pass< Opt >::getRelated().
Member Function Documentation
allocaSimplify()
bool sysy::ir::Memory2Reg::allocaSimplify (AllocaInst * alloca) private
References sysy::ir::allocaDefUse, sysy::ir::allocaToRemove, sysy::ir::allocaUseDef, analysisAlloca(), sysy::ir::Value::getUses(), sysy::ir::info, and sysy::ir::Value::removeAllUseWith().
Referenced by run().
analysisAlloca()
void sysy::ir::Memory2Reg::analysisAlloca (AllocaInst * alloca) private
References sysy::ir::allocaDefUse, sysy::ir::allocaUseDef, sysy::ir::AllocaInfo::get(), sysy::ir::AllocaInfo::getBlock(), sysy::ir::AllocaInfo::getDefBlocks(), sysy::ir::AllocaInfo::getLoad(), sysy::ir::AllocaInfo::getStore(), sysy::ir::AllocaInfo::getUseBlocks(), sysy::ir::Value::getUses(), sysy::ir::info, sysy::ir::less(), and sysy::ir::AllocaInfo::unLockLoad.
Referenced by allocaSimplify().
computeLiveIn()
void sysy::ir::Memory2Reg::computeLiveIn (AllocaInst * alloca, std::set< BasicBlock * > & liveInBasicBlock) private
References sysy::ir::allocaUseDef, sysy::ir::BasicBlock::BasicBlockDfsInv(), and sysy::ir::info.
Referenced by run().
getName()
std::string sysy::ir::Memory2Reg::getName () inline override virtual
Implements sysy::Pass< Opt >.
isAllocaPromotable()
bool sysy::ir::Memory2Reg::isAllocaPromotable (AllocaInst * alloca) private
References sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Value::getType(), sysy::ir::Value::getUses(), sysy::ir::Type::isArrayTy(), and sysy::ir::Type::isPointerTy().
Referenced by run().
queuePhi()
void sysy::ir::Memory2Reg::queuePhi (AllocaInst * alloca, BasicBlock * father) private
References sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Value::getName(), sysy::ir::info, sysy::ir::BasicBlock::insertFront(), and sysy::ir::phiCheck.
Referenced by run().
renameAllocaInBB()
void sysy::ir::Memory2Reg::renameAllocaInBB (AllocaInst * alloca, BasicBlock * bb, BasicBlock * pred) private
References sysy::ir::allocaDefUse, sysy::ir::allocaUseDef, sysy::ir::UndefValue::Create(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::IncomingValsInBB, sysy::ir::info, and sysy::ir::Value::replaceAllUseWith().
Referenced by run().
run()
void sysy::ir::Memory2Reg::run (Function * func) override
References sysy::ir::allocaDefUse, allocaSimplify(), sysy::ir::allocaToRemove, sysy::ir::allocaUseDef, sysy::ir::BasicBlock::BasicBlockDfs(), computeLiveIn(), sysy::ir::UndefValue::Create(), sysy::ir::BasicBlock::getDomFrontier(), sysy::ir::Function::getEntryBlock(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getSuccessor(), sysy::ir::IncomingValsInBB, sysy::ir::info, isAllocaPromotable(), sysy::ir::phiCheck, queuePhi(), sysy::ir::BasicBlock::rankReorder(), and renameAllocaInBB().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/Memory2Reg.h
lib/Transform/Utils/Memory2Reg.cpp