Diana: SysYParser::InitValContext Class Reference
SysYParser::InitValContext Class Reference
#include <SysYParser.h>
Public Member Functions
InitValContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
ExpContext * exp ()
antlr4::tree::TerminalNode * LCBRA ()
antlr4::tree::TerminalNode * RCBRA ()
std::vector< InitValContext * > initVal ()
InitValContext * initVal (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
InitValContext()
SysYParser::InitValContext::InitValContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::InitValContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::InitValContext::COMMA ()
References SysYParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * SysYParser::InitValContext::COMMA (size_t i)
References SysYParser::COMMA.
exp()
SysYParser::ExpContext * SysYParser::InitValContext::exp ()
Referenced by sysy::SysYVisitor::varInitValDfs(), and sysy::SysYVisitor::visitInitVal().
getRuleIndex()
size_t SysYParser::InitValContext::getRuleIndex () const override virtual
References SysYParser::RuleInitVal.
initVal() [1/2]
std::vector< SysYParser::InitValContext * > SysYParser::InitValContext::initVal ()
Referenced by sysy::SysYVisitor::varInitValDfs(), and sysy::SysYVisitor::visitInitVal().
initVal() [2/2]
SysYParser::InitValContext * SysYParser::InitValContext::initVal (size_t i)
LCBRA()
tree::TerminalNode * SysYParser::InitValContext::LCBRA ()
References SysYParser::LCBRA.
RCBRA()
tree::TerminalNode * SysYParser::InitValContext::RCBRA ()
References SysYParser::RCBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp