Diana: sysy::iterator_range< IteratorT > Class Template Reference
sysy::iterator_range< IteratorT > Class Template Reference
#include <iterator_range.h>
Public Member Functions
template<typename Container >
iterator_range (Container &&c)
iterator_range (IteratorT begin_iterator, IteratorT end_iterator)
IteratorT begin () const
IteratorT end () const
bool empty () const
Private Attributes
IteratorT begin_iterator
IteratorT end_iterator
Constructor & Destructor Documentation
iterator_range() [1/2]
template<typename IteratorT > template<typename Container > sysy::iterator_range< IteratorT >::iterator_range (Container && c) inline
iterator_range() [2/2]
template<typename IteratorT > sysy::iterator_range< IteratorT >::iterator_range (IteratorT begin_iterator, IteratorT end_iterator) inline
Member Function Documentation
begin()
template<typename IteratorT > IteratorT sysy::iterator_range< IteratorT >::begin () const inline
References sysy::iterator_range< IteratorT >::begin_iterator.
Referenced by sysy::ir::CallInstruction::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), and sysy::ir::MemPhiInstruction::getSignature().
empty()
template<typename IteratorT > bool sysy::iterator_range< IteratorT >::empty () const inline
References sysy::iterator_range< IteratorT >::begin_iterator, and sysy::iterator_range< IteratorT >::end_iterator.
end()
template<typename IteratorT > IteratorT sysy::iterator_range< IteratorT >::end () const inline
References sysy::iterator_range< IteratorT >::end_iterator.
Referenced by sysy::ir::CallInstruction::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), and sysy::ir::MemPhiInstruction::getSignature().
Member Data Documentation
begin_iterator
template<typename IteratorT > IteratorT sysy::iterator_range< IteratorT >::begin_iterator private
Referenced by sysy::iterator_range< IteratorT >::begin(), and sysy::iterator_range< IteratorT >::empty().
end_iterator
template<typename IteratorT > IteratorT sysy::iterator_range< IteratorT >::end_iterator private
Referenced by sysy::iterator_range< IteratorT >::empty(), and sysy::iterator_range< IteratorT >::end().
The documentation for this class was generated from the following file:
include/sysy/Support/iterator_range.h