Diana: SysYParser::EqExpContext Class Reference
SysYParser::EqExpContext Class Reference
#include <SysYParser.h>
Public Member Functions
EqExpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
RelExpContext * relExp ()
EqExpContext * eqExp ()
antlr4::tree::TerminalNode * EQL ()
antlr4::tree::TerminalNode * NEQ ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
EqExpContext()
SysYParser::EqExpContext::EqExpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::EqExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
eqExp()
SysYParser::EqExpContext * SysYParser::EqExpContext::eqExp ()
Referenced by sysy::SysYVisitor::visitEqExp().
EQL()
tree::TerminalNode * SysYParser::EqExpContext::EQL ()
References SysYParser::EQL.
Referenced by sysy::SysYVisitor::visitEqExp().
getRuleIndex()
size_t SysYParser::EqExpContext::getRuleIndex () const override virtual
References SysYParser::RuleEqExp.
NEQ()
tree::TerminalNode * SysYParser::EqExpContext::NEQ ()
References SysYParser::NEQ.
relExp()
SysYParser::RelExpContext * SysYParser::EqExpContext::relExp ()
Referenced by sysy::SysYVisitor::visitEqExp().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp