Diana: sysy::ir::PointerType Class Reference
sysy::ir::PointerType Class Reference
#include <Type.h>
Public Member Functions
PointerType (Type *_inner)
PointerType ()
Type * getInnerType () override
std::string getSignature () override
size_t getAllocatedSize () override
Public Member Functions inherited from sysy::ir::Type
bool isFloatTy ()
bool isVoidTy ()
bool isLabelTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned width)
bool isFunctionTy ()
bool isPointerTy ()
bool isVectorTy ()
bool isArrayTy ()
bool isUndefTy ()
Static Public Member Functions
static PointerType * get (Type *inner)
static PointerType * getInt8PtrTy ()
static PointerType * getInt32PtrTy ()
static PointerType * getFloatPtrTy ()
Static Public Member Functions inherited from sysy::ir::Type
static Type * getFloatTy ()
static Type * getVoidTy ()
static Type * getUndefTy ()
static Type * getFunctionTy (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static Type * getLabelTy ()
static Type * getIntegerTy (unsigned width)
static Type * getInt1Ty ()
static Type * getInt32Ty ()
static Type * getInt8Ty ()
static Type * getPointerTy (Type *inner)
static Type * getArrayTy (Type *inner, unsigned size)
static Type * getInt8PtrTy ()
static Type * getInt32PtrTy ()
static Type * getFloatPtrTy ()
Private Attributes
Type * inner
Additional Inherited Members
Public Types inherited from sysy::ir::Type
enum TypeID {
FloatTyID = 0, VoidTyID, LabelTyID, IntegerTyID,
FunctionTyID, PointerTyID, ArrayTyID, FixedVectorTyID,
ScalableVectorTyID, UndefTyID
}
Protected Member Functions inherited from sysy::ir::Type
Type (TypeID id)
TypeID getTypeId ()
unsigned getSize ()
Constructor & Destructor Documentation
PointerType() [1/2]
sysy::ir::PointerType::PointerType (Type * _inner) inline
PointerType() [2/2]
sysy::ir::PointerType::PointerType () inline
Referenced by get().
Member Function Documentation
get()
PointerType * sysy::ir::PointerType::get (Type * inner) static
References sysy::ir::Context::getInstance(), inner, and PointerType().
Referenced by sysy::ir::IRBuilder::CreateInBoundsGEP(), getFloatPtrTy(), getInt32PtrTy(), getInt8PtrTy(), sysy::ir::Type::getPointerTy(), and sysy::ir::GEPInstruction::getSignature().
getAllocatedSize()
size_t sysy::ir::PointerType::getAllocatedSize () inline override virtual
Implements sysy::ir::Type.
getFloatPtrTy()
PointerType * sysy::ir::PointerType::getFloatPtrTy () static
References get(), and sysy::ir::Type::getFloatTy().
Referenced by sysy::ir::Type::getFloatPtrTy().
getInnerType()
Type* sysy::ir::PointerType::getInnerType () inline override virtual
Implements sysy::ir::Type.
References inner.
getInt32PtrTy()
PointerType * sysy::ir::PointerType::getInt32PtrTy () static
References get(), and sysy::ir::Type::getInt32Ty().
Referenced by sysy::ir::Type::getInt32PtrTy().
getInt8PtrTy()
PointerType * sysy::ir::PointerType::getInt8PtrTy () static
References get(), and sysy::ir::Type::getInt8Ty().
Referenced by sysy::ir::Type::getInt8PtrTy().
getSignature()
std::string sysy::ir::PointerType::getSignature () inline override virtual
Implements sysy::ir::Type.
References sysy::ir::Type::getSignature(), and inner.
Referenced by sysy::ir::GEPInstruction::getSignature().
Member Data Documentation
inner
Type* sysy::ir::PointerType::inner private
Referenced by get(), getInnerType(), and getSignature().
The documentation for this class was generated from the following files:
include/sysy/IR/Type.h
lib/IR/Type.cpp