Diana: sysy::ir::CollectOccurrences Class Reference
sysy::ir::CollectOccurrences Class Reference
#include <PRE.h>
Public Member Functions
CollectOccurrences (Instruction *key)
bool isSameExpr (Instruction *expr)
void addExpr (Instruction *instr)
size_t phiSize ()
void addPhi (PhiOccurrence *phi, BasicBlock *bb)
PhiOccurrence * getPhi (BasicBlock *bb)
std::vector< Instruction * > & getExprFromBB (BasicBlock *bb)
std::unordered_set< BasicBlock * > & getRealOccurrencesBB ()
std::unordered_set< BasicBlock * > & getPhiBB ()
Public Attributes
std::unordered_map< Instruction *, Occurrence * > occurrenceName
std::unordered_set< Occurrence * > allClasses
Private Attributes
Instruction * keyInstr
std::unordered_set< BasicBlock * > realOccurrencesBB
std::unordered_set< BasicBlock * > phiBB
std::unordered_map< BasicBlock *, std::vector< Instruction * > > instructions
std::unordered_map< BasicBlock *, PhiOccurrence * > phis
Constructor & Destructor Documentation
CollectOccurrences()
sysy::ir::CollectOccurrences::CollectOccurrences (Instruction * key)
Member Function Documentation
addExpr()
void sysy::ir::CollectOccurrences::addExpr (Instruction * instr)
References sysy::ir::Instruction::getBasicBlock(), instructions, and realOccurrencesBB.
addPhi()
void sysy::ir::CollectOccurrences::addPhi (PhiOccurrence * phi, BasicBlock * bb)
References phiBB, and phis.
getExprFromBB()
std::vector< Instruction * > & sysy::ir::CollectOccurrences::getExprFromBB (BasicBlock * bb)
References instructions.
Referenced by sysy::ir::PRE::rename1().
getPhi()
PhiOccurrence* sysy::ir::CollectOccurrences::getPhi (BasicBlock * bb) inline
References phis.
Referenced by sysy::ir::PRE::computeCanBeAvail(), sysy::ir::PRE::computeLater(), sysy::ir::PRE::downSafety(), sysy::ir::PRE::rename1(), sysy::ir::PRE::rename2(), sysy::ir::PRE::resetCanBeAvail(), and sysy::ir::PRE::resetLater().
getPhiBB()
std::unordered_set<BasicBlock*>& sysy::ir::CollectOccurrences::getPhiBB () inline
References phiBB.
Referenced by sysy::ir::PRE::computeCanBeAvail(), sysy::ir::PRE::computeLater(), sysy::ir::PRE::downSafety(), sysy::ir::PRE::rename1(), sysy::ir::PRE::rename2(), sysy::ir::PRE::resetCanBeAvail(), and sysy::ir::PRE::resetLater().
getRealOccurrencesBB()
std::unordered_set<BasicBlock*>& sysy::ir::CollectOccurrences::getRealOccurrencesBB () inline
References realOccurrencesBB.
Referenced by sysy::ir::PRE::rename1().
isSameExpr()
bool sysy::ir::CollectOccurrences::isSameExpr (Instruction * expr)
References sysy::ir::Instruction::getKind(), sysy::ir::User::getOprands(), sysy::ir::Instruction::isCommutative(), keyInstr, and sysy::ir::PRE::sameOriginal().
phiSize()
size_t sysy::ir::CollectOccurrences::phiSize () inline
References phis.
Referenced by sysy::ir::PRE::rename1().
Member Data Documentation
allClasses
std::unordered_set<Occurrence*> sysy::ir::CollectOccurrences::allClasses
Referenced by sysy::ir::PRE::finalize1(), and sysy::ir::PRE::rename1().
instructions
std::unordered_map<BasicBlock*, std::vector<Instruction*> > sysy::ir::CollectOccurrences::instructions private
Referenced by addExpr(), and getExprFromBB().
keyInstr
Instruction* sysy::ir::CollectOccurrences::keyInstr private
Referenced by isSameExpr().
occurrenceName
std::unordered_map<Instruction*, Occurrence*> sysy::ir::CollectOccurrences::occurrenceName
Referenced by sysy::ir::PRE::rename1().
phiBB
std::unordered_set<BasicBlock*> sysy::ir::CollectOccurrences::phiBB private
Referenced by addPhi(), and getPhiBB().
phis
std::unordered_map<BasicBlock*, PhiOccurrence*> sysy::ir::CollectOccurrences::phis private
Referenced by addPhi(), getPhi(), and phiSize().
realOccurrencesBB
std::unordered_set<BasicBlock*> sysy::ir::CollectOccurrences::realOccurrencesBB private
Referenced by addExpr(), and getRealOccurrencesBB().
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/PRE.h
lib/Transform/Scalar/PRE.cpp