Diana: sysy::ir Namespace Reference
sysy::ir Namespace Reference
Classes
class ADCE
class AllocaInfo
class AllocaInstruction
class ArrayInfo
class ArrayType
class BasicBlock
class BasicBlockTarget
class BinaryInstrcution
class BrInstruction
class CallInstruction
class CleanExitBasicBlock
class ClearMemorySSA
struct cmpl
struct cmps
class CollectOccurrences
class Constant
class ConstantArray
class ConstantFP
class ConstantInt
class ConstantString
class ConstructExitBasicBlock
class Context
class DCE
class DeadInstruction
class DomFrontierGen
class DomInfo
class DomTreeGen
class EliminatePhi
class FloatType
class Function
class FunctionInline
class FunctionType
class FunctionVertify
class GCM
class GEPInstruction
class GlobalValue
class GVInfo
class GVN
class IdomGen
class Instruction
class InstructionCombine
class IntegerType
class IPAnalysis
class IPDCE
class IpdomGen
class IRBuilder
class IRCopier
class LableType
class LCSSA
class LinearScalarPass
class LoaclDCE
class LoadInstruction
class LocalGCM
class LocalGVN
class Loop
class LoopEarlyPass
class LoopInfo
class LoopParallel
class LoopUnrollAll
class LoopVariablePass
class LSR
class Memory2Reg
class MemoryInstruction
class MemorySSA
class MemPhiInstruction
class Module
class ModuleVertify
class MoveInstruction
class Occurrence
class PhiInstruction
class PhiOccurrence
class PointerType
class PostDomFrontierGen
class PostDomInfo
class PostDomTreeGen
class PRE
class RealOccurrence
class RetInstruction
class ScalarEvolution
class ScalarEvolutionClean
class ScalarPass
class SCEV
class SimplifyCFG
class SplitCriticalEdge
class SSASet
class StoreInstruction
class TerminatorInstruction
class Type
class UnaryInstruction
class UndefOccurrence
class UndefType
class UndefValue
class UnsetSSA
class Use
class User
class Value
class ValueScope
class VoidType
Typedefs
using BinaryInst = BinaryInstrcution
using UnaryInst = UnaryInstruction
using CallInst = CallInstruction
using BrInst = BrInstruction
using RetInst = RetInstruction
using StoreInst = StoreInstruction
using LoadInst = LoadInstruction
using GEPInst = GEPInstruction
using AllocaInst = AllocaInstruction
using PhiInst = PhiInstruction
using MemPhiInst = MemPhiInstruction
using DeadInst = DeadInstruction
using MoveInst = MoveInstruction
using LoopPass = Pass< Loop * >
using LoopPassManager = PassManager< Loop * >
using ModulePass = Pass< Module * >
using FunctionPass = Pass< Function * >
using BasicBlockPass = Pass< BasicBlock * >
using ModulePassManager = PassManager< Module * >
using FunctionPassManager = PassManager< Function * >
using BasicBlockPassManager = PassManager< BasicBlock * >
using BBset = std::set< BasicBlock * >
using Kind = Instruction::InstrKind
using InstrCpy = std::pair< Instruction *, std::vector< Value * > >
Functions
Value * getOriginArray (Value *ptr)
bool isArgArray (Value *val)
bool alias (Value *array1, Value *array2)
bool aliasAtCall (Value *array, CallInst *call)
BasicBlock * lcaCompute (BasicBlock *bb1, BasicBlock *bb2)
std::string dumpIR (Module *mod)
void dumpFunction (Function *func)
void dumpBasickBlock (BasicBlock *bb)
void llFileGen (Module *mod)
Value * irEmit (ExprNode *expr)
Value * irEmit (FunctionCallExprNode *funcCall)
Value * irEmit (BinaryExprNode *binExpr)
Value * irEmit (UnaryExprNode *unaryExpr)
Value * irEmit (NumberNode *number)
Value * irEmit (LvalNode *lval)
Value * irEmit (StmtNode *stmt)
Value * irEmit (BlockNode *block)
Value * irEmit (IfStmtNode *ifStmt)
Value * irEmit (AssignStmtNode *assignStmt)
Value * irEmit (ExprStmtNode *exprStmt)
Value * irEmit (ForStmtNode *forStmt)
Value * irEmit (WhileStmtNode *whileStmt)
Value * irEmit (BreakStmtNode *breakStmt)
Value * irEmit (ContinueStmtNode *continueStmt)
Value * irEmit (ReturnStmtNode *returnStmt)
Value * irEmit (DeclNode *decl)
Value * irEmit (ConstDeclNode *constDecl)
Value * irEmit (VarDeclNode *varDecl)
Function * irEmit (FuncDefNode *funcDef)
Module * emitIR (CompUnitNode *compUnit)
bool isSameType (ir::Type *type1, ir::Type *type2)
Value * simplifyInstruction (Instruction *instr)
Value * simplifyInstruction (BinaryInst *bin)
Value * simplifyInstruction (UnaryInst *unary)
Value * constantFold (BinaryInst *bin)
Value * constantFold (UnaryInst *unary)
Value * simplifyInstruction (PhiInst *phi)
void initialIRTransform (std::string opt, ModulePassManager *pm)
bool less (LoadInst *load, StoreInst *store)
bool less (StoreInst *store, LoadInst *load)
bool isGlobal (Value *val)
bool isLocal (Value *val)
bool isAliasByGVToArg (GlobalValue *gv, AllocaInst *arg)
static void clearIdomAll ()
static void clearIpdomAll ()
std::string to_hex (float f)
static std::string checkLabel (BasicBlock *bb, const std::string &label)
static std::string getLabel (BasicBlock *bb)
static std::string checkVariable (Instruction *instr, const std::string &variable)
static std::string getVariable (Instruction *instr)
static std::string nameIs (Value *val)
static void initRuntime ()
void getIDX (int index, const std::vector< int > &dims, std::vector< Value * > &IDX)
void emitInitial (Value *gpr, std::vector< std::unique_ptr< ExprNode >> &initial, ArrayType *type)
Function * createGlobalInit ()
Function * createGlobalInit (GlobalValue *G, std::vector< std::unique_ptr< ExprNode >> &initial)
static Value * getElementPtr (AllocaInstruction *A, std::vector< std::unique_ptr< ExprNode >> &expr)
static Value * getPtrPtr (AllocaInstruction *A, std::vector< std::unique_ptr< ExprNode >> &expr)
static Value * getElementPtr (GlobalValue *G, std::vector< std::unique_ptr< ExprNode >> &expr)
static AllocaInstruction * CreateEntryBlockAlloca (Function *TheFunction, const std::string &VarName, Type *&type, std::vector< int > dimSize)
static AllocaInstruction * CreateEntryBlockAlloca (Function *TheFunction, const std::string &VarName, Type *type)
static void globalInit ()
Value * privateInit (Constant *initial, Type *type, std::string name, bool is_constant)
bool getNumberArray (std::vector< std::unique_ptr< ExprNode >> &initial, std::vector< NumberNode * > &constInital)
Constant * getConstantArray (std::vector< NumberNode * > constInitial, ArrayType *type)
GlobalValue * createGlobal (VarDefNode *def, AstType type)
GlobalValue * createGlobal (ConstDefNode *def, AstType type)
SCEV operator+ (Value *lhs, const SCEV &rhs)
SCEV operator+ (const SCEV &lhs, const SCEV &rhs)
SCEV operator- (const SCEV &lhs, Value *rhs)
SCEV operator- (const SCEV &lhs, const SCEV &rhs)
SCEV operator* (Value *lhs, const SCEV &rhs)
static void replace (Instruction *instr, Value *value)
Variables
static std::unordered_map< BasicBlock *, BasicBlock * > parent
static std::unordered_map< BasicBlock *, BasicBlock * > ancenstor
static std::unordered_map< BasicBlock *, BasicBlock * > best
static std::unordered_map< BasicBlock *, int > semi
static std::unordered_map< BasicBlock *, BasicBlock * > child
static std::unordered_map< BasicBlock *, BasicBlock * > samedom
static std::unordered_map< BasicBlock *, int > rank
static std::map< BasicBlock *, BBset > bucket
static std::vector< BasicBlock * > dfnumVertex
static std::set< BasicBlock * > doms
static std::unordered_map< BasicBlock *, BasicBlock * > parent
static std::unordered_map< BasicBlock *, BasicBlock * > ancenstor
static std::unordered_map< BasicBlock *, BasicBlock * > best
static std::unordered_map< BasicBlock *, int > semi
static std::unordered_map< BasicBlock *, BasicBlock * > child
static std::unordered_map< BasicBlock *, BasicBlock * > samedom
static std::unordered_map< BasicBlock *, int > rank
static std::map< BasicBlock *, BBset > bucket
static std::vector< BasicBlock * > dfnumVertex
static std::set< BasicBlock * > pdoms
static std::multiset< std::string > variableCounter
static std::multiset< std::string > labelCounter
static std::map< BasicBlock *, std::string > labelName
static std::map< Instruction *, std::string > variableName
static std::string UnaryOps [] = { "neg", "not", "fneg", "fptosi", "sitofp", "bitcast" }
static std::string binaryOps []
const std::string runtime = "runtime/sylib.ll"
static IRBuilder Builder
static std::vector< Function * > InitFuncList
struct {
Type * sysy::ir::retType
std::vector< Type * > sysy::ir::argType
std::string sysy::ir::funcName
bool sysy::ir::isVarArg
} funcInclude [FUNC_NUM]
int cnt = 0
constexpr int maxTripCount = 80
static std::unordered_set< Instruction * > AliveCode
static std::unordered_set< BasicBlock * > AliveBB
static std::unordered_set< Instruction * > AliveCode
static std::unordered_set< Instruction * > instrSchduled
auto canBeSchduled
static bool fixed
static std::unordered_map< Value *, Value * > ValueNumber
static std::vector< Instruction * > InstrToRemove
static std::vector< CollectOccurrences > collectOccurrencesList
static std::unordered_set< PhiOccurrence * > downSafe
static std::unordered_map< PhiOccurrence *, std::unordered_set< int > > hasRealUse
static std::unordered_map< PhiOccurrence *, BasicBlock * > crossReal
static int varCnt
static std::unordered_set< PhiOccurrence * > canBeAvail
static std::unordered_set< PhiOccurrence * > later
static std::unordered_map< StoreInst *, std::set< LoadInst * > > allocaDefUse
static std::unordered_map< LoadInst *, StoreInst * > allocaUseDef
static std::unordered_map< AllocaInst *, AllocaInfo > info
static std::unordered_map< PhiInst *, AllocaInst * > phiCheck
static std::vector< AllocaInst * > allocaToRemove
std::unordered_map< BasicBlock *, std::unordered_map< AllocaInst *, Value * > > IncomingValsInBB
static std::unordered_map< Instruction *, LoadInst * > globalValueDefUse
static std::unordered_map< LoadInst *, Instruction * > globalValueUseDef
static std::unordered_map< GlobalValue *, GVInfo > globalValueInfo
std::unordered_map< BasicBlock *, std::unordered_map< GlobalValue *, Value * > > IncomingGVStoreInBB
std::unordered_map< BasicBlock *, std::unordered_map< GlobalValue *, Value * > > IncomingGVLoadInBB
static std::unordered_map< Instruction *, LoadInst * > arrayDefUse
static std::unordered_map< LoadInst *, Instruction * > arrayUseDef
static std::unordered_map< Value *, ArrayInfo > info
std::unordered_map< BasicBlock *, std::unordered_map< Value *, Value * > > IncomingStoreInBB
std::unordered_map< LoadInst *, LoadInst * > LoadCoverLoad
std::unordered_map< BasicBlock *, std::unordered_map< Value *, Value * > > IncomingLoadInBB
Typedef Documentation
AllocaInst
using sysy::ir::AllocaInst = typedef AllocaInstruction
BasicBlockPass
using sysy::ir::BasicBlockPass = typedef Pass<BasicBlock*>
BasicBlockPassManager
using sysy::ir::BasicBlockPassManager = typedef PassManager<BasicBlock*>
BBset
typedef std::set< BasicBlock * > sysy::ir::BBset
BinaryInst
using sysy::ir::BinaryInst = typedef BinaryInstrcution
BrInst
using sysy::ir::BrInst = typedef BrInstruction
CallInst
using sysy::ir::CallInst = typedef CallInstruction
DeadInst
using sysy::ir::DeadInst = typedef DeadInstruction
FunctionPass
using sysy::ir::FunctionPass = typedef Pass<Function*>
FunctionPassManager
using sysy::ir::FunctionPassManager = typedef PassManager<Function*>
GEPInst
using sysy::ir::GEPInst = typedef GEPInstruction
InstrCpy
using sysy::ir::InstrCpy = typedef std::pair<Instruction*, std::vector<Value*> >
Kind
typedef Instruction::InstrKind sysy::ir::Kind
LoadInst
using sysy::ir::LoadInst = typedef LoadInstruction
LoopPass
using sysy::ir::LoopPass = typedef Pass<Loop*>
LoopPassManager
using sysy::ir::LoopPassManager = typedef PassManager<Loop*>
MemPhiInst
using sysy::ir::MemPhiInst = typedef MemPhiInstruction
ModulePass
using sysy::ir::ModulePass = typedef Pass<Module*>
ModulePassManager
using sysy::ir::ModulePassManager = typedef PassManager<Module*>
MoveInst
using sysy::ir::MoveInst = typedef MoveInstruction
PhiInst
using sysy::ir::PhiInst = typedef PhiInstruction
RetInst
using sysy::ir::RetInst = typedef RetInstruction
StoreInst
using sysy::ir::StoreInst = typedef StoreInstruction
UnaryInst
using sysy::ir::UnaryInst = typedef UnaryInstruction
Function Documentation
alias()
bool sysy::ir::alias (Value * array1, Value * array2)
References isAliasByGVToArg(), isArgArray(), isGlobal(), and isLocal().
Referenced by aliasAtCall(), and sysy::ir::MemorySSA::computeArrayInfo().
aliasAtCall()
bool sysy::ir::aliasAtCall (Value * array, CallInst * call)
References alias(), sysy::ir::CallInstruction::getArgs(), sysy::ir::CallInstruction::getCallee(), and getOriginArray().
Referenced by sysy::ir::MemorySSA::computeArrayInfo().
checkLabel()
static std::string sysy::ir::checkLabel (BasicBlock * bb, const std::string & label) static
References labelCounter, and labelName.
Referenced by getLabel().
checkVariable()
static std::string sysy::ir::checkVariable (Instruction * instr, const std::string & variable) static
References variableCounter, and variableName.
Referenced by getVariable().
clearIdomAll()
static void sysy::ir::clearIdomAll () static
References ancenstor, best, bucket, child, dfnumVertex, parent, rank, samedom, and semi.
Referenced by sysy::ir::IdomGen::run().
clearIpdomAll()
static void sysy::ir::clearIpdomAll () static
References ancenstor, best, bucket, child, dfnumVertex, parent, rank, samedom, and semi.
Referenced by sysy::ir::IpdomGen::run().
constantFold() [1/2]
Value * sysy::ir::constantFold (BinaryInst * bin)
References sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), and sysy::ir::Instruction::isInteger().
Referenced by simplifyInstruction().
constantFold() [2/2]
Value * sysy::ir::constantFold (UnaryInst * unary)
References sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Instruction::getKind(), sysy::ir::UnaryInstruction::getValue(), and sysy::ir::Instruction::isInteger().
CreateEntryBlockAlloca() [1/2]
static AllocaInstruction* sysy::ir::CreateEntryBlockAlloca (Function * TheFunction, const std::string & VarName, Type *& type, std::vector< int > dimSize) static
References sysy::ir::BasicBlock::begin(), sysy::ir::IRBuilder::CreateAlloca(), sysy::ir::ArrayType::get(), sysy::ir::Function::getEntryBlock(), and sysy::type.
Referenced by irEmit().
CreateEntryBlockAlloca() [2/2]
static AllocaInstruction* sysy::ir::CreateEntryBlockAlloca (Function * TheFunction, const std::string & VarName, Type * type) static
References sysy::ir::BasicBlock::begin(), sysy::ir::IRBuilder::CreateAlloca(), sysy::ir::Function::getEntryBlock(), and sysy::type.
createGlobal() [1/2]
GlobalValue* sysy::ir::createGlobal (ConstDefNode * def, AstType type)
References sysy::ast::AstType2IrType(), sysy::ast::ConstDefNode::constInitVal, sysy::ir::GlobalValue::Create(), sysy::ast::ConstDefNode::dimSize, ErrorMsg, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::ArrayType::get(), getConstantArray(), getNumberArray(), sysy::ir::Constant::getZero(), sysy::ast::INT, sysy::ast::ConstDefNode::name, and sysy::type.
createGlobal() [2/2]
GlobalValue* sysy::ir::createGlobal (VarDefNode * def, AstType type)
References sysy::ast::AstType2IrType(), sysy::ir::GlobalValue::Create(), createGlobalInit(), sysy::ast::VarDefNode::dimSize, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::ArrayType::get(), getConstantArray(), getNumberArray(), sysy::ir::Constant::getZero(), InitFuncList, sysy::ast::INT, sysy::ast::VarDefNode::name, sysy::type, and sysy::ast::VarDefNode::varInitVal.
Referenced by emitIR().
createGlobalInit() [1/2]
Function* sysy::ir::createGlobalInit ()
References Builder, sysy::ir::Function::Create(), sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateCall(), sysy::ir::IRBuilder::CreateRetVoid(), sysy::ir::FunctionType::get(), sysy::ir::Type::getVoidTy(), InitFuncList, sysy::name, and sysy::ir::IRBuilder::SetInsertPoint().
Referenced by createGlobal(), and globalInit().
createGlobalInit() [2/2]
Function* sysy::ir::createGlobalInit (GlobalValue * G, std::vector< std::unique_ptr< ExprNode >> & initial)
References Builder, sysy::ir::Function::Create(), sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateRetVoid(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateStore(), emitInitial(), G, sysy::ir::FunctionType::get(), sysy::ir::Value::getType(), sysy::ir::Type::getVoidTy(), irEmit(), sysy::ir::Type::isIntegerTy(), isSameType(), sysy::name, and sysy::ir::IRBuilder::SetInsertPoint().
dumpBasickBlock()
void sysy::ir::dumpBasickBlock (BasicBlock * bb)
Referenced by sysy::ir::ADCE::findAliveCode(), and sysy::ir::CleanExitBasicBlock::run().
dumpFunction()
void sysy::ir::dumpFunction (Function * func)
Referenced by sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::ConstructExitBasicBlock::run(), sysy::ir::CleanExitBasicBlock::run(), and sysy::ir::SimplifyCFG::run().
dumpIR()
std::string sysy::ir::dumpIR (Module * mod)
References sysy::ir::Module::__function, sysy::ir::Module::__globalValue, and G.
Referenced by sysy::FrontendMain(), and sysy::ir::UnsetSSA::run().
emitInitial()
void sysy::ir::emitInitial (Value * gpr, std::vector< std::unique_ptr< ExprNode >> & initial, ArrayType * type)
References Builder, cnt, sysy::ir::IRBuilder::CreateCall(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateStore(), sysy::dims, sysy::ir::ConstantInt::get(), sysy::ir::Module::getFunction(), getIDX(), sysy::ir::Type::getInnerType(), sysy::ir::Module::getInstance(), sysy::ir::Value::getType(), irEmit(), sysy::ir::Type::isIntegerTy(), isSameType(), and sysy::type.
Referenced by createGlobalInit(), and irEmit().
emitIR()
Module * sysy::ir::emitIR (CompUnitNode * compUnit)
References createGlobal(), sysy::ast::CompUnitNode::element, sysy::ir::ValueScope::getCurrentPtr(), sysy::ir::Module::getInstance(), globalInit(), initRuntime(), irEmit(), sysy::ir::SimplifyCFG::removeDeadBB(), and sysy::type.
Referenced by sysy::FrontendMain().
getConstantArray()
Constant* sysy::ir::getConstantArray (std::vector< NumberNode * > constInitial, ArrayType * type)
References sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::ConstantArray::get(), sysy::ir::ConstantArray::getZero(), sysy::ir::Type::isIntegerTy(), and sysy::type.
Referenced by createGlobal(), and irEmit().
getElementPtr() [1/2]
static Value* sysy::ir::getElementPtr (AllocaInstruction * A, std::vector< std::unique_ptr< ExprNode >> & expr) static
References Builder, sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::ConstantInt::get(), sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Type::getInt32Ty(), and irEmit().
Referenced by irEmit().
getElementPtr() [2/2]
static Value* sysy::ir::getElementPtr (GlobalValue * G, std::vector< std::unique_ptr< ExprNode >> & expr) static
References Builder, sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), G, sysy::ir::ConstantInt::get(), sysy::ir::Type::getInt32Ty(), and irEmit().
getIDX()
void sysy::ir::getIDX (int index, const std::vector< int > & dims, std::vector< Value * > & IDX)
References sysy::dims, sysy::ir::ConstantInt::get(), and sysy::ir::Type::getInt32Ty().
Referenced by emitInitial().
getLabel()
static std::string sysy::ir::getLabel (BasicBlock * bb) static
References checkLabel(), sysy::ir::Value::getName(), and labelName.
Referenced by sysy::ir::BasicBlock::getSignature(), sysy::ir::BrInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), and sysy::ir::MemPhiInstruction::getSignature().
getNumberArray()
bool sysy::ir::getNumberArray (std::vector< std::unique_ptr< ExprNode >> & initial, std::vector< NumberNode * > & constInital)
Referenced by createGlobal(), and irEmit().
getOriginArray()
Value * sysy::ir::getOriginArray (Value * ptr)
Referenced by aliasAtCall(), sysy::ir::MemorySSA::computeArrayInfo(), sysy::ir::GVN::doPerInstr(), sysy::ir::LoopParallel::isParallelizable(), and sysy::ir::IPAnalysis::run().
getPtrPtr()
static Value* sysy::ir::getPtrPtr (AllocaInstruction * A, std::vector< std::unique_ptr< ExprNode >> & expr) static
References Builder, sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateLoad(), sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Type::getInnerType(), sysy::ir::Type::getInt32Ty(), sysy::ir::Value::getType(), and irEmit().
Referenced by irEmit().
getVariable()
static std::string sysy::ir::getVariable (Instruction * instr) static
References checkVariable(), sysy::ir::Value::getName(), and variableName.
Referenced by sysy::ir::BinaryInstrcution::getSignature(), sysy::ir::UnaryInstruction::getSignature(), sysy::ir::CallInstruction::getSignature(), sysy::ir::LoadInstruction::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::AllocaInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), sysy::ir::MemPhiInstruction::getSignature(), and nameIs().
globalInit()
static void sysy::ir::globalInit () static
References sysy::ir::BasicBlock::begin(), Builder, sysy::ir::IRBuilder::CreateCall(), createGlobalInit(), sysy::ir::Function::getEntryBlock(), sysy::ir::Module::getInstance(), InitFuncList, and sysy::ir::IRBuilder::SetInsertPoint().
Referenced by emitIR().
initialIRTransform()
void sysy::ir::initialIRTransform (std::string opt, ModulePassManager * pm)
References sysy::PassManager< Opt >::addPass().
Referenced by main().
initRuntime()
static void sysy::ir::initRuntime () static
References sysy::ir::Function::Create(), funcInclude, and sysy::ir::FunctionType::get().
Referenced by emitIR().
irEmit() [1/20]
Value * sysy::ir::irEmit (AssignStmtNode * assignStmt)
References Builder, sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateStore(), sysy::ast::AssignStmtNode::expr, sysy::ast::FLOAT, G, sysy::ir::ValueScope::getCurrentPtr(), getElementPtr(), sysy::ir::Type::getFloatTy(), sysy::ir::IntegerType::getInt32Ty(), getPtrPtr(), sysy::ast::INT, irEmit(), and sysy::ast::AssignStmtNode::lval.
irEmit() [2/20]
Value * sysy::ir::irEmit (BinaryExprNode * binExpr)
References sysy::ast::BOP_ADD, sysy::ast::BOP_DIV, sysy::ast::BOP_MOD, sysy::ast::BOP_MUL, sysy::ast::BOP_SUB, Builder, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateAdd(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::IRBuilder::CreateFAdd(), sysy::ir::IRBuilder::CreateFCmpUEQ(), sysy::ir::IRBuilder::CreateFCmpUGE(), sysy::ir::IRBuilder::CreateFCmpUGT(), sysy::ir::IRBuilder::CreateFCmpULE(), sysy::ir::IRBuilder::CreateFCmpULT(), sysy::ir::IRBuilder::CreateFCmpUNE(), sysy::ir::IRBuilder::CreateFDiv(), sysy::ir::IRBuilder::CreateFMul(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateFRem(), sysy::ir::IRBuilder::CreateFSub(), sysy::ir::IRBuilder::CreateICmpEQ(), sysy::ir::IRBuilder::CreateICmpNE(), sysy::ir::IRBuilder::CreateICmpSGE(), sysy::ir::IRBuilder::CreateICmpSGT(), sysy::ir::IRBuilder::CreateICmpSLE(), sysy::ir::IRBuilder::CreateICmpSLT(), sysy::ir::IRBuilder::CreateMul(), sysy::ir::IRBuilder::CreateSDiv(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateSRem(), sysy::ir::IRBuilder::CreateSub(), ErrorMsg, sysy::ir::BasicBlockTarget::exitFalse(), sysy::ir::BasicBlockTarget::exitTrue(), sysy::ast::FLOAT, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::BasicBlockTarget::getFalse(), sysy::ir::Type::getFloatTy(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::IntegerType::getInt32Ty(), sysy::ir::BasicBlock::getParent(), sysy::ir::BasicBlockTarget::getTrue(), sysy::ir::Value::getType(), sysy::ast::INT, irEmit(), sysy::ir::Type::isFloatTy(), sysy::ir::Type::isIntegerTy(), sysy::ast::BinaryExprNode::lhs, sysy::ast::BinaryExprNode::op, sysy::ast::BinaryExprNode::rhs, sysy::ast::ROP_AND, sysy::ast::ROP_EQL, sysy::ast::ROP_GEQ, sysy::ast::ROP_GRT, sysy::ast::ROP_LEQ, sysy::ast::ROP_LES, sysy::ast::ROP_NEQ, sysy::ast::ROP_OR, sysy::ir::BasicBlockTarget::setFalse(), sysy::ir::IRBuilder::SetInsertPoint(), sysy::ir::BasicBlockTarget::setTrue(), and sysy::ast::ExprNode::type.
irEmit() [3/20]
Value * sysy::ir::irEmit (BlockNode * block)
References sysy::ast::BlockNode::blockItems, sysy::ir::ValueScope::exitBlock(), sysy::ir::ValueScope::getCurrentPtr(), and irEmit().
irEmit() [4/20]
Value * sysy::ir::irEmit (BreakStmtNode * breakStmt)
References Builder, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::BasicBlockTarget::getAfter(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::BasicBlock::getParent(), and sysy::ir::IRBuilder::SetInsertPoint().
irEmit() [5/20]
Value * sysy::ir::irEmit (ConstDeclNode * constDecl)
References sysy::ast::AstType2IrType(), Builder, sysy::ast::ConstDeclNode::constDef, CreateEntryBlockAlloca(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateStore(), ErrorMsg, getConstantArray(), sysy::ir::ValueScope::getCurrentPtr(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::Value::getName(), getNumberArray(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), irEmit(), sysy::ir::Type::isIntegerTy(), isSameType(), sysy::name, privateInit(), sysy::type, and sysy::ast::DeclNode::type.
irEmit() [6/20]
Value * sysy::ir::irEmit (ContinueStmtNode * continueStmt)
References Builder, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::BasicBlockTarget::getEntry(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::BasicBlock::getParent(), and sysy::ir::IRBuilder::SetInsertPoint().
irEmit() [7/20]
Value * sysy::ir::irEmit (DeclNode * decl)
References irEmit().
irEmit() [8/20]
Value * sysy::ir::irEmit (ExprNode * expr)
Referenced by createGlobalInit(), emitInitial(), emitIR(), getElementPtr(), getPtrPtr(), and irEmit().
irEmit() [9/20]
Value * sysy::ir::irEmit (ExprStmtNode * exprStmt)
References sysy::ast::ExprStmtNode::expr, and irEmit().
irEmit() [10/20]
Value * sysy::ir::irEmit (ForStmtNode * forStmt)
References Builder, sysy::ast::ForStmtNode::cond, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::IRBuilder::CreateICmpNE(), sysy::ir::ConstantInt::get(), sysy::ir::Function::getBasicBlockList(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::Type::getInt1Ty(), sysy::ir::Type::getInt32Ty(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), sysy::ir::Constant::getZero(), sysy::ast::ForStmtNode::increment, sysy::ast::ForStmtNode::initial, irEmit(), sysy::ir::IRBuilder::SetInsertPoint(), sysy::ir::BasicBlockTarget::setLoop(), and sysy::ast::ForStmtNode::stmt.
irEmit() [11/20]
Function * sysy::ir::irEmit (FuncDefNode * funcDef)
References argType, sysy::ast::FuncDefNode::block, Builder, sysy::ir::Function::Create(), sysy::ir::BasicBlock::Create(), CreateEntryBlockAlloca(), sysy::ir::IRBuilder::CreateRet(), sysy::ir::IRBuilder::CreateRetVoid(), sysy::ir::IRBuilder::CreateStore(), ErrorMsg, sysy::ir::ValueScope::exitBlock(), sysy::ast::FLOAT, sysy::ast::FuncDefNode::funcName, sysy::ast::FuncDefNode::funcParamList, sysy::ast::FuncDefNode::funcType, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::ArrayType::get(), sysy::ir::FunctionType::get(), sysy::ir::Function::getArgs(), sysy::ir::ValueScope::getCurrentPtr(), sysy::ir::Type::getFloatTy(), sysy::ir::Type::getInt32Ty(), sysy::ir::Value::getName(), sysy::ir::Type::getPointerTy(), sysy::ir::FunctionType::getRet(), sysy::ir::Type::getVoidTy(), sysy::ast::INT, irEmit(), sysy::ir::Type::isFloatTy(), sysy::ir::Type::isIntegerTy(), sysy::ir::IRBuilder::SetInsertPoint(), sysy::type, and sysy::ast::VOID.
irEmit() [12/20]
Value * sysy::ir::irEmit (FunctionCallExprNode * funcCall)
References sysy::ir::Function::arg_size(), Builder, sysy::ir::IRBuilder::CreateCall(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateSIToFP(), ErrorMsg, sysy::ast::FunctionCallExprNode::format, sysy::ast::FunctionCallExprNode::funcName, sysy::ast::FunctionCallExprNode::funcParamList, sysy::ir::ConstantInt::get(), sysy::ir::Function::getArgs(), sysy::ir::Type::getFloatTy(), sysy::ir::Type::getInnerType(), sysy::ir::Module::getInstance(), sysy::ir::Type::getInt32Ty(), sysy::ir::Constant::getString(), sysy::ir::Value::getType(), irEmit(), sysy::ir::Type::isArrayTy(), sysy::ir::Type::isFloatTy(), sysy::ir::Type::isIntegerTy(), sysy::ir::Type::isPointerTy(), sysy::ast::ExprNode::type, and sysy::ast::VOID.
irEmit() [13/20]
Value * sysy::ir::irEmit (IfStmtNode * ifStmt)
References Builder, sysy::ast::IfStmtNode::cond, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::IRBuilder::CreateFCmpUNE(), sysy::ir::IRBuilder::CreateICmpNE(), sysy::ast::IfStmtNode::elseBlock, sysy::ir::BasicBlockTarget::exitCond(), sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Function::getBasicBlockList(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::Type::getInt1Ty(), sysy::ir::Type::getInt32Ty(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), sysy::ir::Constant::getZero(), irEmit(), sysy::ir::Type::isFloatTy(), sysy::ir::BasicBlockTarget::setCond(), sysy::ir::IRBuilder::SetInsertPoint(), sysy::ir::BasicBlock::setParent(), and sysy::ast::IfStmtNode::thenBlock.
irEmit() [14/20]
Value * sysy::ir::irEmit (LvalNode * lval)
References Builder, sysy::ir::IRBuilder::CreateLoad(), G, sysy::ir::ValueScope::getCurrentPtr(), getElementPtr(), sysy::ir::Type::getInnerType(), getPtrPtr(), sysy::ir::Value::getType(), sysy::ast::LvalNode::indexExpr, sysy::ir::Type::isArrayTy(), sysy::ir::Type::isPointerTy(), and sysy::ast::LvalNode::variable.
irEmit() [15/20]
Value * sysy::ir::irEmit (NumberNode * number)
References sysy::ast::FLOAT, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ast::Immediate::getFloat(), sysy::ast::Immediate::getInt(), sysy::ast::NumberNode::immediate, sysy::ast::INT, and sysy::ast::ExprNode::type.
irEmit() [16/20]
Value * sysy::ir::irEmit (ReturnStmtNode * returnStmt)
References Builder, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateRet(), sysy::ir::IRBuilder::CreateRetVoid(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ast::ReturnStmtNode::expr, sysy::ir::Type::getFloatTy(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::Type::getInt32Ty(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), sysy::ast::ReturnStmtNode::has_ret_val, irEmit(), sysy::ir::Type::isFloatTy(), sysy::ir::Type::isIntegerTy(), and sysy::ir::IRBuilder::SetInsertPoint().
irEmit() [17/20]
Value * sysy::ir::irEmit (StmtNode * stmt)
References ErrorMsg, and irEmit().
irEmit() [18/20]
Value * sysy::ir::irEmit (UnaryExprNode * unaryExpr)
References Builder, sysy::ir::IRBuilder::CreateFNeg(), sysy::ir::IRBuilder::CreateNeg(), sysy::ir::IRBuilder::CreateNot(), ErrorMsg, sysy::ast::UnaryExprNode::expr, sysy::ast::FLOAT, sysy::ast::INT, irEmit(), sysy::ast::UnaryExprNode::op, sysy::ast::ExprNode::type, sysy::ast::UOP_ADD, sysy::ast::UOP_NOT, and sysy::ast::UOP_SUB.
irEmit() [19/20]
Value * sysy::ir::irEmit (VarDeclNode * varDecl)
References sysy::ast::AstType2IrType(), Builder, CreateEntryBlockAlloca(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::IRBuilder::CreateStore(), emitInitial(), sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Instruction::getBasicBlock(), getConstantArray(), sysy::ir::ValueScope::getCurrentPtr(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::Type::getInt32Ty(), sysy::ir::Value::getName(), getNumberArray(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), sysy::ir::Constant::getZero(), irEmit(), sysy::ir::Type::isIntegerTy(), isSameType(), sysy::name, privateInit(), sysy::type, sysy::ast::DeclNode::type, and sysy::ast::VarDeclNode::varDef.
irEmit() [20/20]
Value * sysy::ir::irEmit (WhileStmtNode * whileStmt)
References Builder, sysy::ast::WhileStmtNode::cond, sysy::ir::BasicBlock::Create(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::IRBuilder::CreateICmpNE(), sysy::ir::BasicBlockTarget::exitCond(), sysy::ir::BasicBlockTarget::exitLoop(), sysy::ir::ConstantInt::get(), sysy::ir::Function::getBasicBlockList(), sysy::ir::IRBuilder::GetInsertBlock(), sysy::ir::BasicBlockTarget::getInstance(), sysy::ir::Type::getInt1Ty(), sysy::ir::Type::getInt32Ty(), sysy::ir::BasicBlock::getParent(), sysy::ir::Value::getType(), sysy::ir::Constant::getZero(), irEmit(), sysy::ir::BasicBlockTarget::setCond(), sysy::ir::IRBuilder::SetInsertPoint(), sysy::ir::BasicBlockTarget::setLoop(), sysy::ir::BasicBlock::setParent(), and sysy::ast::WhileStmtNode::stmt.
isAliasByGVToArg()
bool sysy::ir::isAliasByGVToArg (GlobalValue * gv, AllocaInst * arg)
References sysy::ir::AllocaInstruction::getAllocatedType(), sysy::ir::Type::getInnerType(), sysy::ir::GlobalValue::getValueType(), and sysy::type.
Referenced by alias().
isArgArray()
bool sysy::ir::isArgArray (Value * val)
References sysy::ir::AllocaInstruction::getAllocatedType().
Referenced by alias(), isLocal(), and sysy::ir::IPAnalysis::run().
isGlobal()
bool sysy::ir::isGlobal (Value * val)
Referenced by alias(), and isLocal().
isLocal()
bool sysy::ir::isLocal (Value * val)
References isArgArray(), and isGlobal().
Referenced by alias().
isSameType()
bool sysy::ir::isSameType (ir::Type * type1, ir::Type * type2)
References sysy::ir::Type::isFloatTy(), and sysy::ir::Type::isIntegerTy().
Referenced by createGlobalInit(), emitInitial(), and irEmit().
lcaCompute()
BasicBlock * sysy::ir::lcaCompute (BasicBlock * bb1, BasicBlock * bb2)
References sysy::ir::BasicBlock::getDomLevel(), and sysy::ir::BasicBlock::getIdom().
Referenced by replace(), and sysy::ir::GCM::schduleLate().
less() [1/2]
bool sysy::ir::less (LoadInst * load, StoreInst * store)
References sysy::ir::Instruction::getBasicBlock(), and sysy::ir::BasicBlock::getRank().
Referenced by sysy::ir::Memory2Reg::analysisAlloca(), sysy::ir::MemorySSA::analysisArray(), and sysy::ir::MemorySSA::analysisScalarGV().
less() [2/2]
bool sysy::ir::less (StoreInst * store, LoadInst * load)
References sysy::ir::Instruction::getBasicBlock(), and sysy::ir::BasicBlock::getRank().
llFileGen()
void sysy::ir::llFileGen (Module * mod)
References sysy::ir::Module::__function, sysy::ir::Module::__globalValue, and G.
nameIs()
static std::string sysy::ir::nameIs (Value * val) static
References G, and getVariable().
Referenced by sysy::ir::BinaryInstrcution::getSignature(), sysy::ir::UnaryInstruction::getSignature(), sysy::ir::SCEV::getSignature(), sysy::ir::CallInstruction::getSignature(), sysy::ir::BrInstruction::getSignature(), sysy::ir::RetInstruction::getSignature(), sysy::ir::StoreInstruction::getSignature(), sysy::ir::LoadInstruction::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), sysy::ir::MemPhiInstruction::getSignature(), and sysy::ir::MoveInstruction::getSignature().
operator*()
SCEV sysy::ir::operator* (Value * lhs, const SCEV & rhs)
References sysy::ir::ConstantInt::get(), sysy::ir::Value::getType(), sysy::ir::SCEV::instructionsHasBeenCaculated, and sysy::ir::SCEV::scevBody.
operator+() [1/2]
SCEV sysy::ir::operator+ (const SCEV & lhs, const SCEV & rhs)
References sysy::ir::SCEV::at(), sysy::ir::ConstantInt::get(), sysy::ir::Value::getType(), sysy::ir::SCEV::instructionsHasBeenCaculated, and sysy::ir::SCEV::size().
operator+() [2/2]
SCEV sysy::ir::operator+ (Value * lhs, const SCEV & rhs)
References sysy::ir::SCEV::at(), sysy::ir::Value::getType(), sysy::ir::SCEV::instructionsHasBeenCaculated, and sysy::ir::SCEV::size().
operator-() [1/2]
SCEV sysy::ir::operator- (const SCEV & lhs, const SCEV & rhs)
References sysy::ir::SCEV::at(), sysy::ir::ConstantInt::get(), sysy::ir::Value::getType(), sysy::ir::SCEV::instructionsHasBeenCaculated, and sysy::ir::SCEV::size().
operator-() [2/2]
SCEV sysy::ir::operator- (const SCEV & lhs, Value * rhs)
References sysy::ir::SCEV::at(), sysy::ir::Value::getType(), sysy::ir::SCEV::instructionsHasBeenCaculated, and sysy::ir::SCEV::size().
privateInit()
Value* sysy::ir::privateInit (Constant * initial, Type * type, std::string name, bool is_constant)
References sysy::ir::GlobalValue::Create(), sysy::name, and sysy::type.
Referenced by irEmit().
replace()
static void sysy::ir::replace (Instruction * instr, Value * value) static
References fixed, sysy::ir::Instruction::getBasicBlock(), InstrToRemove, lcaCompute(), sysy::ir::Value::replaceAllUseWith(), sysy::ir::User::UnUseAll(), and ValueNumber.
Referenced by sysy::ir::GVN::doPerInstr().
simplifyInstruction() [1/4]
Value * sysy::ir::simplifyInstruction (BinaryInst * bin)
References sysy::ir::User::addOperand(), constantFold(), sysy::ir::ConstantInt::get(), sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), sysy::ir::Instruction::isCmp(), sysy::ir::ConstantInt::isOne(), sysy::ir::ConstantInt::isZero(), and sysy::ir::User::UnUseAll().
simplifyInstruction() [2/4]
Value * sysy::ir::simplifyInstruction (Instruction * instr)
Referenced by sysy::ir::GVN::doPerInstr(), and sysy::ir::InstructionCombine::run().
simplifyInstruction() [3/4]
Value * sysy::ir::simplifyInstruction (PhiInst * phi)
References sysy::ir::PhiInstruction::getPredecessors().
simplifyInstruction() [4/4]
Value * sysy::ir::simplifyInstruction (UnaryInst * unary)
References constantFold(), sysy::ir::Instruction::FSub, sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::Type::getFloatTy(), sysy::ir::Type::getInt32Ty(), sysy::ir::Instruction::getKind(), sysy::ir::UnaryInstruction::getValue(), and sysy::ir::Instruction::Sub.
to_hex()
std::string sysy::ir::to_hex (float f)
Variable Documentation
AliveBB
std::unordered_set<BasicBlock*> sysy::ir::AliveBB static
Referenced by sysy::ir::ADCE::findAliveCode().
AliveCode [1/2]
std::unordered_set<Instruction*> sysy::ir::AliveCode static
AliveCode [2/2]
std::unordered_set<Instruction*> sysy::ir::AliveCode static
Referenced by sysy::ir::ADCE::findAliveCode(), sysy::ir::DCE::findAliveCode(), sysy::ir::ADCE::run(), and sysy::ir::DCE::run().
allocaDefUse
std::unordered_map<StoreInst*, std::set<LoadInst*> > sysy::ir::allocaDefUse static
Referenced by sysy::ir::Memory2Reg::allocaSimplify(), sysy::ir::Memory2Reg::analysisAlloca(), sysy::ir::Memory2Reg::renameAllocaInBB(), and sysy::ir::Memory2Reg::run().
allocaToRemove
std::vector<AllocaInst*> sysy::ir::allocaToRemove static
Referenced by sysy::ir::Memory2Reg::allocaSimplify(), and sysy::ir::Memory2Reg::run().
allocaUseDef
std::unordered_map<LoadInst*, StoreInst*> sysy::ir::allocaUseDef static
Referenced by sysy::ir::Memory2Reg::allocaSimplify(), sysy::ir::Memory2Reg::analysisAlloca(), sysy::ir::Memory2Reg::computeLiveIn(), sysy::ir::Memory2Reg::renameAllocaInBB(), and sysy::ir::Memory2Reg::run().
ancenstor [1/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::ancenstor static
ancenstor [2/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::ancenstor static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::compress(), sysy::ir::IdomGen::compress(), sysy::ir::IpdomGen::eval(), sysy::ir::IdomGen::eval(), sysy::ir::IpdomGen::link(), and sysy::ir::IdomGen::link().
argType
std::vector<Type*> sysy::ir::argType
Referenced by irEmit().
arrayDefUse
std::unordered_map<Instruction*, LoadInst*> sysy::ir::arrayDefUse static
Referenced by sysy::ir::MemorySSA::analysisArray(), sysy::ir::MemorySSA::renameStoreOfArrayInBB(), and sysy::ir::MemorySSA::run().
arrayUseDef
std::unordered_map<LoadInst*, Instruction*> sysy::ir::arrayUseDef static
Referenced by sysy::ir::MemorySSA::analysisArray(), sysy::ir::MemorySSA::renameLoadOfArrayInBB(), and sysy::ir::MemorySSA::run().
best [1/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::best static
best [2/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::best static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::compress(), sysy::ir::IdomGen::compress(), sysy::ir::IpdomGen::eval(), sysy::ir::IdomGen::eval(), sysy::ir::IpdomGen::link(), sysy::ir::IdomGen::link(), sysy::ir::IpdomGen::run(), sysy::ir::IdomGen::run(), and sysy::ir::GCM::schduleLate().
binaryOps
std::string sysy::ir::binaryOps[] static
Initial value:
= { "add", "sub", "mul", "sdiv", "srem", "icmp eq",
                            "icmp ne", "icmp slt", "icmp sgt", "icmp sle", "icmp sge",
                            "ashr", "lshr", "shl", "fadd", "fsub", "fmul", "fdiv",
                            "frem", "fcmp ueq", "fcmp une", "fcmp ult", "fcmp ugt",
                            "fcmp ule", "fcmp uge"}
Referenced by sysy::ir::BinaryInstrcution::getSignature().
bucket [1/2]
std::map<BasicBlock*, BBset> sysy::ir::bucket static
bucket [2/2]
std::map<BasicBlock*, BBset> sysy::ir::bucket static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::run(), and sysy::ir::IdomGen::run().
Builder
IRBuilder sysy::ir::Builder static
Referenced by createGlobalInit(), emitInitial(), getElementPtr(), getPtrPtr(), globalInit(), and irEmit().
canBeAvail
std::unordered_set<PhiOccurrence*> sysy::ir::canBeAvail static
Referenced by sysy::ir::PRE::computeCanBeAvail(), sysy::ir::PRE::computeLater(), and sysy::ir::PRE::resetCanBeAvail().
canBeSchduled
auto sysy::ir::canBeSchduled
Initial value:
= [](Instruction* instr) -> bool {
    if(auto binary = dynamic_cast<BinaryInst*>(instr))
        return true;
    else if(auto load = dynamic_cast<LoadInst*>(instr))
        return true;
    else if(auto gep = dynamic_cast<GEPInst*>(instr))
        return true;
    else if(auto unary = dynamic_cast<UnaryInst*>(instr))
        return true;
    else if(auto call = dynamic_cast<CallInst*>(instr); call
                && call->isPureCall())
        return true;
    return false;
    }
Referenced by sysy::ir::GCM::schduleEarly(), and sysy::ir::GCM::schduleLate().
child [1/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::child static
child [2/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::child static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::ValueScope::createChild(), sysy::AstScope::createChild(), sysy::ir::IpdomGen::link(), sysy::ir::IdomGen::link(), and sysy::SysYVisitor::printCst().
cnt
static int sysy::ir::cnt = 0
Referenced by sysy::ir::IRBuilder::CreateInBoundsGEP(), emitInitial(), sysy::ir::PhiOccurrence::getSignature(), sysy::ir::PRE::insertPhiInstruction(), and sysy::ir::SimplifyCFG::uncondTheCondBr().
collectOccurrencesList
std::vector<CollectOccurrences> sysy::ir::collectOccurrencesList static
Referenced by sysy::ir::PRE::buildCollectOccurrences(), sysy::ir::PRE::insertPhiInstruction(), sysy::ir::PRE::renaming(), and sysy::ir::PRE::run().
crossReal
std::unordered_map<PhiOccurrence*, BasicBlock*> sysy::ir::crossReal static
Referenced by sysy::ir::PRE::rename1().
dfnumVertex [1/2]
std::vector<BasicBlock*> sysy::ir::dfnumVertex static
dfnumVertex [2/2]
std::vector<BasicBlock*> sysy::ir::dfnumVertex static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::getDfnum(), sysy::ir::IdomGen::getDfnum(), sysy::ir::IpdomGen::run(), and sysy::ir::IdomGen::run().
doms
std::set<BasicBlock*> sysy::ir::doms static
Referenced by sysy::ir::DomTreeGen::computeAllDom(), and sysy::ir::DomTreeGen::run().
downSafe
std::unordered_set<PhiOccurrence*> sysy::ir::downSafe static
Referenced by sysy::ir::PRE::computeCanBeAvail(), sysy::ir::PRE::downSafety(), sysy::ir::PRE::insertPhiInstruction(), sysy::ir::PRE::rename1(), sysy::ir::PRE::resetCanBeAvail(), and sysy::ir::PRE::resetDownSafe().
fixed
bool sysy::ir::fixed static
Referenced by sysy::ir::IPDCE::eraseAllUnuseReturn(), replace(), sysy::ir::IPAnalysis::run(), sysy::ir::SimplifyCFG::run(), and sysy::ir::GVN::run().
funcInclude
struct { ... } sysy::ir::funcInclude[FUNC_NUM]
Initial value:
= {
    { Type::getInt32Ty(), {}, "getint", false },
    { Type::getInt32Ty(), {}, "getch", false },
    { Type::getFloatTy(), {}, "getfloat", false },
    { Type::getInt32Ty(), { Type::getInt32PtrTy() }, "getarray", false },
    { Type::getInt32Ty(), { Type::getFloatPtrTy() }, "getfarray", false },
    { Type::getVoidTy(), { Type::getInt32Ty() }, "putint", false },
    { Type::getVoidTy(), { Type::getInt32Ty() }, "putch", false },
    { Type::getVoidTy(), { Type::getFloatTy() }, "putfloat", false },
    { Type::getVoidTy(), { Type::getInt32Ty(), Type::getInt32PtrTy() }, "putarray", false },
    { Type::getVoidTy(), { Type::getInt32Ty(), Type::getFloatPtrTy() }, "putfarray", false },
    { Type::getVoidTy(), { Type::getInt8PtrTy()}, "putf", true },
    { Type::getVoidTy(), {}, "starttime", false },
    { Type::getVoidTy(), {}, "stoptime", false },
    { Type::getVoidTy(), { Type::getInt8PtrTy(), Type::getInt8PtrTy(), Type::getInt32Ty(), Type::getInt1Ty()}, "llvm.memcpy.inline.p0.p0.i32", false},
    { Type::getVoidTy(), { Type::getInt32PtrTy(), Type::getInt32Ty(), Type::getInt32Ty()}, "memset", false},
    { Type::getVoidTy(), { Type::getInt32PtrTy(), Type::getInt32PtrTy(), Type::getInt32Ty()}, "memcpy", false },
    { Type::getInt32Ty(), {}, "__thread_create", false },
    { Type::getVoidTy(), { Type::getInt32Ty() }, "__thread_join", false }
}
Referenced by initRuntime().
funcName
std::string sysy::ir::funcName
globalValueDefUse
std::unordered_map<Instruction*, LoadInst*> sysy::ir::globalValueDefUse static
Referenced by sysy::ir::MemorySSA::analysisScalarGV(), sysy::ir::MemorySSA::renameStoreOfGVInBB(), and sysy::ir::MemorySSA::run().
globalValueInfo
std::unordered_map<GlobalValue*, GVInfo> sysy::ir::globalValueInfo static
Referenced by sysy::ir::MemorySSA::analysisScalarGV(), sysy::ir::MemorySSA::computeScalarGVInfo(), sysy::ir::MemorySSA::DefUseCompute(), sysy::ir::MemorySSA::queueLoadMemPhi(), sysy::ir::MemorySSA::queueStoreMemPhi(), sysy::ir::MemorySSA::renameLoadOfGVInBB(), sysy::ir::MemorySSA::renameStoreOfGVInBB(), sysy::ir::MemorySSA::run(), and sysy::ir::MemorySSA::UseDefCompute().
globalValueUseDef
std::unordered_map<LoadInst*, Instruction*> sysy::ir::globalValueUseDef static
Referenced by sysy::ir::MemorySSA::analysisScalarGV(), sysy::ir::MemorySSA::renameLoadOfGVInBB(), and sysy::ir::MemorySSA::run().
hasRealUse
std::unordered_map<PhiOccurrence*, std::unordered_set<int> > sysy::ir::hasRealUse static
Referenced by sysy::ir::PRE::computeLater(), sysy::ir::PRE::rename1(), sysy::ir::PRE::resetCanBeAvail(), and sysy::ir::PRE::resetDownSafe().
IncomingGVLoadInBB
std::unordered_map<BasicBlock*, std::unordered_map<GlobalValue*, Value*> > sysy::ir::IncomingGVLoadInBB
Referenced by sysy::ir::MemorySSA::renameStoreOfGVInBB(), and sysy::ir::MemorySSA::UseDefCompute().
IncomingGVStoreInBB
std::unordered_map<BasicBlock*, std::unordered_map<GlobalValue*, Value*> > sysy::ir::IncomingGVStoreInBB
Referenced by sysy::ir::MemorySSA::DefUseCompute(), and sysy::ir::MemorySSA::renameLoadOfGVInBB().
IncomingLoadInBB
std::unordered_map<BasicBlock*, std::unordered_map<Value*, Value*> > sysy::ir::IncomingLoadInBB
Referenced by sysy::ir::MemorySSA::renameStoreOfArrayInBB(), and sysy::ir::MemorySSA::UseDefCompute().
IncomingStoreInBB
std::unordered_map<BasicBlock*, std::unordered_map<Value*, Value*> > sysy::ir::IncomingStoreInBB
Referenced by sysy::ir::MemorySSA::DefUseCompute(), and sysy::ir::MemorySSA::renameLoadOfArrayInBB().
IncomingValsInBB
std::unordered_map<BasicBlock*, std::unordered_map<AllocaInst*, Value*> > sysy::ir::IncomingValsInBB
Referenced by sysy::ir::Memory2Reg::renameAllocaInBB(), and sysy::ir::Memory2Reg::run().
info [1/2]
std::unordered_map<AllocaInst*, AllocaInfo> sysy::ir::info static
Referenced by sysy::ir::Memory2Reg::allocaSimplify(), sysy::ir::Memory2Reg::analysisAlloca(), sysy::ir::MemorySSA::analysisArray(), sysy::ir::MemorySSA::computeArrayInfo(), sysy::ir::Memory2Reg::computeLiveIn(), sysy::ir::MemorySSA::DefUseCompute(), sysy::ir::MemorySSA::queueLoadMemPhi(), sysy::ir::Memory2Reg::queuePhi(), sysy::ir::MemorySSA::queueStoreMemPhi(), sysy::ir::Memory2Reg::renameAllocaInBB(), sysy::ir::MemorySSA::renameLoadOfArrayInBB(), sysy::ir::MemorySSA::renameStoreOfArrayInBB(), sysy::ir::Memory2Reg::run(), sysy::ir::MemorySSA::run(), and sysy::ir::MemorySSA::UseDefCompute().
info [2/2]
std::unordered_map<Value*, ArrayInfo> sysy::ir::info static
InitFuncList
std::vector<Function*> sysy::ir::InitFuncList static
Referenced by createGlobal(), createGlobalInit(), and globalInit().
instrSchduled
std::unordered_set<Instruction*> sysy::ir::instrSchduled static
Referenced by sysy::ir::GCM::run(), sysy::ir::GCM::schduleEarly(), and sysy::ir::GCM::schduleLate().
InstrToRemove
std::vector<Instruction*> sysy::ir::InstrToRemove static
Referenced by replace(), and sysy::ir::GVN::run().
isVarArg
bool sysy::ir::isVarArg
Referenced by sysy::ir::Type::getFunctionTy().
labelCounter
std::multiset<std::string> sysy::ir::labelCounter static
Referenced by checkLabel().
labelName
std::map<BasicBlock*, std::string> sysy::ir::labelName static
Referenced by checkLabel(), and getLabel().
later
std::unordered_set<PhiOccurrence*> sysy::ir::later static
Referenced by sysy::ir::PRE::computeLater(), and sysy::ir::PRE::resetLater().
LoadCoverLoad
std::unordered_map<LoadInst*, LoadInst*> sysy::ir::LoadCoverLoad
Referenced by sysy::ir::MemorySSA::DefUseCompute(), and sysy::ir::MemorySSA::renameStoreOfArrayInBB().
maxTripCount
constexpr int sysy::ir::maxTripCount = 80 constexpr
Referenced by sysy::ir::LoopUnrollAll::runOnLoop().
parent [1/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::parent static
parent [2/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::parent static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::LoopInfo::discoverAndMapSubloop(), sysy::ir::IpdomGen::run(), and sysy::ir::IdomGen::run().
pdoms
std::set<BasicBlock*> sysy::ir::pdoms static
Referenced by sysy::ir::PostDomTreeGen::computeAllPostDom(), and sysy::ir::PostDomTreeGen::run().
phiCheck
std::unordered_map<PhiInst*, AllocaInst*> sysy::ir::phiCheck static
Referenced by sysy::ir::Memory2Reg::queuePhi(), and sysy::ir::Memory2Reg::run().
rank [1/2]
std::unordered_map<BasicBlock*, int> sysy::ir::rank static
rank [2/2]
std::unordered_map<BasicBlock*, int> sysy::ir::rank static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::link(), sysy::ir::IdomGen::link(), sysy::ir::IpdomGen::run(), and sysy::ir::IdomGen::run().
retType
Type* sysy::ir::retType
runtime
const std::string sysy::ir::runtime = "runtime/sylib.ll"
samedom [1/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::samedom static
samedom [2/2]
std::unordered_map<BasicBlock*, BasicBlock*> sysy::ir::samedom static
Referenced by clearIdomAll(), and clearIpdomAll().
semi [1/2]
std::unordered_map<BasicBlock*, int> sysy::ir::semi static
semi [2/2]
std::unordered_map<BasicBlock*, int> sysy::ir::semi static
Referenced by clearIdomAll(), clearIpdomAll(), sysy::ir::IpdomGen::compress(), sysy::ir::IdomGen::compress(), sysy::ir::IpdomGen::eval(), sysy::ir::IdomGen::eval(), sysy::ir::IpdomGen::link(), sysy::ir::IdomGen::link(), sysy::ir::IpdomGen::run(), and sysy::ir::IdomGen::run().
UnaryOps
std::string sysy::ir::UnaryOps[] = { "neg", "not", "fneg", "fptosi", "sitofp", "bitcast" } static
Referenced by sysy::ir::UnaryInstruction::getSignature().
ValueNumber
std::unordered_map<Value*, Value*> sysy::ir::ValueNumber static
Referenced by sysy::ir::GVN::checkoutTable(), sysy::ir::GVN::doPerInstr(), sysy::ir::GVN::getValueNumber(), replace(), and sysy::ir::GVN::run().
varCnt
int sysy::ir::varCnt static
Referenced by sysy::ir::PRE::rename1(), and sysy::ir::PRE::renaming().
variableCounter
std::multiset<std::string> sysy::ir::variableCounter static
Referenced by checkVariable().
variableName
std::map<Instruction*, std::string> sysy::ir::variableName static
Referenced by checkVariable(), and getVariable().