Diana: sysy::ir::PhiInstruction Class Reference
sysy::ir::PhiInstruction Class Reference
#include <Instructions.h>
Classes
class PhiIterator
Public Types
using indexRange = iterator_range< PhiIterator >
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Public Member Functions
PhiInstruction (Type *_type, BasicBlock *_father, std::string name="")
PhiInstruction (Type *_type, std::vector< ValueBlockPair > _predecessors, BasicBlock *_father)
size_t size ()
void setInComingValue (Value *val, BasicBlock *bb)
void setIncomingBB (unsigned index, BasicBlock *bb)
void removeIncomingByBB (BasicBlock *bb)
indexRange getPredecessors ()
ValueBlockPair getPredecessors (unsigned i)
std::string getSignature () override
Public Member Functions inherited from sysy::ir::MemoryInstruction
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Private Types
using ValueBlockPair = std::pair< Value *, BasicBlock * >
Additional Inherited Members
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
indexRange
using sysy::ir::PhiInstruction::indexRange = iterator_range<PhiIterator>
ValueBlockPair
using sysy::ir::PhiInstruction::ValueBlockPair = std::pair<Value*, BasicBlock*> private
Constructor & Destructor Documentation
PhiInstruction() [1/2]
sysy::ir::PhiInstruction::PhiInstruction (Type * _type, BasicBlock * _father, std::string name = "")
PhiInstruction() [2/2]
sysy::ir::PhiInstruction::PhiInstruction (Type * _type, std::vector< ValueBlockPair > _predecessors, BasicBlock * _father)
References sysy::ir::User::addOperand().
Member Function Documentation
getPredecessors() [1/2]
PhiInstruction::indexRange sysy::ir::PhiInstruction::getPredecessors ()
References sysy::make_range(), and sysy::ir::User::operands.
Referenced by sysy::ir::ScalarEvolution::BIV2SCEV(), getSignature(), sysy::ir::GVN::getValueNumber(), removeIncomingByBB(), and sysy::ir::simplifyInstruction().
getPredecessors() [2/2]
PhiInstruction::ValueBlockPair sysy::ir::PhiInstruction::getPredecessors (unsigned i)
References sysy::ir::User::getOprands().
getSignature()
std::string sysy::ir::PhiInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References sysy::iterator_range< IteratorT >::begin(), sysy::iterator_range< IteratorT >::end(), sysy::ir::getLabel(), getPredecessors(), sysy::ir::Type::getSignature(), sysy::ir::Value::getType(), sysy::ir::getVariable(), and sysy::ir::nameIs().
removeIncomingByBB()
void sysy::ir::PhiInstruction::removeIncomingByBB (BasicBlock * bb)
References getPredecessors(), sysy::ir::User::operands, and size().
Referenced by sysy::ir::LoopParallel::runOnLoop().
setIncomingBB()
void sysy::ir::PhiInstruction::setIncomingBB (unsigned index, BasicBlock * bb)
References sysy::ir::User::replaceOperandWith().
setInComingValue()
void sysy::ir::PhiInstruction::setInComingValue (Value * val, BasicBlock * bb)
References sysy::ir::User::addOperand().
size()
size_t sysy::ir::PhiInstruction::size () inline
References sysy::ir::User::getOprands().
Referenced by sysy::ir::GVN::getValueNumber(), and removeIncomingByBB().
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/Instructions.cpp
lib/IR/IRDump.cpp