Diana: sysy::ir::SCEV Class Reference
sysy::ir::SCEV Class Reference
#include <Loop.h>
Public Member Functions
SCEV ()
SCEV (Value *initial, Value *step)
SCEV (Value *initial, const SCEV &innerSCEV)
SCEV (const std::vector< Value * > &vec)
SCEV (Value *initial, Value *step, std::set< BinaryInst * > &&binarys)
Value *& at (unsigned i)
size_t size ()
Value * at (unsigned i) const
size_t size () const
void getItemChains (unsigned i, std::vector< BinaryInst * > &instrChain)
std::string getSignature ()
void clear ()
Private Attributes
std::vector< Value * > scevBody
std::set< BinaryInst * > instructionsHasBeenCaculated
Friends
SCEV operator+ (Value *lhs, const SCEV &rhs)
SCEV operator+ (const SCEV &lhs, const SCEV &rhs)
SCEV operator- (const SCEV &lhs, Value *rhs)
SCEV operator- (const SCEV &lhs, const SCEV &rhs)
SCEV operator* (Value *lhs, const SCEV &rhs)
Constructor & Destructor Documentation
SCEV() [1/5]
sysy::ir::SCEV::SCEV () inline
SCEV() [2/5]
sysy::ir::SCEV::SCEV (Value * initial, Value * step)
References scevBody.
SCEV() [3/5]
sysy::ir::SCEV::SCEV (Value * initial, const SCEV & innerSCEV)
References instructionsHasBeenCaculated, and scevBody.
SCEV() [4/5]
sysy::ir::SCEV::SCEV (const std::vector< Value * > & vec)
References scevBody.
SCEV() [5/5]
sysy::ir::SCEV::SCEV (Value * initial, Value * step, std::set< BinaryInst * > && binarys)
References scevBody.
Member Function Documentation
at() [1/2]
Value*& sysy::ir::SCEV::at (unsigned i) inline
References scevBody.
Referenced by sysy::ir::LSR::eraseSingleMul(), getSignature(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::operator+(), and sysy::ir::operator-().
at() [2/2]
Value* sysy::ir::SCEV::at (unsigned i) const inline
References scevBody.
clear()
void sysy::ir::SCEV::clear ()
References instructionsHasBeenCaculated, and scevBody.
getItemChains()
void sysy::ir::SCEV::getItemChains (unsigned i, std::vector< BinaryInst * > & instrChain)
References instructionsHasBeenCaculated, and scevBody.
getSignature()
std::string sysy::ir::SCEV::getSignature ()
References at(), instructionsHasBeenCaculated, sysy::ir::nameIs(), and size().
size() [1/2]
size_t sysy::ir::SCEV::size () inline
References scevBody.
Referenced by getSignature(), sysy::ir::operator+(), and sysy::ir::operator-().
size() [2/2]
size_t sysy::ir::SCEV::size () const inline
References scevBody.
Friends And Related Function Documentation
operator*
SCEV operator* (Value * lhs, const SCEV & rhs) friend
operator+ [1/2]
SCEV operator+ (const SCEV & lhs, const SCEV & rhs) friend
operator+ [2/2]
SCEV operator+ (Value * lhs, const SCEV & rhs) friend
operator- [1/2]
SCEV operator- (const SCEV & lhs, const SCEV & rhs) friend
operator- [2/2]
SCEV operator- (const SCEV & lhs, Value * rhs) friend
Member Data Documentation
instructionsHasBeenCaculated
std::set<BinaryInst*> sysy::ir::SCEV::instructionsHasBeenCaculated private
Referenced by clear(), getItemChains(), getSignature(), sysy::ir::operator*(), sysy::ir::operator+(), sysy::ir::operator-(), and SCEV().
scevBody
std::vector<Value*> sysy::ir::SCEV::scevBody private
Referenced by at(), clear(), getItemChains(), sysy::ir::operator*(), SCEV(), and size().
The documentation for this class was generated from the following files:
include/sysy/IR/Loop.h
lib/IR/IRDump.cpp
lib/IR/Loop.cpp