Diana: sysy::mc::GlobalObject Class Reference
sysy::mc::GlobalObject Class Reference
#include <GlobalObject.h>
Public Member Functions
GlobalObject (std::string _name)
GlobalObject (std::string _name, bool _is_float)
void pushValue (ir::Constant *gv)
Static Public Member Functions
static std::string dec2hex (int i)
static std::string getName ()
Public Attributes
std::string name
std::vector< int > values
std::string str_value
bool is_zero
bool is_string
bool is_float
int size = 0
Static Public Attributes
static int id = 0
Constructor & Destructor Documentation
GlobalObject() [1/2]
sysy::mc::GlobalObject::GlobalObject (std::string _name) inline
GlobalObject() [2/2]
sysy::mc::GlobalObject::GlobalObject (std::string _name, bool _is_float) inline
Member Function Documentation
dec2hex()
std::string sysy::mc::GlobalObject::dec2hex (int i) static
Referenced by sysy::mc::Module::gen_global().
getName()
std::string sysy::mc::GlobalObject::getName () static
References id.
Referenced by sysy::mc::Function::get_reg().
pushValue()
void sysy::mc::GlobalObject::pushValue (ir::Constant * gv)
References sysy::mc::Function::getFloatInt(), is_float, is_string, is_zero, pushValue(), size, str_value, and values.
Referenced by sysy::mc::Module::Module(), and pushValue().
Member Data Documentation
id
int sysy::mc::GlobalObject::id = 0 static
Referenced by getName().
is_float
bool sysy::mc::GlobalObject::is_float
Referenced by pushValue().
is_string
bool sysy::mc::GlobalObject::is_string
Referenced by pushValue().
is_zero
bool sysy::mc::GlobalObject::is_zero
Referenced by sysy::mc::Function::get_reg(), sysy::mc::Module::Module(), and pushValue().
name
std::string sysy::mc::GlobalObject::name
Referenced by sysy::mc::Function::get_reg().
size
int sysy::mc::GlobalObject::size = 0
Referenced by sysy::mc::Module::Module(), and pushValue().
str_value
std::string sysy::mc::GlobalObject::str_value
Referenced by pushValue().
values
std::vector<int> sysy::mc::GlobalObject::values
Referenced by sysy::mc::Function::get_reg(), and pushValue().
The documentation for this class was generated from the following files:
include/sysy/Target/GlobalObject.h
lib/Target/GlobalObject.cpp