Diana: sysy::ir::Instruction Class Reference
sysy::ir::Instruction Class Reference abstract
#include <Instruction.h>
Public Types
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Public Member Functions
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
virtual std::string getSignature ()=0
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static bool isReverse (Instruction *x, Instruction *y)
Private Attributes
InstrKind kind
BasicBlock * father
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Enumeration Documentation
InstrKind
enum sysy::ir::Instruction::InstrKind
Enumerator
Add
Sub
Mul
SDiv
SRem
ICmpEQ
ICmpNE
ICmpSLT
ICmpSGT
ICmpSLE
ICmpSGE
AShr
LShr
Shl
FAdd
FSub
FMul
FDiv
FRem
FCmpUEQ
FCmpUNE
FCmpULT
FCmpUGT
FCmpULE
FCmpUGE
Neg
Not
FNeg
FPToSI
SIToFP
BitCast
CondBr
Br
Call
Ret
Alloca
Load
Store
InboundGEP
Zext
Phi
MemPhi
LoadDep
MemCopy
InsertEle
ExtractEle
Move
Dead
Constructor & Destructor Documentation
Instruction() [1/2]
sysy::ir::Instruction::Instruction (Type * _type, InstrKind _kind, BasicBlock * _father, std::vector< Value * > _oprands, std::string _name = "") inline
Instruction() [2/2]
sysy::ir::Instruction::Instruction (Type * _type, InstrKind _kind, BasicBlock * _father, std::string _name = "") inline
Member Function Documentation
getBasicBlock() [1/2]
BasicBlock* sysy::ir::Instruction::getBasicBlock () inline
References father.
Referenced by sysy::ir::CollectOccurrences::addExpr(), sysy::ir::ADCE::findAliveCode(), sysy::ir::GVN::getValueNumber(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::LCSSA::insertLoopClosedPhi(), sysy::ir::irEmit(), sysy::ir::less(), sysy::ir::ArrayInfo::cmps::operator()(), sysy::ir::ArrayInfo::cmpl::operator()(), sysy::ir::cmps::operator()(), sysy::ir::cmpl::operator()(), sysy::ir::GVInfo::cmps::operator()(), sysy::ir::GVInfo::cmpl::operator()(), sysy::ir::ScalarEvolution::registerBIV(), sysy::ir::replace(), sysy::ir::GCM::schduleEarly(), sysy::ir::GCM::schduleLate(), sysy::ir::simplifyInstruction(), sysy::ir::InstructionCombine::visitAdd(), and sysy::ir::InstructionCombine::visitSub().
getBasicBlock() [2/2]
BasicBlock* sysy::ir::Instruction::getBasicBlock () const inline
References father.
getKind()
InstrKind sysy::ir::Instruction::getKind () inline
References kind.
Referenced by sysy::ir::constantFold(), sysy::ir::BinaryInstrcution::getSignature(), sysy::ir::UnaryInstruction::getSignature(), sysy::ir::GVN::getValueNumber(), sysy::ir::LSR::identifyAllInductiveMultiplication(), isReverse(), sysy::ir::CollectOccurrences::isSameExpr(), sysy::ir::ScalarEvolution::linkInstructionToSCEV(), sysy::ir::simplifyInstruction(), sysy::ir::InstructionCombine::visitAdd(), sysy::ir::InstructionCombine::visitBinary(), and sysy::ir::InstructionCombine::visitSub().
getRank()
int sysy::ir::Instruction::getRank ()
References father, and sysy::ir::BasicBlock::getRank().
Referenced by sysy::ir::MemorySSA::analysisArray(), sysy::ir::MemorySSA::analysisScalarGV(), sysy::ir::FunctionInline::inlineAtCall(), and sysy::ir::GCM::schduleLate().
getSignature()
virtual std::string sysy::ir::Instruction::getSignature () pure virtual
Implements sysy::ir::Value.
Implemented in sysy::ir::MoveInstruction, sysy::ir::DeadInstruction, sysy::ir::MemPhiInstruction, sysy::ir::PhiInstruction, sysy::ir::AllocaInstruction, sysy::ir::GEPInstruction, sysy::ir::LoadInstruction, sysy::ir::StoreInstruction, sysy::ir::RetInstruction, sysy::ir::BrInstruction, sysy::ir::CallInstruction, sysy::ir::UnaryInstruction, and sysy::ir::BinaryInstrcution.
Referenced by sysy::ir::RealOccurrence::getSignature().
isCmp()
bool sysy::ir::Instruction::isCmp () inline
References FCmpUEQ, FCmpUGE, ICmpEQ, ICmpSGE, kind, and Not.
Referenced by sysy::ir::simplifyInstruction().
isCommutative()
bool sysy::ir::Instruction::isCommutative () inline
References Add, FAdd, FCmpUEQ, FCmpUNE, FMul, ICmpEQ, ICmpNE, kind, and Mul.
Referenced by sysy::ir::GVN::getValueNumber(), sysy::ir::CollectOccurrences::isSameExpr(), and sysy::ir::PRE::rename1().
isInteger()
bool sysy::ir::Instruction::isInteger () inline
References Add, kind, Neg, Not, Shl, and SIToFP.
Referenced by sysy::ir::constantFold().
isReverse()
bool sysy::ir::Instruction::isReverse (Instruction * x, Instruction * y) static
References FCmpUGE, FCmpUGT, FCmpULE, FCmpULT, getKind(), ICmpSGE, ICmpSGT, ICmpSLE, and ICmpSLT.
Referenced by sysy::ir::GVN::getValueNumber().
isTerminator()
bool sysy::ir::Instruction::isTerminator () inline
References CondBr, kind, and Ret.
reSetBasicBlock()
void sysy::ir::Instruction::reSetBasicBlock (BasicBlock * bb) inline
References father.
Referenced by sysy::ir::BasicBlock::insertBeforeTerminal(), and sysy::ir::GCM::schduleLate().
Member Data Documentation
father
BasicBlock* sysy::ir::Instruction::father private
Referenced by getBasicBlock(), getRank(), and reSetBasicBlock().
kind
InstrKind sysy::ir::Instruction::kind private
Referenced by getKind(), isCmp(), isCommutative(), isInteger(), and isTerminator().
The documentation for this class was generated from the following files:
include/sysy/IR/Instruction.h
lib/IR/Instructions.cpp