Diana: include/sysy/Support/StrUtils.h File Reference
StrUtils.h File Reference
#include <iomanip>
#include <sstream>
#include <string>
#include <regex>
Functions
int strHex (std::string str)
int strOct (std::string str)
int strDec (std::string str)
float strFloat (std::string str)
float strFloatHex (std::string str)
std::string addIndent (const std::string &str)
std::string subLine (std::string str)
Detailed Description
This file contains the declaration of the Instruction class, which is the base class for all of the VM instructions.
Function Documentation
addIndent()
std::string addIndent (const std::string & str)
Referenced by subLine().
strDec()
int strDec (std::string str)
Referenced by sysy::SysYVisitor::visitIntConst().
strFloat()
float strFloat (std::string str)
Referenced by sysy::SysYVisitor::visitFloatConst().
strFloatHex()
float strFloatHex (std::string str)
Referenced by sysy::SysYVisitor::visitFloatConst().
strHex()
int strHex (std::string str)
Referenced by sysy::SysYVisitor::visitIntConst().
strOct()
int strOct (std::string str)
Referenced by sysy::SysYVisitor::visitIntConst().
subLine()
std::string subLine (std::string str)
References addIndent().
Referenced by sysy::PassManager< Opt >::getPassChain(), sysy::ast::CompUnitNode::getSignature(), sysy::ast::FuncDefNode::getSignature(), sysy::ast::FuncParamListNode::getSignature(), sysy::ast::ConstDeclNode::getSignature(), sysy::ast::VarDeclNode::getSignature(), sysy::ast::ConstDefNode::getSignature(), sysy::ast::VarDefNode::getSignature(), sysy::ast::InitValNode::getSignature(), sysy::ast::AssignStmtNode::getSignature(), sysy::ast::ExprStmtNode::getSignature(), sysy::ast::IfStmtNode::getSignature(), sysy::ast::ForStmtNode::getSignature(), sysy::ast::WhileStmtNode::getSignature(), sysy::ast::ReturnStmtNode::getSignature(), sysy::ast::BlockNode::getSignature(), sysy::ast::UnaryExprNode::getSignature(), sysy::ast::BinaryExprNode::getSignature(), sysy::ast::FunctionCallExprNode::getSignature(), and sysy::ast::LvalNode::getSignature().