Diana: sysy::ir::ValueScope Class Reference
sysy::ir::ValueScope Class Reference
#include <ValueScope.h>
Public Member Functions
ValueScope (ValueScope *_father)
ValueScope ()
ValueScope * getFather () override
Value * getValue (std::string varName)
void insertAlloca (std::string name, Value *value)
ValueScope * createChild ()
Static Public Member Functions
static ValueScope * exitBlock (ValueScope *ptr)
static ValueScope *& getCurrentPtr ()
Protected Attributes
ValueScope * father
std::map< std::string, Value * > namedValues
Constructor & Destructor Documentation
ValueScope() [1/2]
sysy::ir::ValueScope::ValueScope (ValueScope * _father) inline
ValueScope() [2/2]
sysy::ir::ValueScope::ValueScope () inline
Referenced by createChild(), and getCurrentPtr().
Member Function Documentation
createChild()
ValueScope * sysy::ir::ValueScope::createChild ()
References sysy::ir::child, and ValueScope().
exitBlock()
ValueScope * sysy::ir::ValueScope::exitBlock (ValueScope * ptr) static
References father.
Referenced by sysy::ir::irEmit().
getCurrentPtr()
static ValueScope*& sysy::ir::ValueScope::getCurrentPtr () inline static
References ValueScope().
Referenced by sysy::ir::emitIR(), and sysy::ir::irEmit().
getFather()
ValueScope * sysy::ir::ValueScope::getFather () override virtual
Implements sysy::Scope.
References father.
getValue()
Value * sysy::ir::ValueScope::getValue (std::string varName)
References ErrorMsg, father, getValue(), and namedValues.
Referenced by getValue().
insertAlloca()
void sysy::ir::ValueScope::insertAlloca (std::string name, Value * value)
References ErrorMsg, sysy::name, and namedValues.
Member Data Documentation
father
ValueScope* sysy::ir::ValueScope::father protected
Referenced by exitBlock(), getFather(), and getValue().
namedValues
std::map<std::string, Value*> sysy::ir::ValueScope::namedValues protected
Referenced by getValue(), and insertAlloca().
The documentation for this class was generated from the following files:
include/sysy/IR/ValueScope.h
lib/IR/ValueScope.cpp