Diana: sysy::ir::IntegerType Class Reference
sysy::ir::IntegerType Class Reference
#include <Type.h>
Public Member Functions
IntegerType (unsigned _width)
Type * getInnerType () override
std::string getSignature () override
size_t getAllocatedSize () override
Public Member Functions inherited from sysy::ir::Type
bool isFloatTy ()
bool isVoidTy ()
bool isLabelTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned width)
bool isFunctionTy ()
bool isPointerTy ()
bool isVectorTy ()
bool isArrayTy ()
bool isUndefTy ()
Static Public Member Functions
static IntegerType * get (unsigned width)
static IntegerType * getInt1Ty ()
static IntegerType * getInt32Ty ()
static IntegerType * getInt8Ty ()
Static Public Member Functions inherited from sysy::ir::Type
static Type * getFloatTy ()
static Type * getVoidTy ()
static Type * getUndefTy ()
static Type * getFunctionTy (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static Type * getLabelTy ()
static Type * getIntegerTy (unsigned width)
static Type * getInt1Ty ()
static Type * getInt32Ty ()
static Type * getInt8Ty ()
static Type * getPointerTy (Type *inner)
static Type * getArrayTy (Type *inner, unsigned size)
static Type * getInt8PtrTy ()
static Type * getInt32PtrTy ()
static Type * getFloatPtrTy ()
Private Attributes
unsigned width
Additional Inherited Members
Public Types inherited from sysy::ir::Type
enum TypeID {
FloatTyID = 0, VoidTyID, LabelTyID, IntegerTyID,
FunctionTyID, PointerTyID, ArrayTyID, FixedVectorTyID,
ScalableVectorTyID, UndefTyID
}
Protected Member Functions inherited from sysy::ir::Type
Type (TypeID id)
TypeID getTypeId ()
unsigned getSize ()
Constructor & Destructor Documentation
IntegerType()
sysy::ir::IntegerType::IntegerType (unsigned _width) inline
Member Function Documentation
get()
IntegerType * sysy::ir::IntegerType::get (unsigned width) static
References ErrorMsg, getInt1Ty(), getInt32Ty(), getInt8Ty(), and width.
Referenced by sysy::ir::Type::getIntegerTy().
getAllocatedSize()
size_t sysy::ir::IntegerType::getAllocatedSize () inline override virtual
Implements sysy::ir::Type.
References width.
getInnerType()
Type* sysy::ir::IntegerType::getInnerType () inline override virtual
Implements sysy::ir::Type.
getInt1Ty()
IntegerType * sysy::ir::IntegerType::getInt1Ty () static
References sysy::ir::Context::getInstance().
Referenced by get(), and sysy::ir::Type::getInt1Ty().
getInt32Ty()
IntegerType * sysy::ir::IntegerType::getInt32Ty () static
References sysy::ir::Context::getInstance().
Referenced by get(), sysy::ir::Type::getInt32Ty(), and sysy::ir::irEmit().
getInt8Ty()
IntegerType * sysy::ir::IntegerType::getInt8Ty () static
References sysy::ir::Context::getInstance().
Referenced by get(), and sysy::ir::Type::getInt8Ty().
getSignature()
std::string sysy::ir::IntegerType::getSignature () inline override virtual
Implements sysy::ir::Type.
References width.
Member Data Documentation
width
unsigned sysy::ir::IntegerType::width private
Referenced by get(), getAllocatedSize(), and getSignature().
The documentation for this class was generated from the following files:
include/sysy/IR/Type.h
lib/IR/Type.cpp