Diana: sysy::ir::GlobalValue Class Reference
sysy::ir::GlobalValue Class Reference
#include <GlobalValue.h>
Public Member Functions
GlobalValue (Type *_type, bool _isConst, Constant *_initial=nullptr, std::string _name="")
Type * getValueType ()
bool isConstant ()
Constant * getInitial ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static GlobalValue * Create (Type *_type, bool _isConst, Constant *_initial=nullptr, std::string _name="")
Private Attributes
Constant * initial
bool isConst
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
GlobalValue()
sysy::ir::GlobalValue::GlobalValue (Type * _type, bool _isConst, Constant * _initial = nullptr, std::string _name = "") inline
Referenced by Create().
Member Function Documentation
Create()
GlobalValue * sysy::ir::GlobalValue::Create (Type * _type, bool _isConst, Constant * _initial = nullptr, std::string _name = "") static
References sysy::ir::Module::__globalValue, sysy::ir::Module::getInstance(), sysy::ir::Type::getPointerTy(), and GlobalValue().
Referenced by sysy::ir::createGlobal(), and sysy::ir::privateInit().
getInitial()
Constant* sysy::ir::GlobalValue::getInitial () inline
References initial.
getSignature()
std::string sysy::ir::GlobalValue::getSignature () override virtual
Implements sysy::ir::Value.
References sysy::ir::Value::getName(), sysy::ir::Value::getSignature(), sysy::ir::Type::getSignature(), getValueType(), and initial.
getValueType()
Type* sysy::ir::GlobalValue::getValueType () inline
References sysy::ir::Type::getInnerType(), and sysy::ir::Value::getType().
Referenced by sysy::ir::MemorySSA::computeArrayInfo(), sysy::ir::MemorySSA::computeScalarGVInfo(), getSignature(), sysy::ir::isAliasByGVToArg(), and sysy::ir::LoopParallel::isParallelizable().
isConstant()
bool sysy::ir::GlobalValue::isConstant () inline
References isConst.
Referenced by sysy::ir::GVN::doPerInstr().
Member Data Documentation
initial
Constant* sysy::ir::GlobalValue::initial private
Referenced by getInitial(), and getSignature().
isConst
bool sysy::ir::GlobalValue::isConst private
Referenced by isConstant().
The documentation for this class was generated from the following files:
include/sysy/IR/GlobalValue.h
lib/IR/GlobalValue.cpp
lib/IR/IRDump.cpp