Diana: sysy::ir::DomFrontierGen Class Reference
sysy::ir::DomFrontierGen Class Reference
#include <DomInfo.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void computeDF (BasicBlock *bb)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
computeDF()
void sysy::ir::DomFrontierGen::computeDF (BasicBlock * bb) private
References sysy::ir::BasicBlock::getDomFrontier(), sysy::ir::BasicBlock::getDomTree(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by run().
getName()
std::string sysy::ir::DomFrontierGen::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::DomFrontierGen::run (Function * func) override
References computeDF(), and sysy::ir::Function::getEntryBlock().
The documentation for this class was generated from the following files:
include/sysy/Analysis/DomInfo.h
lib/Analysis/DomInfo.cpp