Diana: sysy::PassManager< Opt > Class Template Reference
sysy::PassManager< Opt > Class Template Reference
#include <PassManager.h>
Public Member Functions
virtual ~PassManager ()
void addPass (Pass< Opt > *pass)
std::string getName ()
void run (Opt opt)
std::string getPassChain ()
void dumpPass ()
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Protected Attributes
std::vector< Pass< Opt > * > passes
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
~PassManager()
template<typename Opt > virtual sysy::PassManager< Opt >::~PassManager () inline virtual
Member Function Documentation
addPass()
template<typename Opt > void sysy::PassManager< Opt >::addPass (Pass< Opt > * pass) inline
References sysy::Pass< Opt >::finishByDfs(), sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::relatedDfs().
Referenced by sysy::ir::DomInfo::DomInfo(), sysy::ir::initialIRTransform(), and sysy::ir::PostDomInfo::PostDomInfo().
dumpPass()
template<typename Opt > void sysy::PassManager< Opt >::dumpPass () inline
References sysy::PassManager< Opt >::getPassChain().
getName()
template<typename Opt > std::string sysy::PassManager< Opt >::getName () inline virtual
Implements sysy::Pass< Opt >.
Referenced by sysy::PassManager< Opt >::getPassChain().
getPassChain()
template<typename Opt > std::string sysy::PassManager< Opt >::getPassChain () inline
References sysy::PassManager< Opt >::getName(), sysy::PassManager< Opt >::passes, and subLine().
Referenced by sysy::PassManager< Opt >::dumpPass().
run()
template<typename Opt > void sysy::PassManager< Opt >::run (Opt opt) inline virtual
Implements sysy::Pass< Opt >.
References sysy::PassManager< Opt >::passes.
Member Data Documentation
passes
template<typename Opt > std::vector<Pass<Opt>*> sysy::PassManager< Opt >::passes protected
Referenced by sysy::PassManager< Opt >::getPassChain(), and sysy::PassManager< Opt >::run().
The documentation for this class was generated from the following file:
include/sysy/IR/PassManager.h