Diana: SysYParser Class Reference
SysYParser Class Reference
#include <SysYParser.h>
Classes
class AddExpContext
class BlockContext
class BlockItemContext
class BTypeContext
class CompUnitContext
class CondContext
class ConstDeclContext
class ConstDefContext
class ConstExpContext
class ConstInitValContext
class DeclContext
class ElementContext
class EqExpContext
class ExpContext
class FloatConstContext
class FuncDefContext
class FuncFParamContext
class FuncFParamsContext
class FuncRParamsContext
class FuncTypeContext
struct Initializer
class InitValContext
class IntConstContext
class LAndExpContext
class LOrExpContext
class LValContext
class MulExpContext
class NumberContext
class PrimaryExpContext
class RelExpContext
class Stmt_inContext
class StmtContext
class UnaryExpContext
class UnaryOpContext
class VarDecl_inContext
class VarDeclContext
class VarDefContext
Public Types
enum {
INT = 1, FLOAT = 2, CONST = 3, VOID = 4,
STRING = 5, ESC = 6, IF = 7, ELSE = 8,
WHILE = 9, FOR = 10, BREAK = 11, CONTINUE = 12,
RETURN = 13, AGN = 14, ADD = 15, SUB = 16,
MUL = 17, DIV = 18, MOD = 19, EQL = 20,
NEQ = 21, LES = 22, GRT = 23, LEQ = 24,
GEQ = 25, NOT = 26, AND = 27, OR = 28,
Ident = 29, DEC = 30, OCT = 31, HEX = 32,
DECFLOAT = 33, HEXFLOAT = 34, COMMA = 35, SEMI = 36,
LBRA = 37, RBRA = 38, LSBRA = 39, RSBRA = 40,
LCBRA = 41, RCBRA = 42, WS = 43, SL_COMMENT = 44,
COMMENT = 45
}
enum {
RuleCompUnit = 0, RuleElement = 1, RuleDecl = 2, RuleConstDecl = 3,
RuleBType = 4, RuleConstDef = 5, RuleConstInitVal = 6, RuleVarDecl = 7,
RuleVarDecl_in = 8, RuleVarDef = 9, RuleInitVal = 10, RuleFuncDef = 11,
RuleFuncType = 12, RuleFuncFParams = 13, RuleFuncFParam = 14, RuleBlock = 15,
RuleBlockItem = 16, RuleStmt_in = 17, RuleStmt = 18, RuleExp = 19,
RuleCond = 20, RuleLVal = 21, RulePrimaryExp = 22, RuleNumber = 23,
RuleUnaryExp = 24, RuleUnaryOp = 25, RuleFuncRParams = 26, RuleMulExp = 27,
RuleAddExp = 28, RuleRelExp = 29, RuleEqExp = 30, RuleLAndExp = 31,
RuleLOrExp = 32, RuleConstExp = 33, RuleIntConst = 34, RuleFloatConst = 35
}
Public Member Functions
SysYParser (antlr4::TokenStream *input)
~SysYParser ()
virtual std::string getGrammarFileName () const override
virtual const antlr4::atn::ATN & getATN () const override
virtual const std::vector< std::string > & getTokenNames () const override
virtual const std::vector< std::string > & getRuleNames () const override
virtual antlr4::dfa::Vocabulary & getVocabulary () const override
CompUnitContext * compUnit ()
ElementContext * element ()
DeclContext * decl ()
ConstDeclContext * constDecl ()
BTypeContext * bType ()
ConstDefContext * constDef ()
ConstInitValContext * constInitVal ()
VarDeclContext * varDecl ()
VarDecl_inContext * varDecl_in ()
VarDefContext * varDef ()
InitValContext * initVal ()
FuncDefContext * funcDef ()
FuncTypeContext * funcType ()
FuncFParamsContext * funcFParams ()
FuncFParamContext * funcFParam ()
BlockContext * block ()
BlockItemContext * blockItem ()
Stmt_inContext * stmt_in ()
StmtContext * stmt ()
ExpContext * exp ()
CondContext * cond ()
LValContext * lVal ()
PrimaryExpContext * primaryExp ()
NumberContext * number ()
UnaryExpContext * unaryExp ()
UnaryOpContext * unaryOp ()
FuncRParamsContext * funcRParams ()
MulExpContext * mulExp ()
MulExpContext * mulExp (int precedence)
AddExpContext * addExp ()
AddExpContext * addExp (int precedence)
RelExpContext * relExp ()
RelExpContext * relExp (int precedence)
EqExpContext * eqExp ()
EqExpContext * eqExp (int precedence)
LAndExpContext * lAndExp ()
LAndExpContext * lAndExp (int precedence)
LOrExpContext * lOrExp ()
LOrExpContext * lOrExp (int precedence)
ConstExpContext * constExp ()
IntConstContext * intConst ()
FloatConstContext * floatConst ()
virtual bool sempred (antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override
bool mulExpSempred (MulExpContext *_localctx, size_t predicateIndex)
bool addExpSempred (AddExpContext *_localctx, size_t predicateIndex)
bool relExpSempred (RelExpContext *_localctx, size_t predicateIndex)
bool eqExpSempred (EqExpContext *_localctx, size_t predicateIndex)
bool lAndExpSempred (LAndExpContext *_localctx, size_t predicateIndex)
bool lOrExpSempred (LOrExpContext *_localctx, size_t predicateIndex)
Static Private Attributes
static std::vector< antlr4::dfa::DFA > _decisionToDFA
static antlr4::atn::PredictionContextCache _sharedContextCache
static std::vector< std::string > _ruleNames
static std::vector< std::string > _tokenNames
static std::vector< std::string > _literalNames
static std::vector< std::string > _symbolicNames
static antlr4::dfa::Vocabulary _vocabulary
static antlr4::atn::ATN _atn
static std::vector< uint16_t > _serializedATN
static Initializer _init
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
INT
FLOAT
CONST
VOID
STRING
ESC
IF
ELSE
WHILE
FOR
BREAK
CONTINUE
RETURN
AGN
ADD
SUB
MUL
DIV
MOD
EQL
NEQ
LES
GRT
LEQ
GEQ
NOT
AND
OR
Ident
DEC
OCT
HEX
DECFLOAT
HEXFLOAT
COMMA
SEMI
LBRA
RBRA
LSBRA
RSBRA
LCBRA
RCBRA
WS
SL_COMMENT
COMMENT
anonymous enum
anonymous enum
Enumerator
RuleCompUnit
RuleElement
RuleDecl
RuleConstDecl
RuleBType
RuleConstDef
RuleConstInitVal
RuleVarDecl
RuleVarDecl_in
RuleVarDef
RuleInitVal
RuleFuncDef
RuleFuncType
RuleFuncFParams
RuleFuncFParam
RuleBlock
RuleBlockItem
RuleStmt_in
RuleStmt
RuleExp
RuleCond
RuleLVal
RulePrimaryExp
RuleNumber
RuleUnaryExp
RuleUnaryOp
RuleFuncRParams
RuleMulExp
RuleAddExp
RuleRelExp
RuleEqExp
RuleLAndExp
RuleLOrExp
RuleConstExp
RuleIntConst
RuleFloatConst
Constructor & Destructor Documentation
SysYParser()
SysYParser::SysYParser (antlr4::TokenStream * input) explicit
References _atn, _decisionToDFA, and _sharedContextCache.
~SysYParser()
SysYParser::~SysYParser ()
Member Function Documentation
addExp() [1/2]
SysYParser::AddExpContext * SysYParser::addExp ()
Referenced by constExp(), exp(), and relExp().
addExp() [2/2]
SysYParser::AddExpContext * SysYParser::addExp (int precedence)
References ADD, mulExp(), RuleAddExp, and SUB.
addExpSempred()
bool SysYParser::addExpSempred (AddExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
block()
SysYParser::BlockContext * SysYParser::block ()
References ADD, blockItem(), BREAK, CONST, CONTINUE, DEC, DECFLOAT, FLOAT, FOR, HEX, HEXFLOAT, Ident, IF, INT, LBRA, LCBRA, NOT, OCT, RCBRA, RETURN, RuleBlock, SEMI, SUB, and WHILE.
Referenced by funcDef(), and stmt().
blockItem()
SysYParser::BlockItemContext * SysYParser::blockItem ()
References ADD, BREAK, CONST, CONTINUE, DEC, DECFLOAT, decl(), FLOAT, FOR, HEX, HEXFLOAT, Ident, IF, INT, LBRA, LCBRA, NOT, OCT, RETURN, RuleBlockItem, SEMI, stmt(), SUB, and WHILE.
Referenced by block().
bType()
SysYParser::BTypeContext * SysYParser::bType ()
References FLOAT, INT, and RuleBType.
Referenced by constDecl(), funcFParam(), varDecl(), and varDecl_in().
compUnit()
SysYParser::CompUnitContext * SysYParser::compUnit ()
References CONST, element(), FLOAT, INT, RuleCompUnit, and VOID.
Referenced by sysy::FrontendMain().
cond()
SysYParser::CondContext * SysYParser::cond ()
References lOrExp(), and RuleCond.
Referenced by stmt().
constDecl()
SysYParser::ConstDeclContext * SysYParser::constDecl ()
References bType(), COMMA, CONST, constDef(), RuleConstDecl, and SEMI.
Referenced by decl().
constDef()
SysYParser::ConstDefContext * SysYParser::constDef ()
References AGN, constExp(), constInitVal(), Ident, LSBRA, RSBRA, and RuleConstDef.
Referenced by constDecl().
constExp()
SysYParser::ConstExpContext * SysYParser::constExp ()
References addExp(), and RuleConstExp.
Referenced by constDef(), constInitVal(), and varDef().
constInitVal()
SysYParser::ConstInitValContext * SysYParser::constInitVal ()
References ADD, COMMA, constExp(), DEC, DECFLOAT, HEX, HEXFLOAT, Ident, LBRA, LCBRA, NOT, OCT, RCBRA, RuleConstInitVal, and SUB.
Referenced by constDef().
decl()
SysYParser::DeclContext * SysYParser::decl ()
References CONST, constDecl(), FLOAT, INT, RuleDecl, and varDecl().
Referenced by blockItem(), and element().
element()
SysYParser::ElementContext * SysYParser::element ()
References decl(), funcDef(), and RuleElement.
Referenced by compUnit().
eqExp() [1/2]
SysYParser::EqExpContext * SysYParser::eqExp ()
Referenced by lAndExp().
eqExp() [2/2]
SysYParser::EqExpContext * SysYParser::eqExp (int precedence)
References EQL, NEQ, relExp(), and RuleEqExp.
eqExpSempred()
bool SysYParser::eqExpSempred (EqExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
exp()
SysYParser::ExpContext * SysYParser::exp ()
References addExp(), and RuleExp.
Referenced by funcFParam(), funcRParams(), initVal(), lVal(), primaryExp(), stmt(), and stmt_in().
floatConst()
SysYParser::FloatConstContext * SysYParser::floatConst ()
References DECFLOAT, HEXFLOAT, and RuleFloatConst.
Referenced by number().
funcDef()
SysYParser::FuncDefContext * SysYParser::funcDef ()
References block(), FLOAT, funcFParams(), funcType(), Ident, INT, LBRA, RBRA, and RuleFuncDef.
Referenced by element().
funcFParam()
SysYParser::FuncFParamContext * SysYParser::funcFParam ()
References bType(), exp(), Ident, LSBRA, RSBRA, and RuleFuncFParam.
Referenced by funcFParams().
funcFParams()
SysYParser::FuncFParamsContext * SysYParser::funcFParams ()
References COMMA, funcFParam(), and RuleFuncFParams.
Referenced by funcDef().
funcRParams()
SysYParser::FuncRParamsContext * SysYParser::funcRParams ()
References ADD, COMMA, DEC, DECFLOAT, exp(), HEX, HEXFLOAT, Ident, LBRA, NOT, OCT, RuleFuncRParams, STRING, and SUB.
Referenced by unaryExp().
funcType()
SysYParser::FuncTypeContext * SysYParser::funcType ()
References FLOAT, INT, RuleFuncType, and VOID.
Referenced by funcDef().
getATN()
virtual const antlr4::atn::ATN& SysYParser::getATN () const inline override virtual
References _atn.
getGrammarFileName()
std::string SysYParser::getGrammarFileName () const override virtual
getRuleNames()
const std::vector< std::string > & SysYParser::getRuleNames () const override virtual
References _ruleNames.
getTokenNames()
virtual const std::vector<std::string>& SysYParser::getTokenNames () const inline override virtual
References _tokenNames.
getVocabulary()
dfa::Vocabulary & SysYParser::getVocabulary () const override virtual
References _vocabulary.
initVal()
SysYParser::InitValContext * SysYParser::initVal ()
References ADD, COMMA, DEC, DECFLOAT, exp(), HEX, HEXFLOAT, Ident, LBRA, LCBRA, NOT, OCT, RCBRA, RuleInitVal, and SUB.
Referenced by varDef().
intConst()
SysYParser::IntConstContext * SysYParser::intConst ()
References DEC, HEX, OCT, and RuleIntConst.
Referenced by number().
lAndExp() [1/2]
SysYParser::LAndExpContext * SysYParser::lAndExp ()
Referenced by lOrExp().
lAndExp() [2/2]
SysYParser::LAndExpContext * SysYParser::lAndExp (int precedence)
References AND, eqExp(), and RuleLAndExp.
lAndExpSempred()
bool SysYParser::lAndExpSempred (LAndExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
lOrExp() [1/2]
SysYParser::LOrExpContext * SysYParser::lOrExp ()
Referenced by cond().
lOrExp() [2/2]
SysYParser::LOrExpContext * SysYParser::lOrExp (int precedence)
References lAndExp(), OR, and RuleLOrExp.
lOrExpSempred()
bool SysYParser::lOrExpSempred (LOrExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
lVal()
SysYParser::LValContext * SysYParser::lVal ()
References exp(), Ident, LSBRA, RSBRA, and RuleLVal.
Referenced by primaryExp(), stmt(), and stmt_in().
mulExp() [1/2]
SysYParser::MulExpContext * SysYParser::mulExp ()
Referenced by addExp().
mulExp() [2/2]
SysYParser::MulExpContext * SysYParser::mulExp (int precedence)
References DIV, MOD, MUL, RuleMulExp, and unaryExp().
mulExpSempred()
bool SysYParser::mulExpSempred (MulExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
number()
SysYParser::NumberContext * SysYParser::number ()
References DEC, DECFLOAT, floatConst(), HEX, HEXFLOAT, intConst(), OCT, and RuleNumber.
Referenced by primaryExp().
primaryExp()
SysYParser::PrimaryExpContext * SysYParser::primaryExp ()
References DEC, DECFLOAT, exp(), HEX, HEXFLOAT, Ident, LBRA, lVal(), number(), OCT, RBRA, and RulePrimaryExp.
Referenced by unaryExp().
relExp() [1/2]
SysYParser::RelExpContext * SysYParser::relExp ()
Referenced by eqExp().
relExp() [2/2]
SysYParser::RelExpContext * SysYParser::relExp (int precedence)
References addExp(), GEQ, GRT, LEQ, LES, and RuleRelExp.
relExpSempred()
bool SysYParser::relExpSempred (RelExpContext * _localctx, size_t predicateIndex)
Referenced by sempred().
sempred()
bool SysYParser::sempred (antlr4::RuleContext * _localctx, size_t ruleIndex, size_t predicateIndex) override virtual
References addExpSempred(), eqExpSempred(), lAndExpSempred(), lOrExpSempred(), mulExpSempred(), and relExpSempred().
stmt()
SysYParser::StmtContext * SysYParser::stmt ()
References ADD, AGN, block(), BREAK, cond(), CONTINUE, DEC, DECFLOAT, ELSE, exp(), FLOAT, FOR, HEX, HEXFLOAT, Ident, IF, INT, LBRA, lVal(), NOT, OCT, RBRA, RETURN, RuleStmt, SEMI, stmt_in(), SUB, varDecl_in(), and WHILE.
Referenced by blockItem().
stmt_in()
SysYParser::Stmt_inContext * SysYParser::stmt_in ()
References ADD, AGN, DEC, DECFLOAT, exp(), HEX, HEXFLOAT, Ident, LBRA, lVal(), NOT, OCT, RuleStmt_in, and SUB.
Referenced by stmt().
unaryExp()
SysYParser::UnaryExpContext * SysYParser::unaryExp ()
References ADD, DEC, DECFLOAT, funcRParams(), HEX, HEXFLOAT, Ident, LBRA, NOT, OCT, primaryExp(), RBRA, RuleUnaryExp, STRING, SUB, and unaryOp().
Referenced by mulExp().
unaryOp()
SysYParser::UnaryOpContext * SysYParser::unaryOp ()
References ADD, NOT, RuleUnaryOp, and SUB.
Referenced by unaryExp().
varDecl()
SysYParser::VarDeclContext * SysYParser::varDecl ()
References bType(), COMMA, RuleVarDecl, SEMI, and varDef().
Referenced by decl().
varDecl_in()
SysYParser::VarDecl_inContext * SysYParser::varDecl_in ()
References bType(), COMMA, RuleVarDecl_in, and varDef().
Referenced by stmt().
varDef()
SysYParser::VarDefContext * SysYParser::varDef ()
References AGN, constExp(), Ident, initVal(), LSBRA, RSBRA, and RuleVarDef.
Referenced by varDecl(), and varDecl_in().
Member Data Documentation
_atn
atn::ATN SysYParser::_atn static private
Referenced by getATN(), SysYParser::Initializer::Initializer(), and SysYParser().
_decisionToDFA
std::vector< dfa::DFA > SysYParser::_decisionToDFA static private
Referenced by SysYParser::Initializer::Initializer(), and SysYParser().
_init
SysYParser::Initializer SysYParser::_init static private
_literalNames
std::vector< std::string > SysYParser::_literalNames static private
Initial value:
= {
  "", "'int'", "'float'", "'const'", "'void'", "", "", "'if'", "'else'",
  "'while'", "'for'", "'break'", "'continue'", "'return'", "'='", "'+'",
  "'-'", "'*'", "'/'", "'%'", "'=='", "'!='", "'<'", "'>'", "'<='", "'>='",
  "'!'", "'&&'", "'||'", "", "", "", "", "", "", "','", "';'", "'('", "')'",
  "'['", "']'", "'{'", "'}'"
}
_ruleNames
std::vector< std::string > SysYParser::_ruleNames static private
Initial value:
= {
  "compUnit", "element", "decl", "constDecl", "bType", "constDef", "constInitVal",
  "varDecl", "varDecl_in", "varDef", "initVal", "funcDef", "funcType", "funcFParams",
  "funcFParam", "block", "blockItem", "stmt_in", "stmt", "exp", "cond",
  "lVal", "primaryExp", "number", "unaryExp", "unaryOp", "funcRParams",
  "mulExp", "addExp", "relExp", "eqExp", "lAndExp", "lOrExp", "constExp",
  "intConst", "floatConst"
}
Referenced by getRuleNames().
_serializedATN
std::vector< uint16_t > SysYParser::_serializedATN static private
Referenced by SysYParser::Initializer::Initializer().
_sharedContextCache
atn::PredictionContextCache SysYParser::_sharedContextCache static private
Referenced by SysYParser().
_symbolicNames
std::vector< std::string > SysYParser::_symbolicNames static private
Initial value:
= {
  "", "INT", "FLOAT", "CONST", "VOID", "STRING", "ESC", "IF", "ELSE", "WHILE",
  "FOR", "BREAK", "CONTINUE", "RETURN", "AGN", "ADD", "SUB", "MUL", "DIV",
  "MOD", "EQL", "NEQ", "LES", "GRT", "LEQ", "GEQ", "NOT", "AND", "OR", "Ident",
  "DEC", "OCT", "HEX", "DECFLOAT", "HEXFLOAT", "COMMA", "SEMI", "LBRA",
  "RBRA", "LSBRA", "RSBRA", "LCBRA", "RCBRA", "WS", "SL_COMMENT", "COMMENT"
}
Referenced by SysYParser::Initializer::Initializer().
_tokenNames
std::vector< std::string > SysYParser::_tokenNames static private
Referenced by getTokenNames(), and SysYParser::Initializer::Initializer().
_vocabulary
dfa::Vocabulary SysYParser::_vocabulary static private
Referenced by getVocabulary(), and SysYParser::Initializer::Initializer().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp