Diana: sysy::ir::Context Class Reference
sysy::ir::Context Class Reference
#include <Context.h>
Public Member Functions
Context ()
Static Public Member Functions
static Context & getInstance ()
Public Attributes
FloatType FloatTy
IntegerType Int1Ty
IntegerType Int8Ty
IntegerType Int32Ty
LableType LabelTy
VoidType VoidTy
UndefType UndefTy
std::map< Type *, PointerType > PointerTy
std::map< std::pair< Type *, unsigned >, ArrayType > ArrayTy
std::set< FunctionType > FunctionTy
Constructor & Destructor Documentation
Context()
sysy::ir::Context::Context () inline
Member Function Documentation
getInstance()
static Context& sysy::ir::Context::getInstance () inline static
Referenced by sysy::ir::LableType::get(), sysy::ir::VoidType::get(), sysy::ir::UndefType::get(), sysy::ir::FloatType::get(), sysy::ir::PointerType::get(), sysy::ir::ArrayType::get(), sysy::ir::IntegerType::getInt1Ty(), sysy::ir::IntegerType::getInt32Ty(), and sysy::ir::IntegerType::getInt8Ty().
Member Data Documentation
ArrayTy
std::map<std::pair<Type*, unsigned>, ArrayType> sysy::ir::Context::ArrayTy
FloatTy
FloatType sysy::ir::Context::FloatTy
FunctionTy
std::set<FunctionType> sysy::ir::Context::FunctionTy
Int1Ty
IntegerType sysy::ir::Context::Int1Ty
Int32Ty
IntegerType sysy::ir::Context::Int32Ty
Int8Ty
IntegerType sysy::ir::Context::Int8Ty
LabelTy
LableType sysy::ir::Context::LabelTy
PointerTy
std::map<Type*, PointerType> sysy::ir::Context::PointerTy
UndefTy
UndefType sysy::ir::Context::UndefTy
VoidTy
VoidType sysy::ir::Context::VoidTy
The documentation for this class was generated from the following file:
include/sysy/IR/Context.h