Diana: sysy::ast::AstNode Class Reference
sysy::ast::AstNode Class Reference abstract
#include <Ast.h>
Public Types
enum AstKind {
AST_compUnit, AST_decl, AST_constDecl, AST_constDef,
AST_varDecl, AST_varDef, AST_prototype, AST_initVal,
AST_funcDef, AST_funcParams, AST_funcParam, AST_stmt,
AST_block, AST_assignStmt, AST_expStmt, AST_ifStmt,
AST_forStmt, AST_whileStmt, AST_breakStmt, AST_continueStmt,
AST_returnStmt, AST_exp, AST_cond, AST_mulExp,
AST_addExp, AST_relExp, AST_eqExp, AST_lAndExp,
AST_lOrExp, AST_unaryExp, AST_binaryExp, AST_functCallExp,
AST_primaryExp, AST_lVal, AST_ConditionNumber, AST_Number,
AST_EOF, AST_Undefined
}
Public Member Functions
AstNode (AstKind _kind)
virtual ~AstNode ()
void setParent (AstNode *_parent)
void addChildren (AstNode *_children)
std::vector< AstNode * > & getChildren ()
const AstNode * getParent () const
AstNode * getParent ()
const AstKind & getKind () const
FuncDefNode * getParentFuction () const
AAAA.
virtual std::string getSignature () const =0
Public Attributes
AstKind kind
AstNode * parent
std::vector< AstNode * > children
Member Enumeration Documentation
AstKind
enum sysy::ast::AstNode::AstKind
Enumerator
AST_compUnit
AST_decl
AST_constDecl
AST_constDef
AST_varDecl
AST_varDef
AST_prototype
AST_initVal
AST_funcDef
AST_funcParams
AST_funcParam
AST_stmt
AST_block
AST_assignStmt
AST_expStmt
AST_ifStmt
AST_forStmt
AST_whileStmt
AST_breakStmt
AST_continueStmt
AST_returnStmt
AST_exp
AST_cond
AST_mulExp
AST_addExp
AST_relExp
AST_eqExp
AST_lAndExp
AST_lOrExp
AST_unaryExp
AST_binaryExp
AST_functCallExp
AST_primaryExp
AST_lVal
AST_ConditionNumber
AST_Number
AST_EOF
AST_Undefined
Constructor & Destructor Documentation
AstNode()
sysy::ast::AstNode::AstNode (AstKind _kind) inline
~AstNode()
virtual sysy::ast::AstNode::~AstNode () inline virtual
Member Function Documentation
addChildren()
void sysy::ast::AstNode::addChildren (AstNode * _children) inline
References children.
getChildren()
std::vector<AstNode*>& sysy::ast::AstNode::getChildren () inline
References children.
getKind()
const AstKind& sysy::ast::AstNode::getKind () const inline
References kind.
Referenced by sysy::ast::CompUnitNode::classof(), sysy::ast::FuncDefNode::classof(), sysy::ast::FuncParamListNode::classof(), sysy::ast::FuncParamNode::classof(), sysy::ast::StmtNode::classof(), sysy::ast::DeclNode::classof(), sysy::ast::ConstDeclNode::classof(), sysy::ast::VarDeclNode::classof(), sysy::ast::ConstDefNode::classof(), sysy::ast::VarDefNode::classof(), sysy::ast::InitValNode::classof(), sysy::ast::AssignStmtNode::classof(), sysy::ast::ExprStmtNode::classof(), sysy::ast::IfStmtNode::classof(), sysy::ast::ForStmtNode::classof(), sysy::ast::WhileStmtNode::classof(), sysy::ast::BreakStmtNode::classof(), sysy::ast::ContinueStmtNode::classof(), sysy::ast::ReturnStmtNode::classof(), sysy::ast::BlockNode::classof(), sysy::ast::ExprNode::classof(), sysy::ast::UnaryExprNode::classof(), sysy::ast::BinaryExprNode::classof(), sysy::ast::FunctionCallExprNode::classof(), sysy::ast::LvalNode::classof(), and sysy::ast::NumberNode::classof().
getParent() [1/2]
AstNode* sysy::ast::AstNode::getParent () inline
References parent.
getParent() [2/2]
const AstNode* sysy::ast::AstNode::getParent () const inline
References parent.
getParentFuction()
FuncDefNode * sysy::ast::AstNode::getParentFuction () const
AAAA.
Returns
getSignature()
virtual std::string sysy::ast::AstNode::getSignature () const pure virtual
Implemented in sysy::ast::NumberNode, sysy::ast::LvalNode, sysy::ast::FunctionCallExprNode, sysy::ast::BinaryExprNode, sysy::ast::UnaryExprNode, sysy::ast::ExprNode, sysy::ast::BlockNode, sysy::ast::ReturnStmtNode, sysy::ast::ContinueStmtNode, sysy::ast::BreakStmtNode, sysy::ast::WhileStmtNode, sysy::ast::ForStmtNode, sysy::ast::IfStmtNode, sysy::ast::ExprStmtNode, sysy::ast::AssignStmtNode, sysy::ast::InitValNode, sysy::ast::VarDefNode, sysy::ast::ConstDefNode, sysy::ast::VarDeclNode, sysy::ast::ConstDeclNode, sysy::ast::DeclNode, sysy::ast::StmtNode, sysy::ast::FuncParamNode, sysy::ast::FuncParamListNode, sysy::ast::FuncDefNode, and sysy::ast::CompUnitNode.
Referenced by sysy::ast::dump().
setParent()
void sysy::ast::AstNode::setParent (AstNode * _parent) inline
References parent.
Member Data Documentation
children
std::vector<AstNode*> sysy::ast::AstNode::children
Referenced by addChildren(), and getChildren().
kind
AstKind sysy::ast::AstNode::kind
Referenced by getKind(), and sysy::ast::ExprNode::ready().
parent
AstNode* sysy::ast::AstNode::parent
Referenced by getParent(), and setParent().
The documentation for this class was generated from the following files:
include/sysy/Frontend/Ast.h
lib/Frontend/Ast.cpp