Diana: sysy::ir::Function Class Reference
sysy::ir::Function Class Reference
#include <Function.h>
Classes
class Arg
Public Member Functions
Function (FunctionType *_type, std::string _name)
Function (FunctionType *_type)
std::string getSignature () override
ArgVec & getArgs ()
Type * getReturnType ()
std::set< Function * > & getCaller ()
std::set< Function * > & getCallee ()
std::vector< CallInstruction * > & getCallSite ()
std::set< GlobalValue * > & getStoreGV ()
std::set< GlobalValue * > & getLoadGV ()
BasicBlock * getEntryBlock ()
BasicBlock * getExitBlock ()
void setExitBlock (BasicBlock *exit)
std::list< BasicBlock * > & getBasicBlockList ()
size_t arg_size ()
bool isDeclare ()
bool isParallelZeon ()
bool hasSideEffect ()
void noSideEffect ()
void clearLinkOfBBToLoop ()
void linkBBToLoop (BasicBlock *bb, Loop *loop)
Loop * getLoopOfBB (BasicBlock *bb)
std::vector< Loop * > & getTopLoops ()
std::vector< Loop * > & getAllLoops ()
void setRecursive ()
bool isRecursive ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static Function * Create (FunctionType *type, const std::string &name)
static Function * Create (FunctionType *type)
Private Types
using ArgVec = std::vector< std::unique_ptr< Arg > >
using FuncIter = std::list< Function * >::iterator
Private Attributes
bool innerFunction = false
bool sideEffect = true
bool recursive = false
ArgVec args
Type * retType
FuncIter funcIter
std::set< Function * > caller
std::set< Function * > callee
std::vector< CallInstruction * > callSite
std::set< GlobalValue * > storeGV
std::set< GlobalValue * > loadGV
std::list< BasicBlock * > basicBlock
std::unordered_map< BasicBlock *, Loop * > bbToLoop
std::vector< Loop * > topLoops
std::vector< Loop * > allLoops
BasicBlock * exitBlock = nullptr
Additional Inherited Members
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
ArgVec
using sysy::ir::Function::ArgVec = std::vector<std::unique_ptr<Arg> > private
FuncIter
using sysy::ir::Function::FuncIter = std::list<Function*>::iterator private
Constructor & Destructor Documentation
Function() [1/2]
sysy::ir::Function::Function (FunctionType * _type, std::string _name)
References args, funcIter, sysy::ir::FunctionType::getArg(), sysy::ir::Module::getInstance(), sysy::ir::Value::name, and sysy::ir::Value::type.
Referenced by Create().
Function() [2/2]
sysy::ir::Function::Function (FunctionType * _type)
References args, sysy::ir::FunctionType::getArg(), and sysy::ir::Value::type.
Member Function Documentation
arg_size()
size_t sysy::ir::Function::arg_size () inline
References args.
Referenced by sysy::ir::irEmit().
clearLinkOfBBToLoop()
void sysy::ir::Function::clearLinkOfBBToLoop () inline
References bbToLoop.
Referenced by sysy::ir::LoopInfo::run().
Create() [1/2]
static Function* sysy::ir::Function::Create (FunctionType * type) inline static
References Function(), and sysy::ir::Value::type.
Create() [2/2]
static Function* sysy::ir::Function::Create (FunctionType * type, const std::string & name) inline static
References Function(), sysy::ir::Value::name, and sysy::ir::Value::type.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::initRuntime(), and sysy::ir::irEmit().
getAllLoops()
std::vector< Loop * > & sysy::ir::Function::getAllLoops ()
References allLoops.
Referenced by sysy::ir::LoopInfo::computeExitBlocks(), sysy::ir::LoopInfo::computeExitingBlocks(), sysy::ir::LoopInfo::computeLatch(), sysy::ir::LoopInfo::computeLoopIndVar(), sysy::ir::LoopInfo::computePreHeader(), and sysy::ir::LoopInfo::run().
getArgs()
ArgVec& sysy::ir::Function::getArgs () inline
References args.
Referenced by sysy::mc::Function::analyseFunc(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::irEmit(), and sysy::ir::FunctionVertify::run().
getBasicBlockList()
std::list<BasicBlock*>& sysy::ir::Function::getBasicBlockList () inline
References basicBlock.
Referenced by sysy::mc::Function::analyseFunc(), sysy::ir::PRE::buildCollectOccurrences(), sysy::ir::MemorySSA::computeArrayInfo(), sysy::ir::MemorySSA::computeScalarGVInfo(), sysy::ir::BasicBlock::Create(), sysy::ir::IpdomGen::getDfnum(), sysy::ir::IdomGen::getDfnum(), sysy::ir::IRCopier::getFunctionCopy(), getSignature(), sysy::ir::PRE::insertPhiInstruction(), sysy::ir::irEmit(), sysy::ir::SimplifyCFG::removeDeadBB(), sysy::ir::ConstructExitBasicBlock::run(), sysy::ir::InstructionCombine::run(), sysy::ir::CleanExitBasicBlock::run(), sysy::ir::EliminatePhi::run(), sysy::ir::PostDomTreeGen::run(), sysy::ir::DomTreeGen::run(), and sysy::ir::ClearMemorySSA::run().
getCallee()
std::set<Function*>& sysy::ir::Function::getCallee () inline
References callee.
getCaller()
std::set<Function*>& sysy::ir::Function::getCaller () inline
References caller.
getCallSite()
std::vector<CallInstruction*>& sysy::ir::Function::getCallSite () inline
References callSite.
getEntryBlock()
BasicBlock* sysy::ir::Function::getEntryBlock () inline
References basicBlock.
Referenced by sysy::mc::Function::analyseFunc(), sysy::ir::CreateEntryBlockAlloca(), sysy::ir::MemorySSA::DefUseCompute(), sysy::ir::SimplifyCFG::deleteEmptyBB(), sysy::ir::IdomGen::getDfnum(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::globalInit(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::SimplifyCFG::removeDeadBB(), sysy::ir::SplitCriticalEdge::run(), sysy::ir::ADCE::run(), sysy::ir::FunctionVertify::run(), sysy::ir::EliminatePhi::run(), sysy::ir::LoopInfo::run(), sysy::ir::GCM::run(), sysy::ir::SimplifyCFG::run(), sysy::ir::DCE::run(), sysy::ir::IdomGen::run(), sysy::ir::PostDomTreeGen::run(), sysy::ir::GVN::run(), sysy::ir::DomTreeGen::run(), sysy::ir::Memory2Reg::run(), sysy::ir::DomFrontierGen::run(), sysy::ir::PRE::run(), sysy::ir::GCM::schduleEarly(), and sysy::ir::MemorySSA::UseDefCompute().
getExitBlock()
BasicBlock* sysy::ir::Function::getExitBlock () inline
References exitBlock.
Referenced by sysy::ir::IpdomGen::getDfnum(), sysy::ir::ConstructExitBasicBlock::run(), sysy::ir::CleanExitBasicBlock::run(), sysy::ir::IpdomGen::run(), and sysy::ir::PostDomFrontierGen::run().
getLoadGV()
std::set<GlobalValue*>& sysy::ir::Function::getLoadGV () inline
References loadGV.
getLoopOfBB()
Loop* sysy::ir::Function::getLoopOfBB (BasicBlock * bb) inline
References bbToLoop.
Referenced by sysy::mc::Function::analyseFunc(), and sysy::ir::LoopInfo::discoverAndMapSubloop().
getReturnType()
Type* sysy::ir::Function::getReturnType () inline
References retType.
Referenced by sysy::ir::CleanExitBasicBlock::run().
getSignature()
std::string sysy::ir::Function::getSignature () override virtual
Implements sysy::ir::Value.
References args, getBasicBlockList(), sysy::ir::Value::getName(), sysy::ir::Type::getSignature(), sysy::ir::Value::getType(), and isDeclare().
getStoreGV()
std::set<GlobalValue*>& sysy::ir::Function::getStoreGV () inline
References storeGV.
getTopLoops()
std::vector< Loop * > & sysy::ir::Function::getTopLoops ()
References topLoops.
Referenced by sysy::ir::LoopUnrollAll::run(), sysy::ir::LoopParallel::run(), sysy::ir::LCSSA::run(), sysy::ir::LSR::run(), sysy::ir::ScalarEvolution::run(), sysy::ir::LoopInfo::run(), and sysy::ir::ScalarEvolutionClean::run().
hasSideEffect()
bool sysy::ir::Function::hasSideEffect () inline
References sideEffect.
isDeclare()
bool sysy::ir::Function::isDeclare () inline
References basicBlock.
Referenced by getSignature().
isParallelZeon()
bool sysy::ir::Function::isParallelZeon () inline
References innerFunction.
isRecursive()
bool sysy::ir::Function::isRecursive () inline
References recursive.
Referenced by sysy::ir::LoopParallel::run().
linkBBToLoop()
void sysy::ir::Function::linkBBToLoop (BasicBlock * bb, Loop * loop) inline
References bbToLoop.
Referenced by sysy::ir::LoopInfo::discoverAndMapSubloop().
noSideEffect()
void sysy::ir::Function::noSideEffect () inline
References sideEffect.
setExitBlock()
void sysy::ir::Function::setExitBlock (BasicBlock * exit) inline
References exitBlock.
Referenced by sysy::ir::ConstructExitBasicBlock::run(), and sysy::ir::CleanExitBasicBlock::run().
setRecursive()
void sysy::ir::Function::setRecursive () inline
References recursive.
Member Data Documentation
allLoops
std::vector<Loop*> sysy::ir::Function::allLoops private
Referenced by getAllLoops().
args
ArgVec sysy::ir::Function::args private
Referenced by arg_size(), Function(), getArgs(), and getSignature().
basicBlock
std::list<BasicBlock*> sysy::ir::Function::basicBlock private
Referenced by getBasicBlockList(), getEntryBlock(), and isDeclare().
bbToLoop
std::unordered_map<BasicBlock*, Loop*> sysy::ir::Function::bbToLoop private
Referenced by clearLinkOfBBToLoop(), getLoopOfBB(), and linkBBToLoop().
callee
std::set<Function*> sysy::ir::Function::callee private
Referenced by getCallee().
caller
std::set<Function*> sysy::ir::Function::caller private
Referenced by getCaller().
callSite
std::vector<CallInstruction*> sysy::ir::Function::callSite private
Referenced by getCallSite().
exitBlock
BasicBlock* sysy::ir::Function::exitBlock = nullptr private
Referenced by getExitBlock(), and setExitBlock().
funcIter
FuncIter sysy::ir::Function::funcIter private
Referenced by Function().
innerFunction
bool sysy::ir::Function::innerFunction = false private
Referenced by isParallelZeon().
loadGV
std::set<GlobalValue*> sysy::ir::Function::loadGV private
Referenced by getLoadGV().
recursive
bool sysy::ir::Function::recursive = false private
Referenced by isRecursive(), and setRecursive().
retType
Type* sysy::ir::Function::retType private
Referenced by getReturnType().
sideEffect
bool sysy::ir::Function::sideEffect = true private
Referenced by hasSideEffect(), and noSideEffect().
storeGV
std::set<GlobalValue*> sysy::ir::Function::storeGV private
Referenced by getStoreGV().
topLoops
std::vector<Loop*> sysy::ir::Function::topLoops private
Referenced by getTopLoops().
The documentation for this class was generated from the following files:
include/sysy/IR/Function.h
lib/IR/Function.cpp
lib/IR/IRDump.cpp