Diana: sysy::Pass< Opt > Class Template Reference
sysy::Pass< Opt > Class Template Reference abstract
#include <PassManager.h>
Public Types
using DfsFunc = std::function< void(Pass< Opt > *)>
Public Member Functions
virtual ~Pass ()
virtual void run (Opt opt)=0
virtual std::string getName ()=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Static Public Member Functions
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Private Attributes
std::vector< Pass< Opt > * > relatedPasses
std::vector< Pass< Opt > * > passFinishBy
Member Typedef Documentation
DfsFunc
template<typename Opt > using sysy::Pass< Opt >::DfsFunc = std::function<void(Pass<Opt>*)>
Constructor & Destructor Documentation
~Pass()
template<typename Opt > virtual sysy::Pass< Opt >::~Pass () inline virtual
Member Function Documentation
finishByDfs()
template<typename Opt > static void sysy::Pass< Opt >::finishByDfs (Pass< Opt > * pass, DfsFunc func) inline static
References sysy::Pass< Opt >::getFinish().
Referenced by sysy::PassManager< Opt >::addPass().
getFinish()
template<typename Opt > std::vector<Pass<Opt>*>& sysy::Pass< Opt >::getFinish () inline
References sysy::Pass< Opt >::passFinishBy.
Referenced by sysy::ir::ADCE::ADCE(), sysy::PassManager< Opt >::addPass(), sysy::ir::EliminatePhi::EliminatePhi(), sysy::Pass< Opt >::finishByDfs(), sysy::ir::GCM::GCM(), sysy::ir::GVN::GVN(), sysy::ir::LoopEarlyPass::LoopEarlyPass(), sysy::ir::LoopParallel::LoopParallel(), sysy::ir::LoopUnrollAll::LoopUnrollAll(), sysy::ir::LoopVariablePass::LoopVariablePass(), sysy::ir::LSR::LSR(), and sysy::ir::PRE::PRE().
getName()
template<typename Opt > virtual std::string sysy::Pass< Opt >::getName () pure virtual
Implemented in sysy::ir::PRE, sysy::ir::DomFrontierGen, sysy::ir::PostDomFrontierGen, sysy::ir::LoopEarlyPass, sysy::ir::Memory2Reg, sysy::ir::DomTreeGen, sysy::ir::PostDomTreeGen, sysy::ir::LoopVariablePass, sysy::ir::GVN, sysy::ir::ScalarEvolutionClean, sysy::ir::IdomGen, sysy::ir::LinearScalarPass, sysy::ir::IpdomGen, sysy::ir::DCE, sysy::ir::GCM, sysy::ir::SimplifyCFG, sysy::ir::EliminatePhi, sysy::ir::ScalarEvolution, sysy::ir::FunctionVertify, sysy::ir::LSR, sysy::ir::LCSSA, sysy::ir::SSASet, sysy::ir::ScalarPass, sysy::ir::CleanExitBasicBlock, sysy::ir::ADCE, sysy::ir::InstructionCombine, sysy::ir::LoopParallel, sysy::ir::FunctionInline, sysy::ir::LoopUnrollAll, sysy::ir::SplitCriticalEdge, sysy::ir::DomInfo, sysy::ir::ModuleVertify, sysy::ir::IPDCE, sysy::ir::PostDomInfo, sysy::ir::LoaclDCE, sysy::ir::LocalGCM, sysy::ir::LocalGVN, sysy::ir::IPAnalysis, sysy::ir::UnsetSSA, sysy::ir::ConstructExitBasicBlock, sysy::ir::ClearMemorySSA, sysy::ir::MemorySSA, sysy::PassManager< Opt >, and sysy::ir::LoopInfo.
getRelated()
template<typename Opt > std::vector<Pass<Opt>*>& sysy::Pass< Opt >::getRelated () inline
References sysy::Pass< Opt >::relatedPasses.
Referenced by sysy::ir::ADCE::ADCE(), sysy::ir::FunctionInline::FunctionInline(), sysy::ir::GCM::GCM(), sysy::ir::GVN::GVN(), sysy::ir::IPDCE::IPDCE(), sysy::ir::LocalGVN::LocalGVN(), sysy::ir::LoopInfo::LoopInfo(), sysy::ir::LoopParallel::LoopParallel(), sysy::ir::LoopUnrollAll::LoopUnrollAll(), sysy::ir::LSR::LSR(), sysy::ir::Memory2Reg::Memory2Reg(), sysy::ir::MemorySSA::MemorySSA(), sysy::ir::PRE::PRE(), sysy::Pass< Opt >::relatedDfs(), and sysy::ir::ScalarPass::ScalarPass().
relatedDfs()
template<typename Opt > static void sysy::Pass< Opt >::relatedDfs (Pass< Opt > * pass, DfsFunc func) inline static
References sysy::Pass< Opt >::getRelated().
Referenced by sysy::PassManager< Opt >::addPass().
run()
template<typename Opt > virtual void sysy::Pass< Opt >::run (Opt opt) pure virtual
Implemented in sysy::PassManager< Opt >.
Member Data Documentation
passFinishBy
template<typename Opt > std::vector<Pass<Opt>*> sysy::Pass< Opt >::passFinishBy private
Referenced by sysy::Pass< Opt >::getFinish().
relatedPasses
template<typename Opt > std::vector<Pass<Opt>*> sysy::Pass< Opt >::relatedPasses private
Referenced by sysy::Pass< Opt >::getRelated().
The documentation for this class was generated from the following file:
include/sysy/IR/PassManager.h