Diana: sysy::AstScope Class Reference
sysy::AstScope Class Reference
#include <Semantics.h>
Public Member Functions
AstScope (AstScope *_father)
AstScope ()
AstScope * getFather () override
ast::AstType getType (std::string varName)
std::vector< int > getDim (std::string varName)
void insertDim (std::string name, std::vector< int > dimSize)
void insertVariable (std::string name, ast::AstType type)
AstScope * createChild ()
void insertInitial (std::string varName, ast::InitValNode *initial)
ast::InitValNode * getInitial (std::string varName)
bool isConst (std::string name)
void setCosnt (std::string name)
Static Public Member Functions
static AstScope * exitBlock (AstScope *ptr)
static AstScope *& getCurrentPtr ()
Protected Attributes
AstScope * father
std::unordered_map< std::string, ast::AstType > declType
std::unordered_map< std::string, std::vector< int > > dimSize
std::unordered_map< std::string, ast::InitValNode * > constInitial
std::unordered_set< std::string > constVar
Constructor & Destructor Documentation
AstScope() [1/2]
sysy::AstScope::AstScope (AstScope * _father) inline
AstScope() [2/2]
sysy::AstScope::AstScope () inline
Referenced by createChild(), and getCurrentPtr().
Member Function Documentation
createChild()
AstScope * sysy::AstScope::createChild ()
References AstScope(), and sysy::ir::child.
exitBlock()
AstScope * sysy::AstScope::exitBlock (AstScope * ptr) static
References father.
Referenced by sysy::SysYVisitor::visitBlock(), and sysy::SysYVisitor::visitFuncDef().
getCurrentPtr()
static AstScope*& sysy::AstScope::getCurrentPtr () inline static
References AstScope().
Referenced by sysy::SysYVisitor::visitBlock(), sysy::SysYVisitor::visitCompUnit(), sysy::SysYVisitor::visitConstDef(), sysy::SysYVisitor::visitFuncDef(), sysy::SysYVisitor::visitLVal(), sysy::SysYVisitor::visitPrimaryExp(), sysy::SysYVisitor::visitUnaryExp(), sysy::SysYVisitor::visitVarDecl(), and sysy::SysYVisitor::visitVarDecl_in().
getDim()
std::vector< int > sysy::AstScope::getDim (std::string varName)
References dimSize, ErrorMsg, father, and getDim().
Referenced by getDim().
getFather()
AstScope * sysy::AstScope::getFather () override virtual
Implements sysy::Scope.
References father.
getInitial()
ast::InitValNode * sysy::AstScope::getInitial (std::string varName)
References constInitial, father, and getInitial().
Referenced by getInitial().
getType()
ast::AstType sysy::AstScope::getType (std::string varName)
References declType, ErrorMsg, father, and getType().
Referenced by getType().
insertDim()
void sysy::AstScope::insertDim (std::string name, std::vector< int > dimSize)
References dimSize, ErrorMsg, and sysy::name.
insertInitial()
void sysy::AstScope::insertInitial (std::string varName, ast::InitValNode * initial)
References constInitial.
insertVariable()
void sysy::AstScope::insertVariable (std::string name, ast::AstType type)
References declType, ErrorMsg, sysy::name, and sysy::type.
isConst()
bool sysy::AstScope::isConst (std::string name)
References constVar, father, isConst(), and sysy::name.
Referenced by isConst().
setCosnt()
void sysy::AstScope::setCosnt (std::string name)
References constVar, and sysy::name.
Member Data Documentation
constInitial
std::unordered_map<std::string, ast::InitValNode*> sysy::AstScope::constInitial protected
Referenced by getInitial(), and insertInitial().
constVar
std::unordered_set<std::string> sysy::AstScope::constVar protected
Referenced by isConst(), and setCosnt().
declType
std::unordered_map<std::string, ast::AstType> sysy::AstScope::declType protected
Referenced by getType(), and insertVariable().
dimSize
std::unordered_map<std::string, std::vector<int> > sysy::AstScope::dimSize protected
Referenced by getDim(), and insertDim().
father
AstScope* sysy::AstScope::father protected
Referenced by exitBlock(), getDim(), getFather(), getInitial(), getType(), and isConst().
The documentation for this class was generated from the following files:
include/sysy/Frontend/Semantics.h
lib/Frontend/AstTramsform.cpp