Diana: sysy::ir::LCSSA Class Reference
sysy::ir::LCSSA Class Reference
#include <LCSSA.h>
Public Member Functions
LCSSA ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void runOnLoop (Loop *loop)
void computeDefInUseOut (Loop *loop, std::unordered_set< Instruction * > &DefInUseOut)
void insertLoopClosedPhi (Loop *loop, Instruction *instr)
Value * getIncomingValAtBB (BasicBlock *bb, Instruction *instr, std::unordered_map< BasicBlock *, PhiInst * > &BBToPhi, Loop *loop)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
LCSSA()
sysy::ir::LCSSA::LCSSA ()
Member Function Documentation
computeDefInUseOut()
void sysy::ir::LCSSA::computeDefInUseOut (Loop * loop, std::unordered_set< Instruction * > & DefInUseOut) private
References sysy::ir::Loop::BBSet, and sysy::ir::Loop::getLoopBasicBlocks().
Referenced by runOnLoop().
getIncomingValAtBB()
Value * sysy::ir::LCSSA::getIncomingValAtBB (BasicBlock * bb, Instruction * instr, std::unordered_map< BasicBlock *, PhiInst * > & BBToPhi, Loop * loop) private
References sysy::ir::Loop::BBSet, sysy::ir::UndefValue::Create(), sysy::ir::BasicBlock::getIdom(), sysy::ir::Value::getName(), sysy::ir::Value::getType(), and sysy::ir::BasicBlock::insertFront().
Referenced by insertLoopClosedPhi().
getName()
std::string sysy::ir::LCSSA::getName () inline override virtual
Implements sysy::Pass< Opt >.
insertLoopClosedPhi()
void sysy::ir::LCSSA::insertLoopClosedPhi (Loop * loop, Instruction * instr) private
References sysy::ir::Loop::BBSet, sysy::ir::Instruction::getBasicBlock(), sysy::ir::Loop::getExitBlocks(), getIncomingValAtBB(), sysy::ir::Value::getName(), sysy::ir::Value::getType(), and sysy::ir::Value::getUses().
Referenced by runOnLoop().
run()
void sysy::ir::LCSSA::run (Function * func) override
References sysy::ir::Value::getName(), sysy::ir::Function::getTopLoops(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::LCSSA::runOnLoop (Loop * loop) private
References computeDefInUseOut(), sysy::ir::Loop::getExitBlocks(), sysy::ir::Loop::getSubLoops(), and insertLoopClosedPhi().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/LCSSA.h
lib/Transform/Utils/LCSSA.cpp