Diana: SysYParser::ConstDefContext Class Reference
SysYParser::ConstDefContext Class Reference
#include <SysYParser.h>
Public Member Functions
ConstDefContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * Ident ()
antlr4::tree::TerminalNode * AGN ()
ConstInitValContext * constInitVal ()
std::vector< antlr4::tree::TerminalNode * > LSBRA ()
antlr4::tree::TerminalNode * LSBRA (size_t i)
std::vector< ConstExpContext * > constExp ()
ConstExpContext * constExp (size_t i)
std::vector< antlr4::tree::TerminalNode * > RSBRA ()
antlr4::tree::TerminalNode * RSBRA (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConstDefContext()
SysYParser::ConstDefContext::ConstDefContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::ConstDefContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
AGN()
tree::TerminalNode * SysYParser::ConstDefContext::AGN ()
References SysYParser::AGN.
constExp() [1/2]
std::vector< SysYParser::ConstExpContext * > SysYParser::ConstDefContext::constExp ()
Referenced by sysy::SysYVisitor::visitConstDef().
constExp() [2/2]
SysYParser::ConstExpContext * SysYParser::ConstDefContext::constExp (size_t i)
constInitVal()
SysYParser::ConstInitValContext * SysYParser::ConstDefContext::constInitVal ()
Referenced by sysy::SysYVisitor::visitConstDef().
getRuleIndex()
size_t SysYParser::ConstDefContext::getRuleIndex () const override virtual
References SysYParser::RuleConstDef.
Ident()
tree::TerminalNode * SysYParser::ConstDefContext::Ident ()
References SysYParser::Ident.
Referenced by sysy::SysYVisitor::visitConstDef().
LSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::ConstDefContext::LSBRA ()
References SysYParser::LSBRA.
LSBRA() [2/2]
tree::TerminalNode * SysYParser::ConstDefContext::LSBRA (size_t i)
References SysYParser::LSBRA.
RSBRA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::ConstDefContext::RSBRA ()
References SysYParser::RSBRA.
RSBRA() [2/2]
tree::TerminalNode * SysYParser::ConstDefContext::RSBRA (size_t i)
References SysYParser::RSBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp