Diana: sysy::ir::GVN Class Reference
sysy::ir::GVN Class Reference
#include <GVN.h>
Public Member Functions
GVN ()
std::string getName () override
void run (Function *func) override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void doPerInstr (Instruction *instr)
Value * checkoutTable (Value *val)
Value * getValueNumber (Instruction *instr)
Value * getValueNumber (BinaryInst *binary)
Value * getValueNumber (UnaryInst *unary)
Value * getValueNumber (PhiInst *phi)
Value * getValueNumber (GEPInst *gep)
Value * getValueNumber (CallInst *call)
Value * getValueNumber (LoadInst *load)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
GVN()
sysy::ir::GVN::GVN ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
checkoutTable()
Value * sysy::ir::GVN::checkoutTable (Value * val) private
References sysy::ir::ConstantInt::getValue(), sysy::ir::ConstantFP::getValue(), getValueNumber(), and sysy::ir::ValueNumber.
Referenced by doPerInstr(), and getValueNumber().
doPerInstr()
void sysy::ir::GVN::doPerInstr (Instruction * instr) private
References checkoutTable(), sysy::ir::ConstantInt::get(), sysy::ir::ConstantFP::get(), sysy::ir::Type::getInt32Ty(), sysy::ir::getOriginArray(), sysy::ir::Value::getUses(), sysy::ir::ConstantInt::getZero(), sysy::ir::ConstantFP::getZero(), sysy::ir::GlobalValue::isConstant(), sysy::ir::replace(), sysy::ir::simplifyInstruction(), and sysy::ir::ValueNumber.
Referenced by run().
getName()
std::string sysy::ir::GVN::getName () inline override virtual
Implements sysy::Pass< Opt >.
getValueNumber() [1/7]
Value * sysy::ir::GVN::getValueNumber (BinaryInst * binary) private
References checkoutTable(), sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), sysy::ir::Instruction::isCommutative(), sysy::ir::Instruction::isReverse(), and sysy::ir::ValueNumber.
getValueNumber() [2/7]
Value * sysy::ir::GVN::getValueNumber (CallInst * call) private
getValueNumber() [3/7]
Value * sysy::ir::GVN::getValueNumber (GEPInst * gep) private
References checkoutTable(), sysy::ir::GEPInstruction::getIndex(), sysy::ir::GEPInstruction::getPtr(), sysy::ir::GEPInstruction::size(), and sysy::ir::ValueNumber.
getValueNumber() [4/7]
Value * sysy::ir::GVN::getValueNumber (Instruction * instr) private
Referenced by checkoutTable().
getValueNumber() [5/7]
Value * sysy::ir::GVN::getValueNumber (LoadInst * load) private
References checkoutTable(), sysy::ir::LoadInstruction::getPtr(), sysy::ir::LoadInstruction::getStore(), and sysy::ir::ValueNumber.
getValueNumber() [6/7]
Value * sysy::ir::GVN::getValueNumber (PhiInst * phi) private
References sysy::ir::Instruction::getBasicBlock(), sysy::ir::PhiInstruction::getPredecessors(), sysy::ir::PhiInstruction::size(), and sysy::ir::ValueNumber.
getValueNumber() [7/7]
Value * sysy::ir::GVN::getValueNumber (UnaryInst * unary) private
References checkoutTable(), sysy::ir::Instruction::getKind(), sysy::ir::UnaryInstruction::getValue(), and sysy::ir::ValueNumber.
run()
void sysy::ir::GVN::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfsPost(), doPerInstr(), sysy::ir::fixed, sysy::ir::Function::getEntryBlock(), sysy::ir::Value::getName(), sysy::ir::InstrToRemove, PrintMsg, sysy::ir::BasicBlock::rbegin(), sysy::ir::BasicBlock::rend(), and sysy::ir::ValueNumber.
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/GVN.h
lib/Transform/Scalar/GVN.cpp