Diana: sysy::ir::InstructionCombine Class Reference
sysy::ir::InstructionCombine Class Reference
#include <InstructionCombine.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
Instruction * visitBinary (BinaryInst *binary)
Instruction * visitAdd (BinaryInst *add)
Instruction * visitSub (BinaryInst *sub)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
getName()
std::string sysy::ir::InstructionCombine::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::InstructionCombine::run (Function * func) override
References sysy::ir::Function::getBasicBlockList(), PrintMsg, sysy::ir::simplifyInstruction(), and visitBinary().
visitAdd()
Instruction * sysy::ir::InstructionCombine::visitAdd (BinaryInst * add) private
References sysy::ir::ConstantInt::get(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), and sysy::ir::Value::getType().
Referenced by visitBinary().
visitBinary()
Instruction * sysy::ir::InstructionCombine::visitBinary (BinaryInst * binary) private
References sysy::ir::Instruction::getKind(), visitAdd(), and visitSub().
Referenced by run().
visitSub()
Instruction * sysy::ir::InstructionCombine::visitSub (BinaryInst * sub) private
References sysy::ir::ConstantInt::get(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), and sysy::ir::Value::getType().
Referenced by visitBinary().
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/InstructionCombine.h
lib/Transform/Scalar/InstructionCombine.cpp