Diana: sysy::ir::Loop Class Reference
sysy::ir::Loop Class Reference
#include <Loop.h>
Public Types
using scev_iterator = std::unordered_map< Instruction *, SCEV >::iterator
Public Member Functions
Loop (BasicBlock *header)
Function * getParent ()
void setLoopDepth (int depth)
int getLoopDepth ()
Loop * getParentLoop ()
void setParentLoop (Loop *parent)
std::vector< Loop * > & getSubLoops ()
std::vector< BasicBlock * > & getLoopBasicBlocks ()
BasicBlock * getHeader ()
std::unordered_set< BasicBlock * > & getExitingBlocks ()
std::unordered_set< BasicBlock * > & getExitBlocks ()
BasicBlock * getLatchBlock ()
void setLatchBlock (BasicBlock *latch)
BasicBlock * getPreHeader ()
void setPreHeader (BasicBlock *_preHeader)
SCEV & getSCEV (Instruction *instr)
bool hasSCEV (Instruction *instr)
void registerSCEV (Instruction *instr, SCEV scev)
void cleanSCEV ()
iterator_range< scev_iterator > getSCEV ()
PhiInst * getIndexPhi ()
void setIndexPhi (PhiInst *phi)
Value * getIndexEnd ()
void setIndexEnd (Value *end)
Instruction * getIndexCondInstr ()
void setIndexCondInstr (Instruction *instr)
int getTripCount ()
void setTripCount (int c)
void setICmpKind (Instruction::InstrKind kind)
Instruction::InstrKind getICmpKind ()
bool isLoopInvariant (Value *val)
Public Attributes
std::unordered_set< BasicBlock * > BBSet
Private Attributes
Function * parent
int loopDepth
Loop * parentLoop
BasicBlock * loopHeader
std::vector< Loop * > subLoops
std::vector< BasicBlock * > blocks
std::unordered_set< BasicBlock * > exitingBlocks
std::unordered_set< BasicBlock * > exitBlocks
BasicBlock * latchBlock
BasicBlock * preHeader
std::unordered_map< Instruction *, SCEV > SCEVCheck
PhiInst * indPhi
Instruction * indCondVar
Value * indEnd
Instruction::InstrKind icmpKind
int tripCount
Member Typedef Documentation
scev_iterator
using sysy::ir::Loop::scev_iterator = std::unordered_map<Instruction*, SCEV>::iterator
Constructor & Destructor Documentation
Loop()
sysy::ir::Loop::Loop (BasicBlock * header)
References BBSet, and blocks.
Member Function Documentation
cleanSCEV()
void sysy::ir::Loop::cleanSCEV () inline
References SCEVCheck.
Referenced by sysy::ir::ScalarEvolution::runOnLoop().
getExitBlocks()
std::unordered_set<BasicBlock*>& sysy::ir::Loop::getExitBlocks () inline
References exitBlocks.
Referenced by sysy::ir::LCSSA::insertLoopClosedPhi(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::LoopUnrollAll::runOnLoop(), sysy::ir::LoopParallel::runOnLoop(), and sysy::ir::LCSSA::runOnLoop().
getExitingBlocks()
std::unordered_set<BasicBlock*>& sysy::ir::Loop::getExitingBlocks () inline
References exitingBlocks.
Referenced by sysy::ir::LoopParallel::isParallelizable(), and sysy::ir::LoopUnrollAll::runOnLoop().
getHeader()
BasicBlock* sysy::ir::Loop::getHeader () inline
References loopHeader.
Referenced by sysy::ir::LoopInfo::discoverAndMapSubloop(), sysy::ir::LSR::eraseSingleMul(), sysy::ir::ScalarEvolution::findAndRegisterBIV(), sysy::ir::IRCopier::getLoopCopy(), and sysy::ir::LoopUnrollAll::runOnLoop().
getICmpKind()
Instruction::InstrKind sysy::ir::Loop::getICmpKind () inline
References icmpKind.
Referenced by sysy::ir::ScalarEvolution::runOnLoop().
getIndexCondInstr()
Instruction* sysy::ir::Loop::getIndexCondInstr () inline
References indCondVar.
Referenced by sysy::ir::LoopParallel::runOnLoop().
getIndexEnd()
Value* sysy::ir::Loop::getIndexEnd () inline
References indEnd.
Referenced by sysy::ir::LoopParallel::isParallelizable(), sysy::ir::LoopParallel::runOnLoop(), and sysy::ir::ScalarEvolution::runOnLoop().
getIndexPhi()
PhiInst* sysy::ir::Loop::getIndexPhi () inline
References indPhi.
Referenced by sysy::ir::LoopParallel::isParallelizable(), sysy::ir::LoopParallel::runOnLoop(), and sysy::ir::ScalarEvolution::runOnLoop().
getLatchBlock()
BasicBlock* sysy::ir::Loop::getLatchBlock () inline
References latchBlock.
Referenced by sysy::ir::LSR::eraseSingleMul(), sysy::ir::IRCopier::getLoopCopy(), sysy::ir::LoopParallel::isParallelizable(), and sysy::ir::LoopUnrollAll::runOnLoop().
getLoopBasicBlocks()
std::vector<BasicBlock*>& sysy::ir::Loop::getLoopBasicBlocks () inline
References blocks.
Referenced by sysy::ir::LCSSA::computeDefInUseOut(), sysy::ir::IRCopier::getLoopCopy(), sysy::ir::LSR::identifyAllInductiveMultiplication(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::LoopUnrollAll::runOnLoop(), and sysy::ir::ScalarEvolution::runOnLoop().
getLoopDepth()
int sysy::ir::Loop::getLoopDepth () inline
References loopDepth.
getParent()
Function* sysy::ir::Loop::getParent () inline
References parent.
Referenced by sysy::ir::IRCopier::getLoopCopy().
getParentLoop()
Loop* sysy::ir::Loop::getParentLoop () inline
References parentLoop.
getPreHeader()
BasicBlock* sysy::ir::Loop::getPreHeader () inline
References preHeader.
Referenced by sysy::ir::LSR::eraseSingleMul(), sysy::ir::LoopUnrollAll::runOnLoop(), and sysy::ir::LoopParallel::runOnLoop().
getSCEV() [1/2]
iterator_range<scev_iterator> sysy::ir::Loop::getSCEV () inline
References sysy::make_range(), and SCEVCheck.
getSCEV() [2/2]
SCEV & sysy::ir::Loop::getSCEV (Instruction * instr)
References SCEVCheck.
Referenced by sysy::ir::LSR::eraseSingleMul(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::ScalarEvolution::linkInstructionToSCEV(), sysy::ir::LoopParallel::runOnLoop(), sysy::ir::ScalarEvolution::runOnLoop(), and sysy::ir::ScalarEvolutionClean::runOnLoop().
getSubLoops()
std::vector<Loop*>& sysy::ir::Loop::getSubLoops () inline
References subLoops.
Referenced by sysy::ir::LCSSA::runOnLoop(), sysy::ir::ScalarEvolution::runOnLoop(), sysy::ir::LSR::runOnLoop(), and sysy::ir::ScalarEvolutionClean::runOnLoop().
getTripCount()
int sysy::ir::Loop::getTripCount () inline
References tripCount.
Referenced by sysy::ir::LoopParallel::isParallelizable(), and sysy::ir::LoopUnrollAll::runOnLoop().
hasSCEV()
bool sysy::ir::Loop::hasSCEV (Instruction * instr)
References SCEVCheck.
Referenced by sysy::ir::LSR::identifyAllInductiveMultiplication(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::ScalarEvolution::linkInstructionToSCEV(), and sysy::ir::ScalarEvolution::runOnLoop().
isLoopInvariant()
bool sysy::ir::Loop::isLoopInvariant (Value * val)
References BBSet.
Referenced by sysy::ir::ScalarEvolution::BIV2SCEV(), sysy::ir::ScalarEvolution::findAndRegisterBIV(), sysy::ir::LoopParallel::isParallelizable(), sysy::ir::ScalarEvolution::linkInstructionToSCEV(), and sysy::ir::ScalarEvolution::registerBIV().
registerSCEV()
void sysy::ir::Loop::registerSCEV (Instruction * instr, SCEV scev)
References SCEVCheck.
Referenced by sysy::ir::ScalarEvolution::BIV2SCEV(), and sysy::ir::ScalarEvolution::linkInstructionToSCEV().
setICmpKind()
void sysy::ir::Loop::setICmpKind (Instruction::InstrKind kind) inline
References icmpKind.
setIndexCondInstr()
void sysy::ir::Loop::setIndexCondInstr (Instruction * instr) inline
References indCondVar.
setIndexEnd()
void sysy::ir::Loop::setIndexEnd (Value * end) inline
References indEnd.
setIndexPhi()
void sysy::ir::Loop::setIndexPhi (PhiInst * phi) inline
References indPhi.
setLatchBlock()
void sysy::ir::Loop::setLatchBlock (BasicBlock * latch) inline
References latchBlock.
setLoopDepth()
void sysy::ir::Loop::setLoopDepth (int depth) inline
References sysy::depth, and loopDepth.
setParentLoop()
void sysy::ir::Loop::setParentLoop (Loop * parent) inline
References parent, and parentLoop.
setPreHeader()
void sysy::ir::Loop::setPreHeader (BasicBlock * _preHeader) inline
References preHeader.
setTripCount()
void sysy::ir::Loop::setTripCount (int c) inline
References tripCount.
Referenced by sysy::ir::ScalarEvolution::runOnLoop().
Member Data Documentation
BBSet
std::unordered_set<BasicBlock*> sysy::ir::Loop::BBSet
Referenced by sysy::ir::LCSSA::computeDefInUseOut(), sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::LCSSA::insertLoopClosedPhi(), isLoopInvariant(), and Loop().
blocks
std::vector<BasicBlock*> sysy::ir::Loop::blocks private
Referenced by getLoopBasicBlocks(), and Loop().
exitBlocks
std::unordered_set<BasicBlock*> sysy::ir::Loop::exitBlocks private
Referenced by getExitBlocks().
exitingBlocks
std::unordered_set<BasicBlock*> sysy::ir::Loop::exitingBlocks private
Referenced by getExitingBlocks().
icmpKind
Instruction::InstrKind sysy::ir::Loop::icmpKind private
Referenced by getICmpKind(), and setICmpKind().
indCondVar
Instruction* sysy::ir::Loop::indCondVar private
Referenced by getIndexCondInstr(), and setIndexCondInstr().
indEnd
Value* sysy::ir::Loop::indEnd private
Referenced by getIndexEnd(), and setIndexEnd().
indPhi
PhiInst* sysy::ir::Loop::indPhi private
Referenced by getIndexPhi(), and setIndexPhi().
latchBlock
BasicBlock* sysy::ir::Loop::latchBlock private
Referenced by getLatchBlock(), and setLatchBlock().
loopDepth
int sysy::ir::Loop::loopDepth private
Referenced by getLoopDepth(), and setLoopDepth().
loopHeader
BasicBlock* sysy::ir::Loop::loopHeader private
Referenced by getHeader().
parent
Function* sysy::ir::Loop::parent private
Referenced by getParent(), and setParentLoop().
parentLoop
Loop* sysy::ir::Loop::parentLoop private
Referenced by getParentLoop(), and setParentLoop().
preHeader
BasicBlock* sysy::ir::Loop::preHeader private
Referenced by getPreHeader(), and setPreHeader().
SCEVCheck
std::unordered_map<Instruction*, SCEV> sysy::ir::Loop::SCEVCheck private
Referenced by cleanSCEV(), getSCEV(), hasSCEV(), and registerSCEV().
subLoops
std::vector<Loop*> sysy::ir::Loop::subLoops private
Referenced by getSubLoops().
tripCount
int sysy::ir::Loop::tripCount private
Referenced by getTripCount(), and setTripCount().
The documentation for this class was generated from the following files:
include/sysy/IR/Loop.h
lib/IR/Loop.cpp