Diana: sysy::ir::IRCopier Class Reference
sysy::ir::IRCopier Class Reference
#include <IRCopy.h>
Public Member Functions
Function * getFunctionCopy (Function *func)
Loop * getLoopCopy (Loop *loop, std::unordered_map< Value *, Value * > &LoopValueCpy, std::unordered_map< PhiInst *, Value * > &CurrentIncomingValue)
Static Public Member Functions
static Instruction * getCopyOfInstruction (Instruction *instr, std::function< Value *(Value *)> findValue)
Private Attributes
std::unordered_map< Value *, Value * > ValueCopy
Member Function Documentation
getCopyOfInstruction()
Instruction * sysy::ir::IRCopier::getCopyOfInstruction (Instruction * instr, std::function< Value *(Value *)> findValue) static
References sysy::name.
getFunctionCopy()
Function * sysy::ir::IRCopier::getFunctionCopy (Function * func)
References sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::Function::Create(), sysy::ir::BasicBlock::Create(), sysy::ir::Function::getArgs(), sysy::ir::Function::getBasicBlockList(), sysy::ir::Function::getEntryBlock(), sysy::ir::Module::getInstance(), sysy::ir::Value::getName(), sysy::ir::BasicBlock::getPredecessor(), sysy::ir::Value::getType(), and ValueCopy.
Referenced by sysy::ir::FunctionInline::inlineAtCall().
getLoopCopy()
Loop * sysy::ir::IRCopier::getLoopCopy (Loop * loop, std::unordered_map< Value *, Value * > & LoopValueCpy, std::unordered_map< PhiInst *, Value * > & CurrentIncomingValue)
References sysy::ir::Loop::getHeader(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::Loop::getLatchBlock(), sysy::ir::Loop::getLoopBasicBlocks(), sysy::ir::Value::getName(), and sysy::ir::Loop::getParent().
Referenced by sysy::ir::LoopUnrollAll::runOnLoop().
Member Data Documentation
ValueCopy
std::unordered_map<Value*, Value*> sysy::ir::IRCopier::ValueCopy private
Referenced by getFunctionCopy().
The documentation for this class was generated from the following files:
include/sysy/IR/IRCopy.h
lib/IR/IRCopy.cpp