Diana: sysy::ir::PRE Class Reference
sysy::ir::PRE Class Reference
#include <PRE.h>
Public Member Functions
PRE ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Static Public Member Functions
static bool sameOriginal (Value *x, Value *y)
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Private Member Functions
void buildCollectOccurrences (Function *func)
void insertPhiInstruction (Function *func)
void renaming (BasicBlock *entry)
void rename1 (BasicBlock *entry, CollectOccurrences &collect)
void rename2 (BasicBlock *entry, CollectOccurrences &collect)
void resetDownSafe (PhiOccurrence *, int index)
void downSafety (CollectOccurrences &collect)
void willBeAvail (CollectOccurrences &collect)
void resetCanBeAvail (PhiOccurrence *occ, CollectOccurrences &collect)
void computeCanBeAvail (CollectOccurrences &collect)
void resetLater (PhiOccurrence *occ, CollectOccurrences &collect)
void computeLater (CollectOccurrences &collect)
void finalize ()
void finalize1 (CollectOccurrences &collect)
void finalize2 (CollectOccurrences &collect)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Constructor & Destructor Documentation
PRE()
sysy::ir::PRE::PRE ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
buildCollectOccurrences()
void sysy::ir::PRE::buildCollectOccurrences (Function * func) private
References sysy::ir::collectOccurrencesList, and sysy::ir::Function::getBasicBlockList().
Referenced by run().
computeCanBeAvail()
void sysy::ir::PRE::computeCanBeAvail (CollectOccurrences & collect) private
References sysy::ir::canBeAvail, sysy::ir::downSafe, sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), and resetCanBeAvail().
Referenced by willBeAvail().
computeLater()
void sysy::ir::PRE::computeLater (CollectOccurrences & collect) private
References sysy::ir::canBeAvail, sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), sysy::ir::hasRealUse, sysy::ir::later, and resetLater().
Referenced by willBeAvail().
downSafety()
void sysy::ir::PRE::downSafety (CollectOccurrences & collect) private
References sysy::ir::downSafe, sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), and resetDownSafe().
Referenced by run().
finalize()
void sysy::ir::PRE::finalize () private
finalize1()
void sysy::ir::PRE::finalize1 (CollectOccurrences & collect) private
References sysy::ir::CollectOccurrences::allClasses.
finalize2()
void sysy::ir::PRE::finalize2 (CollectOccurrences & collect) private
getName()
std::string sysy::ir::PRE::getName () inline override virtual
Implements sysy::Pass< Opt >.
insertPhiInstruction()
void sysy::ir::PRE::insertPhiInstruction (Function * func) private
References sysy::ir::cnt, sysy::ir::collectOccurrencesList, sysy::ir::downSafe, sysy::ir::Function::getBasicBlockList(), and sysy::name.
Referenced by run().
rename1()
void sysy::ir::PRE::rename1 (BasicBlock * entry, CollectOccurrences & collect) private
References sysy::ir::CollectOccurrences::allClasses, sysy::ir::crossReal, sysy::ir::downSafe, sysy::ir::UndefOccurrence::get(), sysy::ir::CollectOccurrences::getExprFromBB(), sysy::ir::User::getOprands(), sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), sysy::ir::CollectOccurrences::getRealOccurrencesBB(), sysy::ir::hasRealUse, sysy::ir::Instruction::isCommutative(), sysy::name, sysy::ir::CollectOccurrences::occurrenceName, sysy::ir::CollectOccurrences::phiSize(), and sysy::ir::varCnt.
Referenced by renaming().
rename2()
void sysy::ir::PRE::rename2 (BasicBlock * entry, CollectOccurrences & collect) private
References sysy::ir::CollectOccurrences::getPhi(), and sysy::ir::CollectOccurrences::getPhiBB().
Referenced by renaming().
renaming()
void sysy::ir::PRE::renaming (BasicBlock * entry) private
References sysy::ir::collectOccurrencesList, rename1(), rename2(), and sysy::ir::varCnt.
Referenced by run().
resetCanBeAvail()
void sysy::ir::PRE::resetCanBeAvail (PhiOccurrence * occ, CollectOccurrences & collect) private
References sysy::ir::canBeAvail, sysy::ir::downSafe, sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), and sysy::ir::hasRealUse.
Referenced by computeCanBeAvail().
resetDownSafe()
void sysy::ir::PRE::resetDownSafe (PhiOccurrence * phi, int index) private
References sysy::ir::downSafe, sysy::ir::PhiOccurrence::getIncoming(), and sysy::ir::hasRealUse.
Referenced by downSafety().
resetLater()
void sysy::ir::PRE::resetLater (PhiOccurrence * occ, CollectOccurrences & collect) private
References sysy::ir::CollectOccurrences::getPhi(), sysy::ir::CollectOccurrences::getPhiBB(), and sysy::ir::later.
Referenced by computeLater().
run()
void sysy::ir::PRE::run (Function * func) override
References buildCollectOccurrences(), sysy::ir::collectOccurrencesList, downSafety(), sysy::ir::Function::getEntryBlock(), insertPhiInstruction(), renaming(), and willBeAvail().
sameOriginal()
bool sysy::ir::PRE::sameOriginal (Value * x, Value * y) static
Referenced by sysy::ir::CollectOccurrences::isSameExpr().
willBeAvail()
void sysy::ir::PRE::willBeAvail (CollectOccurrences & collect) private
References computeCanBeAvail(), and computeLater().
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/PRE.h
lib/Transform/Scalar/PRE.cpp