Diana: sysy::SysYVisitor Class Reference
sysy::SysYVisitor Class Reference
#include <SysYVisitor.h>
Public Member Functions
SysYVisitor (SysYParser &_parser)
void printCst (antlr4::ParserRuleContext *ctx, int depth)
void printSrc (SysYParser::CompUnitContext *ctx)
std::vector< std::unique_ptr< ExprNode > > constInitValDfs (SysYParser::ConstInitValContext *ctx, int idx)
std::vector< std::unique_ptr< ExprNode > > varInitValDfs (SysYParser::InitValContext *ctx, int idx)
antlrcpp::Any visitCompUnit (SysYParser::CompUnitContext *ctx) override
antlrcpp::Any visitElement (SysYParser::ElementContext *ctx) override
antlrcpp::Any visitDecl (SysYParser::DeclContext *ctx) override
antlrcpp::Any visitConstDecl (SysYParser::ConstDeclContext *ctx) override
antlrcpp::Any visitBType (SysYParser::BTypeContext *ctx) override
antlrcpp::Any visitConstDef (SysYParser::ConstDefContext *ctx) override
antlrcpp::Any visitConstInitVal (SysYParser::ConstInitValContext *ctx) override
antlrcpp::Any visitVarDecl (SysYParser::VarDeclContext *ctx) override
antlrcpp::Any visitVarDecl_in (SysYParser::VarDecl_inContext *ctx) override
antlrcpp::Any visitVarDef (SysYParser::VarDefContext *ctx) override
antlrcpp::Any visitInitVal (SysYParser::InitValContext *ctx) override
antlrcpp::Any visitFuncDef (SysYParser::FuncDefContext *ctx) override
antlrcpp::Any visitFuncType (SysYParser::FuncTypeContext *ctx) override
antlrcpp::Any visitFuncFParams (SysYParser::FuncFParamsContext *ctx) override
antlrcpp::Any visitFuncFParam (SysYParser::FuncFParamContext *ctx) override
antlrcpp::Any visitBlock (SysYParser::BlockContext *ctx) override
antlrcpp::Any visitBlockItem (SysYParser::BlockItemContext *ctx) override
antlrcpp::Any visitStmt_in (SysYParser::Stmt_inContext *ctx) override
antlrcpp::Any visitStmt (SysYParser::StmtContext *ctx) override
antlrcpp::Any visitExp (SysYParser::ExpContext *ctx) override
antlrcpp::Any visitCond (SysYParser::CondContext *ctx) override
antlrcpp::Any visitLVal (SysYParser::LValContext *ctx) override
antlrcpp::Any visitPrimaryExp (SysYParser::PrimaryExpContext *ctx) override
antlrcpp::Any visitNumber (SysYParser::NumberContext *ctx) override
antlrcpp::Any visitUnaryExp (SysYParser::UnaryExpContext *ctx) override
antlrcpp::Any visitUnaryOp (SysYParser::UnaryOpContext *ctx) override
antlrcpp::Any visitFuncRParams (SysYParser::FuncRParamsContext *ctx) override
antlrcpp::Any visitMulExp (SysYParser::MulExpContext *ctx) override
antlrcpp::Any visitAddExp (SysYParser::AddExpContext *ctx) override
antlrcpp::Any visitRelExp (SysYParser::RelExpContext *ctx) override
antlrcpp::Any visitEqExp (SysYParser::EqExpContext *ctx) override
antlrcpp::Any visitLAndExp (SysYParser::LAndExpContext *ctx) override
antlrcpp::Any visitLOrExp (SysYParser::LOrExpContext *ctx) override
antlrcpp::Any visitConstExp (SysYParser::ConstExpContext *ctx) override
antlrcpp::Any visitIntConst (SysYParser::IntConstContext *ctx) override
antlrcpp::Any visitFloatConst (SysYParser::FloatConstContext *ctx) override
Protected Attributes
SysYParser & parser
Constructor & Destructor Documentation
SysYVisitor()
sysy::SysYVisitor::SysYVisitor (SysYParser & _parser) inline
Member Function Documentation
constInitValDfs()
std::vector< std::unique_ptr< ExprNode > > sysy::SysYVisitor::constInitValDfs (SysYParser::ConstInitValContext * ctx, int idx)
References SysYParser::ConstInitValContext::constExp(), SysYParser::ConstInitValContext::constInitVal(), sysy::depth, sysy::dims, sysy::ast::INT, and PrintMsg.
printCst()
void sysy::SysYVisitor::printCst (antlr4::ParserRuleContext * ctx, int depth)
References sysy::ir::child, sysy::depth, and SysYParser::RuleCompUnit.
Referenced by sysy::FrontendMain().
printSrc()
void sysy::SysYVisitor::printSrc (SysYParser::CompUnitContext * ctx)
Referenced by sysy::FrontendMain().
varInitValDfs()
std::vector< std::unique_ptr< ExprNode > > sysy::SysYVisitor::varInitValDfs (SysYParser::InitValContext * ctx, int idx)
References sysy::depth, sysy::dims, SysYParser::InitValContext::exp(), SysYParser::InitValContext::initVal(), sysy::ast::INT, and PrintMsg.
visitAddExp()
antlrcpp::Any sysy::SysYVisitor::visitAddExp (SysYParser::AddExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::AddExpContext::ADD(), SysYParser::AddExpContext::addExp(), sysy::ast::BOP_ADD, sysy::ast::BOP_SUB, sysy::ast::Immediate::computeAssign(), sysy::ast::NumberNode::immediate, SysYParser::AddExpContext::mulExp(), PrintMsg, sysy::ast::Immediate::type, and sysy::ast::ExprNode::type.
visitBlock()
antlrcpp::Any sysy::SysYVisitor::visitBlock (SysYParser::BlockContext * ctx) override virtual
Returns
return type is BlockNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::BlockContext::blockItem(), sysy::AstScope::exitBlock(), sysy::AstScope::getCurrentPtr(), PrintMsg, and sysy::ast::removeDeadStmts().
visitBlockItem()
antlrcpp::Any sysy::SysYVisitor::visitBlockItem (SysYParser::BlockItemContext * ctx) override virtual
Returns
return type is StmtNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::BlockItemContext::decl(), PrintMsg, and SysYParser::BlockItemContext::stmt().
visitBType()
antlrcpp::Any sysy::SysYVisitor::visitBType (SysYParser::BTypeContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitCompUnit()
antlrcpp::Any sysy::SysYVisitor::visitCompUnit (SysYParser::CompUnitContext * ctx) override virtual
Returns
return type is CompUnitNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::CompUnitContext::element(), sysy::AstScope::getCurrentPtr(), sysy::name, PrintMsg, sysy::storedRuntime, and sysy::type.
Referenced by sysy::FrontendMain().
visitCond()
antlrcpp::Any sysy::SysYVisitor::visitCond (SysYParser::CondContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::CondContext::lOrExp(), and PrintMsg.
visitConstDecl()
antlrcpp::Any sysy::SysYVisitor::visitConstDecl (SysYParser::ConstDeclContext * ctx) override virtual
Returns
return type is ConstDeclNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::ConstDeclContext::bType(), sysy::constDeclType, SysYParser::ConstDeclContext::constDef(), sysy::ast::FLOAT, SysYParser::BTypeContext::FLOAT(), sysy::ast::INT, SysYParser::BTypeContext::INT(), and PrintMsg.
visitConstDef()
antlrcpp::Any sysy::SysYVisitor::visitConstDef (SysYParser::ConstDefContext * ctx) override virtual
Returns
return type is ConstDefNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::cnt, sysy::constDeclType, SysYParser::ConstDefContext::constExp(), SysYParser::ConstDefContext::constInitVal(), sysy::dims, ErrorMsg, sysy::AstScope::getCurrentPtr(), SysYParser::ConstDefContext::Ident(), and PrintMsg.
visitConstExp()
antlrcpp::Any sysy::SysYVisitor::visitConstExp (SysYParser::ConstExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::ConstExpContext::addExp(), and PrintMsg.
visitConstInitVal()
antlrcpp::Any sysy::SysYVisitor::visitConstInitVal (SysYParser::ConstInitValContext * ctx) override virtual
Returns
return type is InitValNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::ConstInitValContext::constExp(), SysYParser::ConstInitValContext::constInitVal(), and sysy::depth.
visitDecl()
antlrcpp::Any sysy::SysYVisitor::visitDecl (SysYParser::DeclContext * ctx) override virtual
Returns
return type is DeclNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::DeclContext::constDecl(), PrintMsg, and SysYParser::DeclContext::varDecl().
visitElement()
antlrcpp::Any sysy::SysYVisitor::visitElement (SysYParser::ElementContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitEqExp()
antlrcpp::Any sysy::SysYVisitor::visitEqExp (SysYParser::EqExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::ast::Immediate::computeAssign(), SysYParser::EqExpContext::eqExp(), SysYParser::EqExpContext::EQL(), sysy::ast::FLOAT, sysy::ast::Immediate::getType(), sysy::ast::NumberNode::immediate, sysy::ast::INT, PrintMsg, SysYParser::EqExpContext::relExp(), sysy::ast::ROP_EQL, sysy::ast::ROP_NEQ, and sysy::type.
visitExp()
antlrcpp::Any sysy::SysYVisitor::visitExp (SysYParser::ExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::ExpContext::addExp(), and PrintMsg.
visitFloatConst()
antlrcpp::Any sysy::SysYVisitor::visitFloatConst (SysYParser::FloatConstContext * ctx) override virtual
Returns
return type is float
Reimplemented from SysYParserBaseVisitor.
References SysYParser::FloatConstContext::DECFLOAT(), SysYParser::FloatConstContext::HEXFLOAT(), PrintMsg, strFloat(), and strFloatHex().
visitFuncDef()
antlrcpp::Any sysy::SysYVisitor::visitFuncDef (SysYParser::FuncDefContext * ctx) override virtual
Returns
return type is FuncDefNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::FuncDefContext::block(), sysy::AstScope::exitBlock(), sysy::ast::FLOAT, SysYParser::FuncTypeContext::FLOAT(), SysYParser::FuncDefContext::funcFParams(), SysYParser::FuncDefContext::funcType(), sysy::AstScope::getCurrentPtr(), SysYParser::FuncDefContext::Ident(), sysy::ast::INT, SysYParser::FuncTypeContext::INT(), PrintMsg, sysy::ast::VOID, and SysYParser::FuncTypeContext::VOID().
visitFuncFParam()
antlrcpp::Any sysy::SysYVisitor::visitFuncFParam (SysYParser::FuncFParamContext * ctx) override virtual
Returns
return type is FuncParamNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::FuncFParamContext::bType(), ErrorMsg, SysYParser::FuncFParamContext::exp(), sysy::ast::FLOAT, SysYParser::BTypeContext::FLOAT(), SysYParser::FuncFParamContext::Ident(), sysy::ast::INT, SysYParser::BTypeContext::INT(), SysYParser::FuncFParamContext::LSBRA(), and PrintMsg.
visitFuncFParams()
antlrcpp::Any sysy::SysYVisitor::visitFuncFParams (SysYParser::FuncFParamsContext * ctx) override virtual
Returns
return type is FuncParamListNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::FuncFParamsContext::funcFParam(), and PrintMsg.
visitFuncRParams()
antlrcpp::Any sysy::SysYVisitor::visitFuncRParams (SysYParser::FuncRParamsContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitFuncType()
antlrcpp::Any sysy::SysYVisitor::visitFuncType (SysYParser::FuncTypeContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitInitVal()
antlrcpp::Any sysy::SysYVisitor::visitInitVal (SysYParser::InitValContext * ctx) override virtual
Returns
return type is InitValNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::depth, SysYParser::InitValContext::exp(), SysYParser::InitValContext::initVal(), and PrintMsg.
visitIntConst()
antlrcpp::Any sysy::SysYVisitor::visitIntConst (SysYParser::IntConstContext * ctx) override virtual
Returns
return type is int
Reimplemented from SysYParserBaseVisitor.
References SysYParser::IntConstContext::DEC(), ErrorMsg, SysYParser::IntConstContext::HEX(), SysYParser::IntConstContext::OCT(), PrintMsg, strDec(), strHex(), and strOct().
visitLAndExp()
antlrcpp::Any sysy::SysYVisitor::visitLAndExp (SysYParser::LAndExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::ast::Immediate::computeAssign(), SysYParser::LAndExpContext::eqExp(), sysy::ast::NumberNode::immediate, sysy::ast::INT, SysYParser::LAndExpContext::lAndExp(), PrintMsg, and sysy::ast::ROP_AND.
visitLOrExp()
antlrcpp::Any sysy::SysYVisitor::visitLOrExp (SysYParser::LOrExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::ast::Immediate::computeAssign(), sysy::ast::NumberNode::immediate, sysy::ast::INT, SysYParser::LOrExpContext::lAndExp(), SysYParser::LOrExpContext::lOrExp(), PrintMsg, and sysy::ast::ROP_OR.
visitLVal()
antlrcpp::Any sysy::SysYVisitor::visitLVal (SysYParser::LValContext * ctx) override virtual
Returns
return type is LvalNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::LValContext::exp(), sysy::AstScope::getCurrentPtr(), SysYParser::LValContext::Ident(), and PrintMsg.
visitMulExp()
antlrcpp::Any sysy::SysYVisitor::visitMulExp (SysYParser::MulExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::ast::BOP_DIV, sysy::ast::BOP_MOD, sysy::ast::BOP_MUL, sysy::ast::Immediate::computeAssign(), SysYParser::MulExpContext::DIV(), sysy::ast::NumberNode::immediate, SysYParser::MulExpContext::MUL(), SysYParser::MulExpContext::mulExp(), PrintMsg, sysy::ast::ExprNode::type, and SysYParser::MulExpContext::unaryExp().
visitNumber()
antlrcpp::Any sysy::SysYVisitor::visitNumber (SysYParser::NumberContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitPrimaryExp()
antlrcpp::Any sysy::SysYVisitor::visitPrimaryExp (SysYParser::PrimaryExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::cnt, ErrorMsg, SysYParser::PrimaryExpContext::exp(), sysy::ast::FLOAT, SysYParser::NumberContext::floatConst(), sysy::AstScope::getCurrentPtr(), sysy::ast::Immediate::getType(), sysy::ast::INT, SysYParser::NumberContext::intConst(), SysYParser::PrimaryExpContext::lVal(), sysy::name, SysYParser::PrimaryExpContext::number(), and PrintMsg.
visitRelExp()
antlrcpp::Any sysy::SysYVisitor::visitRelExp (SysYParser::RelExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::RelExpContext::addExp(), sysy::ast::Immediate::computeAssign(), SysYParser::RelExpContext::GRT(), sysy::ast::NumberNode::immediate, sysy::ast::INT, SysYParser::RelExpContext::LEQ(), SysYParser::RelExpContext::LES(), PrintMsg, SysYParser::RelExpContext::relExp(), sysy::ast::ROP_GEQ, sysy::ast::ROP_GRT, sysy::ast::ROP_LEQ, sysy::ast::ROP_LES, and sysy::type.
visitStmt()
antlrcpp::Any sysy::SysYVisitor::visitStmt (SysYParser::StmtContext * ctx) override virtual
Returns
return type is StmtNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::StmtContext::AGN(), SysYParser::StmtContext::block(), SysYParser::StmtContext::BREAK(), SysYParser::StmtContext::cond(), SysYParser::StmtContext::CONTINUE(), SysYParser::StmtContext::exp(), SysYParser::StmtContext::FOR(), SysYParser::StmtContext::IF(), SysYParser::StmtContext::lVal(), PrintMsg, SysYParser::StmtContext::RETURN(), SysYParser::StmtContext::stmt(), SysYParser::StmtContext::stmt_in(), SysYParser::StmtContext::varDecl_in(), and SysYParser::StmtContext::WHILE().
visitStmt_in()
antlrcpp::Any sysy::SysYVisitor::visitStmt_in (SysYParser::Stmt_inContext * ctx) override virtual
Returns
return type is StmtNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::Stmt_inContext::exp(), SysYParser::Stmt_inContext::lVal(), and PrintMsg.
visitUnaryExp()
antlrcpp::Any sysy::SysYVisitor::visitUnaryExp (SysYParser::UnaryExpContext * ctx) override virtual
Returns
return type is ExprNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::UnaryOpContext::ADD(), sysy::ast::Immediate::computeAssign(), SysYParser::UnaryExpContext::funcRParams(), sysy::AstScope::getCurrentPtr(), sysy::Line::getInstance(), SysYParser::UnaryExpContext::Ident(), sysy::ast::INT, SysYParser::UnaryOpContext::NOT(), SysYParser::UnaryExpContext::primaryExp(), PrintMsg, SysYParser::FuncRParamsContext::STRING(), SysYParser::UnaryOpContext::SUB(), sysy::ast::Immediate::type, SysYParser::UnaryExpContext::unaryExp(), SysYParser::UnaryExpContext::unaryOp(), sysy::ast::UOP_ADD, sysy::ast::UOP_NOT, and sysy::ast::UOP_SUB.
visitUnaryOp()
antlrcpp::Any sysy::SysYVisitor::visitUnaryOp (SysYParser::UnaryOpContext * ctx) override virtual
Reimplemented from SysYParserBaseVisitor.
visitVarDecl()
antlrcpp::Any sysy::SysYVisitor::visitVarDecl (SysYParser::VarDeclContext * ctx) override virtual
Returns
return VarDeclNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::VarDeclContext::bType(), sysy::ast::FLOAT, SysYParser::BTypeContext::FLOAT(), sysy::AstScope::getCurrentPtr(), sysy::ast::INT, SysYParser::BTypeContext::INT(), PrintMsg, and SysYParser::VarDeclContext::varDef().
visitVarDecl_in()
antlrcpp::Any sysy::SysYVisitor::visitVarDecl_in (SysYParser::VarDecl_inContext * ctx) override virtual
Returns
return type is VarDeclNode*
Reimplemented from SysYParserBaseVisitor.
References SysYParser::VarDecl_inContext::bType(), sysy::ast::FLOAT, SysYParser::BTypeContext::FLOAT(), sysy::AstScope::getCurrentPtr(), sysy::ast::INT, SysYParser::BTypeContext::INT(), PrintMsg, and SysYParser::VarDecl_inContext::varDef().
visitVarDef()
antlrcpp::Any sysy::SysYVisitor::visitVarDef (SysYParser::VarDefContext * ctx) override virtual
Returns
return type is VarDefNode*
Reimplemented from SysYParserBaseVisitor.
References sysy::cnt, SysYParser::VarDefContext::constExp(), sysy::dims, ErrorMsg, SysYParser::VarDefContext::Ident(), SysYParser::VarDefContext::initVal(), and PrintMsg.
Member Data Documentation
parser
SysYParser& sysy::SysYVisitor::parser protected
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYVisitor.h
lib/Frontend/SysYVisitor.cpp