Diana: sysy::ir::Module Class Reference
sysy::ir::Module Class Reference
#include <Module.h>
Public Member Functions
void registerFunc (const std::string &name, std::list< Function * >::iterator iter)
Function * getFunction (const std::string &name)
Static Public Member Functions
static Module & getInstance ()
Public Attributes
std::vector< GlobalValue * > __globalValue
std::list< Function * > __function
Private Attributes
std::unordered_map< std::string, std::list< Function * >::iterator > nameFunc
Member Function Documentation
getFunction()
Function * sysy::ir::Module::getFunction (const std::string & name)
References __function, sysy::name, and nameFunc.
Referenced by sysy::ir::emitInitial(), and sysy::ir::LoopParallel::runOnLoop().
getInstance()
static Module& sysy::ir::Module::getInstance () inline static
Referenced by sysy::ir::GlobalValue::Create(), sysy::ir::IRBuilder::CreateMemCpyInline(), sysy::ir::emitInitial(), sysy::ir::emitIR(), sysy::ir::Function::Function(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::globalInit(), sysy::ir::irEmit(), sysy::mc::Module::Module(), and sysy::ir::LoopParallel::runOnLoop().
registerFunc()
void sysy::ir::Module::registerFunc (const std::string & name, std::list< Function * >::iterator iter) inline
References sysy::name, and nameFunc.
Member Data Documentation
__function
std::list<Function*> sysy::ir::Module::__function
Referenced by sysy::ir::dumpIR(), sysy::ir::IPDCE::eraseAllUnuseReturn(), getFunction(), sysy::ir::llFileGen(), sysy::mc::Module::Module(), sysy::ir::IPAnalysis::run(), sysy::ir::UnsetSSA::run(), sysy::ir::LoaclDCE::run(), sysy::ir::LocalGCM::run(), sysy::ir::LocalGVN::run(), sysy::ir::FunctionInline::run(), sysy::ir::ScalarPass::run(), sysy::ir::SSASet::run(), sysy::ir::LinearScalarPass::run(), sysy::ir::LoopVariablePass::run(), and sysy::ir::LoopEarlyPass::run().
__globalValue
std::vector<GlobalValue*> sysy::ir::Module::__globalValue
Referenced by sysy::ir::GlobalValue::Create(), sysy::ir::dumpIR(), sysy::ir::llFileGen(), and sysy::mc::Module::Module().
nameFunc
std::unordered_map<std::string, std::list<Function*>::iterator> sysy::ir::Module::nameFunc private
Referenced by getFunction(), and registerFunc().
The documentation for this class was generated from the following files:
include/sysy/IR/Module.h
lib/IR/Module.cpp