Diana: SysYParser::BTypeContext Class Reference
SysYParser::BTypeContext Class Reference
#include <SysYParser.h>
Public Member Functions
BTypeContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * INT ()
antlr4::tree::TerminalNode * FLOAT ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
BTypeContext()
SysYParser::BTypeContext::BTypeContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::BTypeContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
FLOAT()
tree::TerminalNode * SysYParser::BTypeContext::FLOAT ()
References SysYParser::FLOAT.
Referenced by sysy::SysYVisitor::visitConstDecl(), sysy::SysYVisitor::visitFuncFParam(), sysy::SysYVisitor::visitVarDecl(), and sysy::SysYVisitor::visitVarDecl_in().
getRuleIndex()
size_t SysYParser::BTypeContext::getRuleIndex () const override virtual
References SysYParser::RuleBType.
INT()
tree::TerminalNode * SysYParser::BTypeContext::INT ()
References SysYParser::INT.
Referenced by sysy::SysYVisitor::visitConstDecl(), sysy::SysYVisitor::visitFuncFParam(), sysy::SysYVisitor::visitVarDecl(), and sysy::SysYVisitor::visitVarDecl_in().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp