Diana: SysYParser::RelExpContext Class Reference
SysYParser::RelExpContext Class Reference
#include <SysYParser.h>
Public Member Functions
RelExpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
AddExpContext * addExp ()
RelExpContext * relExp ()
antlr4::tree::TerminalNode * LES ()
antlr4::tree::TerminalNode * GRT ()
antlr4::tree::TerminalNode * LEQ ()
antlr4::tree::TerminalNode * GEQ ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
RelExpContext()
SysYParser::RelExpContext::RelExpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::RelExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
addExp()
SysYParser::AddExpContext * SysYParser::RelExpContext::addExp ()
Referenced by sysy::SysYVisitor::visitRelExp().
GEQ()
tree::TerminalNode * SysYParser::RelExpContext::GEQ ()
References SysYParser::GEQ.
getRuleIndex()
size_t SysYParser::RelExpContext::getRuleIndex () const override virtual
References SysYParser::RuleRelExp.
GRT()
tree::TerminalNode * SysYParser::RelExpContext::GRT ()
References SysYParser::GRT.
Referenced by sysy::SysYVisitor::visitRelExp().
LEQ()
tree::TerminalNode * SysYParser::RelExpContext::LEQ ()
References SysYParser::LEQ.
Referenced by sysy::SysYVisitor::visitRelExp().
LES()
tree::TerminalNode * SysYParser::RelExpContext::LES ()
References SysYParser::LES.
Referenced by sysy::SysYVisitor::visitRelExp().
relExp()
SysYParser::RelExpContext * SysYParser::RelExpContext::relExp ()
Referenced by sysy::SysYVisitor::visitRelExp().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp