Diana: sysy::ir::IdomGen Class Reference
sysy::ir::IdomGen Class Reference
#include <DomInfo.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void getDfnum (Function *func)
void compress (BasicBlock *v)
BasicBlock * eval (BasicBlock *v)
void link (BasicBlock *pre, BasicBlock *now)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
compress()
void sysy::ir::IdomGen::compress (BasicBlock * v) private
References sysy::ir::ancenstor, sysy::ir::best, and sysy::ir::semi.
Referenced by eval().
eval()
BasicBlock * sysy::ir::IdomGen::eval (BasicBlock * v) private
References sysy::ir::ancenstor, sysy::ir::best, compress(), and sysy::ir::semi.
Referenced by run().
getDfnum()
void sysy::ir::IdomGen::getDfnum (Function * func) private
References sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::dfnumVertex, sysy::ir::Function::getBasicBlockList(), and sysy::ir::Function::getEntryBlock().
Referenced by run().
getName()
std::string sysy::ir::IdomGen::getName () override virtual
Implements sysy::Pass< Opt >.
link()
void sysy::ir::IdomGen::link (BasicBlock * pre, BasicBlock * now) private
References sysy::ir::ancenstor, sysy::ir::best, sysy::ir::child, sysy::ir::rank, and sysy::ir::semi.
Referenced by run().
run()
void sysy::ir::IdomGen::run (Function * func) override
References sysy::ir::best, sysy::ir::bucket, sysy::ir::clearIdomAll(), sysy::ir::dfnumVertex, eval(), getDfnum(), sysy::ir::Function::getEntryBlock(), link(), sysy::ir::parent, sysy::ir::rank, sysy::ir::semi, and sysy::ir::BasicBlock::setIdom().
The documentation for this class was generated from the following files:
include/sysy/Analysis/DomInfo.h
lib/Analysis/DomInfo.cpp