Diana: sysy::ast::UnaryExprNode Class Reference
sysy::ast::UnaryExprNode Class Reference
#include <Ast.h>
Public Member Functions
UnaryExprNode (AstType _type, UnaryOp _op, std::unique_ptr< ExprNode > _unaryExpr)
~UnaryExprNode ()
std::string getSignature () const override
Public Member Functions inherited from sysy::ast::ExprNode
ExprNode (AstKind _kind, AstType _type)
~ExprNode ()
void setImmediate (Immediate _immediate)
bool ready ()
Public Member Functions inherited from sysy::ast::AstNode
AstNode (AstKind _kind)
virtual ~AstNode ()
void setParent (AstNode *_parent)
void addChildren (AstNode *_children)
std::vector< AstNode * > & getChildren ()
const AstNode * getParent () const
AstNode * getParent ()
const AstKind & getKind () const
FuncDefNode * getParentFuction () const
Static Public Member Functions
static bool classof (const AstNode *c)
LLVM style RTTI.
Static Public Member Functions inherited from sysy::ast::ExprNode
static bool classof (const AstNode *c)
LLVM style RTTI.
Public Attributes
UnaryOp op
std::unique_ptr< ExprNode > expr
Public Attributes inherited from sysy::ast::ExprNode
AstType type
Public Attributes inherited from sysy::ast::AstNode
AstKind kind
AstNode * parent
std::vector< AstNode * > children
Additional Inherited Members
Public Types inherited from sysy::ast::AstNode
enum AstKind {
AST_compUnit, AST_decl, AST_constDecl, AST_constDef,
AST_varDecl, AST_varDef, AST_prototype, AST_initVal,
AST_funcDef, AST_funcParams, AST_funcParam, AST_stmt,
AST_block, AST_assignStmt, AST_expStmt, AST_ifStmt,
AST_forStmt, AST_whileStmt, AST_breakStmt, AST_continueStmt,
AST_returnStmt, AST_exp, AST_cond, AST_mulExp,
AST_addExp, AST_relExp, AST_eqExp, AST_lAndExp,
AST_lOrExp, AST_unaryExp, AST_binaryExp, AST_functCallExp,
AST_primaryExp, AST_lVal, AST_ConditionNumber, AST_Number,
AST_EOF, AST_Undefined
}
Constructor & Destructor Documentation
UnaryExprNode()
sysy::ast::UnaryExprNode::UnaryExprNode (AstType _type, UnaryOp _op, std::unique_ptr< ExprNode > _unaryExpr)
References SET_IT_PARENT.
~UnaryExprNode()
sysy::ast::UnaryExprNode::~UnaryExprNode ()
References expr.
Member Function Documentation
classof()
static bool sysy::ast::UnaryExprNode::classof (const AstNode * c) inline static
LLVM style RTTI.
References sysy::ast::AstNode::AST_unaryExp, and sysy::ast::AstNode::getKind().
getSignature()
std::string sysy::ast::UnaryExprNode::getSignature () const override virtual
Reimplemented from sysy::ast::ExprNode.
References expr, sysy::ast::getSignature(), op, subLine(), and sysy::ast::ExprNode::type.
Member Data Documentation
expr
std::unique_ptr<ExprNode> sysy::ast::UnaryExprNode::expr
Referenced by getSignature(), sysy::ir::irEmit(), and ~UnaryExprNode().
op
UnaryOp sysy::ast::UnaryExprNode::op
Referenced by getSignature(), and sysy::ir::irEmit().
The documentation for this class was generated from the following files:
include/sysy/Frontend/Ast.h
lib/Frontend/Ast.cpp
lib/Frontend/AstDump.cpp