Diana: sysy::ir::UndefValue Class Reference
sysy::ir::UndefValue Class Reference
#include <Value.h>
Public Member Functions
UndefValue ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static UndefValue * Create ()
Additional Inherited Members
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
UndefValue()
sysy::ir::UndefValue::UndefValue () inline
Referenced by Create().
Member Function Documentation
Create()
UndefValue * sysy::ir::UndefValue::Create () static
References UndefValue().
Referenced by sysy::ir::SimplifyCFG::addEdge(), sysy::ir::MemorySSA::DefUseCompute(), sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::Memory2Reg::renameAllocaInBB(), sysy::ir::MemorySSA::renameLoadOfArrayInBB(), sysy::ir::MemorySSA::renameLoadOfGVInBB(), sysy::ir::MemorySSA::renameStoreOfArrayInBB(), sysy::ir::MemorySSA::renameStoreOfGVInBB(), sysy::ir::Memory2Reg::run(), and sysy::ir::MemorySSA::UseDefCompute().
getSignature()
std::string sysy::ir::UndefValue::getSignature () inline override virtual
Implements sysy::ir::Value.
The documentation for this class was generated from the following files:
include/sysy/IR/Value.h
lib/IR/Value.cpp