Diana: sysy::ir::LoopParallel Class Reference
sysy::ir::LoopParallel Class Reference
#include <LoopParallel.h>
Public Member Functions
LoopParallel ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
bool isParallelizable (Loop *loop)
void runOnLoop (Loop *loop)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
LoopParallel()
sysy::ir::LoopParallel::LoopParallel ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
getName()
std::string sysy::ir::LoopParallel::getName () inline override virtual
Implements sysy::Pass< Opt >.
isParallelizable()
bool sysy::ir::LoopParallel::isParallelizable (Loop * loop) private
References sysy::ir::SCEV::at(), sysy::ir::Loop::getExitBlocks(), sysy::ir::Loop::getExitingBlocks(), sysy::ir::Loop::getIndexEnd(), sysy::ir::Loop::getIndexPhi(), sysy::ir::Loop::getLatchBlock(), sysy::ir::Loop::getLoopBasicBlocks(), sysy::ir::getOriginArray(), sysy::ir::Loop::getSCEV(), sysy::ir::Loop::getTripCount(), sysy::ir::GlobalValue::getValueType(), sysy::ir::Loop::hasSCEV(), sysy::ir::Type::isArrayTy(), and sysy::ir::Loop::isLoopInvariant().
Referenced by runOnLoop().
run()
void sysy::ir::LoopParallel::run (Function * func) override
References sysy::ir::Value::getName(), sysy::ir::Function::getTopLoops(), sysy::ir::Function::isRecursive(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::LoopParallel::runOnLoop (Loop * loop) private
References sysy::ir::Instruction::Add, sysy::ir::ConstantInt::get(), sysy::ir::Loop::getExitBlocks(), sysy::ir::Module::getFunction(), sysy::ir::Loop::getIndexCondInstr(), sysy::ir::Loop::getIndexEnd(), sysy::ir::Loop::getIndexPhi(), sysy::ir::Module::getInstance(), sysy::ir::Type::getInt32Ty(), sysy::ir::Loop::getPreHeader(), sysy::ir::Loop::getSCEV(), isParallelizable(), sysy::ir::Instruction::Mul, sysy::ir::PhiInstruction::removeIncomingByBB(), sysy::ir::User::replaceOperandWith(), sysy::ir::Instruction::SDiv, and sysy::ir::Instruction::Sub.
Referenced by run().
The documentation for this class was generated from the following files:
include/sysy/Transform/Loop/LoopParallel.h
lib/Transform/Loop/LoopParallel.cpp