Diana: sysy::ir::Value Class Reference
sysy::ir::Value Class Reference abstract
#include <Value.h>
Public Member Functions
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
virtual std::string getSignature ()=0
Protected Attributes
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
Value()
sysy::ir::Value::Value (Type * _type, std::string _name = "") inline
Member Function Documentation
addUse()
void sysy::ir::Value::addUse (std::shared_ptr< Use > use) inline
References uses.
Referenced by sysy::ir::User::addOperand(), sysy::ir::User::replaceOperand(), and sysy::ir::User::replaceOperandWith().
getName()
std::string sysy::ir::Value::getName () inline
References name.
Referenced by sysy::ir::LSR::eraseSingleMul(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::getLabel(), sysy::ir::IRCopier::getLoopCopy(), sysy::ir::GlobalValue::getSignature(), sysy::ir::CallInstruction::getSignature(), sysy::ir::Function::getSignature(), sysy::ir::getVariable(), sysy::ir::LCSSA::insertLoopClosedPhi(), sysy::ir::irEmit(), sysy::ir::MemorySSA::queueLoadMemPhi(), sysy::ir::Memory2Reg::queuePhi(), sysy::ir::MemorySSA::queueStoreMemPhi(), sysy::ir::LoopParallel::run(), sysy::ir::ADCE::run(), sysy::ir::LCSSA::run(), sysy::ir::LSR::run(), sysy::ir::ScalarEvolution::run(), sysy::ir::GCM::run(), sysy::ir::DCE::run(), sysy::ir::SimplifyCFG::run(), sysy::ir::ScalarEvolutionClean::run(), sysy::ir::GVN::run(), sysy::ir::MemorySSA::run(), and sysy::ir::ClearMemorySSA::run().
getSignature()
virtual std::string sysy::ir::Value::getSignature () pure virtual
Implemented in sysy::ir::Instruction, sysy::ir::MoveInstruction, sysy::ir::DeadInstruction, sysy::ir::MemPhiInstruction, sysy::ir::PhiInstruction, sysy::ir::AllocaInstruction, sysy::ir::GEPInstruction, sysy::ir::LoadInstruction, sysy::ir::StoreInstruction, sysy::ir::RetInstruction, sysy::ir::ConstantString, sysy::ir::BrInstruction, sysy::ir::ConstantArray, sysy::ir::BasicBlock, sysy::ir::Function, sysy::ir::CallInstruction, sysy::ir::ConstantFP, sysy::ir::UndefValue, sysy::ir::ConstantInt, sysy::ir::UnaryInstruction, sysy::ir::Function::Arg, sysy::ir::GlobalValue, and sysy::ir::BinaryInstrcution.
Referenced by sysy::ir::GlobalValue::getSignature().
getType()
Type* sysy::ir::Value::getType () inline
References type.
Referenced by sysy::mc::Function::analyseFunc(), sysy::ir::createGlobalInit(), sysy::ir::IRBuilder::CreateMemCpyInline(), sysy::ir::IRBuilder::CreateNot(), sysy::ir::emitInitial(), sysy::mc::Function::get_reg(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::getPtrPtr(), sysy::ir::BinaryInstrcution::getSignature(), sysy::ir::UnaryInstruction::getSignature(), sysy::ir::CallInstruction::getSignature(), sysy::ir::Function::getSignature(), sysy::ir::BrInstruction::getSignature(), sysy::ir::RetInstruction::getSignature(), sysy::ir::StoreInstruction::getSignature(), sysy::ir::LoadInstruction::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), sysy::ir::MemPhiInstruction::getSignature(), sysy::ir::GlobalValue::getValueType(), sysy::ir::LCSSA::insertLoopClosedPhi(), sysy::mc::Block::instSelection(), sysy::ir::irEmit(), sysy::ir::Memory2Reg::isAllocaPromotable(), sysy::ir::RetInstruction::isVoidRet(), sysy::ir::operator*(), sysy::ir::operator+(), sysy::ir::operator-(), sysy::ir::InstructionCombine::visitAdd(), and sysy::ir::InstructionCombine::visitSub().
getUses()
std::list<std::shared_ptr<Use> >& sysy::ir::Value::getUses () inline
References uses.
Referenced by sysy::ir::Memory2Reg::allocaSimplify(), sysy::ir::Memory2Reg::analysisAlloca(), sysy::ir::GVN::doPerInstr(), sysy::ir::LCSSA::insertLoopClosedPhi(), sysy::ir::Memory2Reg::isAllocaPromotable(), sysy::ir::ScalarEvolution::registerBIV(), sysy::ir::DCE::removeUselessStore(), replaceAllUseWith(), and sysy::ir::GCM::schduleLate().
removeAllUseWith()
void sysy::ir::Value::removeAllUseWith ()
References replaceAllUseWith().
Referenced by sysy::ir::Memory2Reg::allocaSimplify().
removeUse()
void sysy::ir::Value::removeUse (const std::shared_ptr< Use > & use) inline
References uses.
removeUseIf()
void sysy::ir::Value::removeUseIf (std::function< bool(std::shared_ptr< Use >)> func) inline
References uses.
replaceAllUseWith()
void sysy::ir::Value::replaceAllUseWith (Value * value)
References getUses().
Referenced by sysy::ir::LSR::eraseSingleMul(), removeAllUseWith(), sysy::ir::Memory2Reg::renameAllocaInBB(), sysy::ir::replace(), and sysy::ir::LoopUnrollAll::runOnLoop().
setName()
void sysy::ir::Value::setName (std::string _name) inline
References name.
setType()
void sysy::ir::Value::setType (Type * _type) inline
References type.
Member Data Documentation
name
std::string sysy::ir::Value::name protected
Referenced by sysy::ir::Function::Create(), sysy::ir::BasicBlock::Create(), sysy::ir::Function::Function(), getName(), sysy::ir::Function::Arg::getSignature(), sysy::ir::Function::Arg::setName(), and setName().
type
Type* sysy::ir::Value::type protected
Referenced by sysy::ir::Function::Create(), sysy::ir::Function::Function(), sysy::ir::Function::Arg::getSignature(), getType(), and setType().
uses
std::list<std::shared_ptr<Use> > sysy::ir::Value::uses protected
Referenced by addUse(), getUses(), removeUse(), and removeUseIf().
The documentation for this class was generated from the following files:
include/sysy/IR/Value.h
lib/IR/Value.cpp