Diana: sysy::ir::ConstantArray Class Reference
sysy::ir::ConstantArray Class Reference
#include <Constant.h>
Public Member Functions
ConstantArray (std::vector< Constant * > initial, ArrayType *_type)
bool isZero () override
Constant * getValue (size_t idx)
size_t size ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Constant
Constant (Type *_type, std::vector< Value * > _operands)
Constant (Type *_type)
void setZero ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static ConstantArray * get (ArrayType *_type, std::vector< Constant * > initial)
static ConstantArray * getZero (ArrayType *_type)
Static Public Member Functions inherited from sysy::ir::Constant
static Constant * getZero (Type *_type)
static Constant * getString (const std::string &str)
Private Attributes
std::vector< Constant * > items
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::Constant
bool zeroinitializer = false
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
ConstantArray()
sysy::ir::ConstantArray::ConstantArray (std::vector< Constant * > initial, ArrayType * _type) inline
References sysy::ir::User::operands.
Referenced by get().
Member Function Documentation
get()
ConstantArray * sysy::ir::ConstantArray::get (ArrayType * _type, std::vector< Constant * > initial) static
References ConstantArray().
Referenced by sysy::ir::getConstantArray(), and getZero().
getSignature()
std::string sysy::ir::ConstantArray::getSignature () override virtual
Implements sysy::ir::Value.
References items, and sysy::ir::Constant::zeroinitializer.
getValue()
Constant* sysy::ir::ConstantArray::getValue (size_t idx) inline
References items.
getZero()
ConstantArray * sysy::ir::ConstantArray::getZero (ArrayType * _type) static
References get(), and sysy::ir::Constant::setZero().
Referenced by sysy::ir::getConstantArray(), and sysy::ir::Constant::getZero().
isZero()
bool sysy::ir::ConstantArray::isZero () inline override virtual
Implements sysy::ir::Constant.
References items, and sysy::ir::Constant::zeroinitializer.
size()
size_t sysy::ir::ConstantArray::size () inline
References items.
Member Data Documentation
items
std::vector<Constant*> sysy::ir::ConstantArray::items private
Referenced by getSignature(), getValue(), isZero(), and size().
The documentation for this class was generated from the following files:
include/sysy/IR/Constant.h
lib/IR/Constant.cpp
lib/IR/IRDump.cpp