Diana: sysy::ir::FunctionInline Class Reference
sysy::ir::FunctionInline Class Reference
#include <FunctionInline.h>
Public Member Functions
FunctionInline ()
void run (Module *moudle) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void inlineAtCall (CallInst *call)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
FunctionInline()
sysy::ir::FunctionInline::FunctionInline ()
References sysy::Pass< Opt >::getRelated().
Member Function Documentation
getName()
std::string sysy::ir::FunctionInline::getName () inline override virtual
Implements sysy::Pass< Opt >.
inlineAtCall()
void sysy::ir::FunctionInline::inlineAtCall (CallInst * call) private
References sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::BasicBlock::Create(), sysy::ir::dumpFunction(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::CallInstruction::getCallee(), sysy::ir::Function::getEntryBlock(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::BasicBlock::getParent(), sysy::ir::BasicBlock::getPredecessor(), sysy::ir::Instruction::getRank(), PrintMsg, and sysy::ir::SimplifyCFG::redirectEdge().
run()
void sysy::ir::FunctionInline::run (Module * moudle) override
References sysy::ir::Module::__function, and PrintMsg.
The documentation for this class was generated from the following files:
include/sysy/Transform/IPO/FunctionInline.h
lib/Transform/IPO/FunctionInline.cpp