Diana: sysy::ir::ArrayType Class Reference
sysy::ir::ArrayType Class Reference
#include <Type.h>
Public Member Functions
ArrayType (Type *_inner, unsigned _size)
ArrayType ()
Type * getInnerType () override
std::string getSignature () override
unsigned getSize ()
size_t getAllocatedSize () override
Public Member Functions inherited from sysy::ir::Type
bool isFloatTy ()
bool isVoidTy ()
bool isLabelTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned width)
bool isFunctionTy ()
bool isPointerTy ()
bool isVectorTy ()
bool isArrayTy ()
bool isUndefTy ()
Static Public Member Functions
static ArrayType * get (Type *inner, unsigned size)
Static Public Member Functions inherited from sysy::ir::Type
static Type * getFloatTy ()
static Type * getVoidTy ()
static Type * getUndefTy ()
static Type * getFunctionTy (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static Type * getLabelTy ()
static Type * getIntegerTy (unsigned width)
static Type * getInt1Ty ()
static Type * getInt32Ty ()
static Type * getInt8Ty ()
static Type * getPointerTy (Type *inner)
static Type * getArrayTy (Type *inner, unsigned size)
static Type * getInt8PtrTy ()
static Type * getInt32PtrTy ()
static Type * getFloatPtrTy ()
Private Attributes
Type * inner
unsigned size
Additional Inherited Members
Public Types inherited from sysy::ir::Type
enum TypeID {
FloatTyID = 0, VoidTyID, LabelTyID, IntegerTyID,
FunctionTyID, PointerTyID, ArrayTyID, FixedVectorTyID,
ScalableVectorTyID, UndefTyID
}
Protected Member Functions inherited from sysy::ir::Type
Type (TypeID id)
TypeID getTypeId ()
unsigned getSize ()
Constructor & Destructor Documentation
ArrayType() [1/2]
sysy::ir::ArrayType::ArrayType (Type * _inner, unsigned _size) inline
ArrayType() [2/2]
sysy::ir::ArrayType::ArrayType () inline
Referenced by get().
Member Function Documentation
get()
ArrayType * sysy::ir::ArrayType::get (Type * inner, unsigned size) static
References ArrayType(), sysy::ir::Context::getInstance(), inner, size, and sysy::type.
Referenced by sysy::ir::CreateEntryBlockAlloca(), sysy::ir::createGlobal(), sysy::ir::Type::getArrayTy(), and sysy::ir::irEmit().
getAllocatedSize()
size_t sysy::ir::ArrayType::getAllocatedSize () override virtual
Implements sysy::ir::Type.
References sysy::type.
getInnerType()
Type* sysy::ir::ArrayType::getInnerType () inline override virtual
Implements sysy::ir::Type.
References inner.
getSignature()
std::string sysy::ir::ArrayType::getSignature () inline override virtual
Implements sysy::ir::Type.
References sysy::ir::Type::getSignature(), inner, and size.
getSize()
unsigned sysy::ir::ArrayType::getSize () inline
References size.
Member Data Documentation
inner
Type* sysy::ir::ArrayType::inner private
Referenced by get(), getInnerType(), and getSignature().
size
unsigned sysy::ir::ArrayType::size private
Referenced by get(), getSignature(), and getSize().
The documentation for this class was generated from the following files:
include/sysy/IR/Type.h
lib/IR/Type.cpp