Diana: sysy::ir::DCE Class Reference
sysy::ir::DCE Class Reference
#include <DCE.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void removeUselessStore (BasicBlock *bb)
bool isUsefulInstr (Instruction *instr)
void findAliveCode (Instruction *instr)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
findAliveCode()
void sysy::ir::DCE::findAliveCode (Instruction * instr) private
References sysy::ir::AliveCode, and sysy::ir::User::getOprands().
getName()
std::string sysy::ir::DCE::getName () inline override virtual
Implements sysy::Pass< Opt >.
isUsefulInstr()
bool sysy::ir::DCE::isUsefulInstr (Instruction * instr) private
References sysy::ir::CallInstruction::isPureCall().
removeUselessStore()
void sysy::ir::DCE::removeUselessStore (BasicBlock * bb) private
References sysy::ir::BasicBlock::getInstructions(), sysy::ir::StoreInstruction::getPtr(), and sysy::ir::Value::getUses().
run()
void sysy::ir::DCE::run (Function * func) override
References sysy::ir::AliveCode, sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::Function::getEntryBlock(), sysy::ir::Value::getName(), and PrintMsg.
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/DCE.h
lib/Transform/Scalar/DCE.cpp