Diana: sysy::ir::ScalarEvolution Class Reference
sysy::ir::ScalarEvolution Class Reference
#include <SCEV.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void linkInstructionToSCEV (Loop *loop, BinaryInst *instr)
void runOnLoop (Loop *loop)
void findAndRegisterBIV (Loop *loop)
void registerBIV (Loop *loop, PhiInst *phi)
void BIV2SCEV (Loop *loop, PhiInst *phi, std::set< Value * > &adds, std::set< Value * > &subs)
Private Attributes
bool fixed
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
BIV2SCEV()
void sysy::ir::ScalarEvolution::BIV2SCEV (Loop * loop, PhiInst * phi, std::set< Value * > & adds, std::set< Value * > & subs) private
References sysy::ir::Instruction::Add, sysy::ir::Type::getInt32Ty(), sysy::ir::PhiInstruction::getPredecessors(), sysy::ir::ConstantInt::getZero(), sysy::ir::Loop::isLoopInvariant(), sysy::ir::Loop::registerSCEV(), and sysy::ir::Instruction::Sub.
Referenced by registerBIV().
findAndRegisterBIV()
void sysy::ir::ScalarEvolution::findAndRegisterBIV (Loop * loop) private
References sysy::ir::Loop::getHeader(), sysy::ir::Loop::isLoopInvariant(), and registerBIV().
Referenced by runOnLoop().
getName()
std::string sysy::ir::ScalarEvolution::getName () inline override virtual
Implements sysy::Pass< Opt >.
linkInstructionToSCEV()
void sysy::ir::ScalarEvolution::linkInstructionToSCEV (Loop * loop, BinaryInst * instr) private
References fixed, sysy::ir::Instruction::getKind(), sysy::ir::BinaryInstrcution::getLhs(), sysy::ir::BinaryInstrcution::getRhs(), sysy::ir::Loop::getSCEV(), sysy::ir::Loop::hasSCEV(), sysy::ir::Loop::isLoopInvariant(), and sysy::ir::Loop::registerSCEV().
Referenced by runOnLoop().
registerBIV()
void sysy::ir::ScalarEvolution::registerBIV (Loop * loop, PhiInst * phi) private
References sysy::ir::Instruction::Add, BIV2SCEV(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::Value::getUses(), sysy::ir::Loop::isLoopInvariant(), and sysy::ir::Instruction::Sub.
Referenced by findAndRegisterBIV().
run()
void sysy::ir::ScalarEvolution::run (Function * func) override
References sysy::ir::Value::getName(), sysy::ir::Function::getTopLoops(), PrintMsg, and runOnLoop().
runOnLoop()
void sysy::ir::ScalarEvolution::runOnLoop (Loop * loop) private
References sysy::ir::Loop::cleanSCEV(), findAndRegisterBIV(), fixed, sysy::ir::Loop::getICmpKind(), sysy::ir::Loop::getIndexEnd(), sysy::ir::Loop::getIndexPhi(), sysy::ir::Loop::getLoopBasicBlocks(), sysy::ir::Loop::getSCEV(), sysy::ir::Loop::getSubLoops(), sysy::ir::Loop::hasSCEV(), linkInstructionToSCEV(), and sysy::ir::Loop::setTripCount().
Referenced by run().
Member Data Documentation
fixed
bool sysy::ir::ScalarEvolution::fixed private
Referenced by linkInstructionToSCEV(), and runOnLoop().
The documentation for this class was generated from the following files:
include/sysy/Analysis/SCEV.h
lib/Analysis/SCEV.cpp