Diana: sysy::ir::FunctionVertify Class Reference
sysy::ir::FunctionVertify Class Reference
#include <Vertify.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
getName()
std::string sysy::ir::FunctionVertify::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::FunctionVertify::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::Function::getArgs(), and sysy::ir::Function::getEntryBlock().
The documentation for this class was generated from the following files:
include/sysy/Analysis/Vertify.h
lib/Analysis/Vertify.cpp