Diana: sysy::mc::Module Class Reference
sysy::mc::Module Class Reference
#include <Module.h>
Public Member Functions
std::vector< int > reg_allocate (RegAllocStat *stat)
Module (ir::Module *ir, int _argc)
void run (std::string file_name)
std::string gen_global ()
void gen_asm (std::string file_name)
Public Attributes
std::list< Function * > functions
std::vector< GlobalObject * > global_objects
bool data_flag = false
bool bss_flag = false
int argc
bool create_threads = false
std::map< int, GlobalObject * > float_map
std::map< ir::Function *, Function * > func_map
std::map< ir::GlobalValue *, GlobalObject * > global_map
std::map< GlobalObject *, ir::GlobalValue * > rev_global_map
Constructor & Destructor Documentation
Module()
sysy::mc::Module::Module (ir::Module * ir, int _argc)
References sysy::ir::Module::__function, sysy::ir::Module::__globalValue, argc, bss_flag, data_flag, func_map, functions, sysy::ir::Module::getInstance(), global_map, global_objects, sysy::mc::GlobalObject::is_zero, sysy::name, sysy::mc::GlobalObject::pushValue(), rev_global_map, and sysy::mc::GlobalObject::size.
Member Function Documentation
gen_asm()
void sysy::mc::Module::gen_asm (std::string file_name)
References create_threads, functions, gen_global(), and sysy::mc::gen_threads().
Referenced by run().
gen_global()
std::string sysy::mc::Module::gen_global ()
References bss_flag, data_flag, sysy::mc::GlobalObject::dec2hex(), and global_objects.
Referenced by gen_asm().
reg_allocate()
std::vector<int> sysy::mc::Module::reg_allocate (RegAllocStat * stat)
run()
void sysy::mc::Module::run (std::string file_name)
References sysy::mc::analyseType(), functions, gen_asm(), sysy::mc::merge_block(), sysy::mc::remove_bottom_to_top(), sysy::mc::remove_branch(), and sysy::mc::remove_multi_store().
Referenced by main().
Member Data Documentation
argc
int sysy::mc::Module::argc
Referenced by sysy::mc::Block::instSelection(), and Module().
bss_flag
bool sysy::mc::Module::bss_flag = false
Referenced by gen_global(), and Module().
create_threads
bool sysy::mc::Module::create_threads = false
Referenced by gen_asm(), and sysy::mc::Block::instSelection().
data_flag
bool sysy::mc::Module::data_flag = false
Referenced by gen_global(), sysy::mc::Function::get_reg(), and Module().
float_map
std::map<int, GlobalObject*> sysy::mc::Module::float_map
Referenced by sysy::mc::Function::get_reg().
func_map
std::map<ir::Function*, Function*> sysy::mc::Module::func_map
Referenced by sysy::mc::Block::instSelection(), and Module().
functions
std::list<Function*> sysy::mc::Module::functions
Referenced by gen_asm(), Module(), and run().
global_map
std::map<ir::GlobalValue*, GlobalObject*> sysy::mc::Module::global_map
Referenced by sysy::mc::Function::get_reg(), and Module().
global_objects
std::vector<GlobalObject*> sysy::mc::Module::global_objects
Referenced by sysy::mc::Function::analyseFunc(), gen_global(), sysy::mc::Function::get_reg(), and Module().
rev_global_map
std::map<GlobalObject*, ir::GlobalValue*> sysy::mc::Module::rev_global_map
Referenced by sysy::mc::Function::analyseFunc(), and Module().
The documentation for this class was generated from the following files:
include/sysy/Target/Module.h
lib/Target/MCModule.cpp