Diana: sysy::ir::ConstantInt Class Reference
sysy::ir::ConstantInt Class Reference
#include <Constant.h>
Public Member Functions
ConstantInt (Type *_type, int _value)
bool isZero () override
bool isOne ()
int getValue ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Constant
Constant (Type *_type, std::vector< Value * > _operands)
Constant (Type *_type)
void setZero ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static ConstantInt * get (Type *_type, int _value)
static ConstantInt * get (unsigned width, int _value)
static ConstantInt * getZero (Type *_type)
Static Public Member Functions inherited from sysy::ir::Constant
static Constant * getZero (Type *_type)
static Constant * getString (const std::string &str)
Private Attributes
int value
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::Constant
bool zeroinitializer = false
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
ConstantInt()
sysy::ir::ConstantInt::ConstantInt (Type * _type, int _value) inline
Referenced by get().
Member Function Documentation
get() [1/2]
ConstantInt * sysy::ir::ConstantInt::get (Type * _type, int _value) static
References ConstantInt().
Referenced by sysy::ir::BrInstruction::BrInstruction(), sysy::ir::constantFold(), sysy::ir::createGlobal(), sysy::ir::IRBuilder::CreateMemCpyInline(), sysy::ir::IRBuilder::CreateNeg(), sysy::ir::IRBuilder::CreateNot(), sysy::ir::GVN::doPerInstr(), sysy::ir::emitInitial(), sysy::ir::IPDCE::eraseAllUnuseReturn(), get(), sysy::ir::getConstantArray(), sysy::ir::getElementPtr(), sysy::ir::getIDX(), getZero(), sysy::ir::irEmit(), sysy::ir::operator*(), sysy::ir::operator+(), sysy::ir::operator-(), sysy::ir::CleanExitBasicBlock::run(), sysy::ir::LoopParallel::runOnLoop(), sysy::ir::BrInstruction::setUnconditional(), sysy::ir::simplifyInstruction(), sysy::ir::InstructionCombine::visitAdd(), and sysy::ir::InstructionCombine::visitSub().
get() [2/2]
ConstantInt * sysy::ir::ConstantInt::get (unsigned width, int _value) static
References ErrorMsg, get(), sysy::ir::Type::getInt1Ty(), sysy::ir::Type::getInt32Ty(), and sysy::ir::Type::getInt8Ty().
getSignature()
std::string sysy::ir::ConstantInt::getSignature () override virtual
Implements sysy::ir::Value.
References value.
getValue()
int sysy::ir::ConstantInt::getValue () inline
References value.
Referenced by sysy::ir::GVN::checkoutTable().
getZero()
ConstantInt * sysy::ir::ConstantInt::getZero (Type * _type) static
References get().
Referenced by sysy::ir::ScalarEvolution::BIV2SCEV(), sysy::ir::GVN::doPerInstr(), sysy::ir::AllocaInstruction::getSize(), and sysy::ir::Constant::getZero().
isOne()
bool sysy::ir::ConstantInt::isOne () inline
References value.
Referenced by sysy::ir::simplifyInstruction().
isZero()
bool sysy::ir::ConstantInt::isZero () inline override virtual
Implements sysy::ir::Constant.
References value.
Referenced by sysy::ir::simplifyInstruction().
Member Data Documentation
value
int sysy::ir::ConstantInt::value private
Referenced by getSignature(), getValue(), isOne(), and isZero().
The documentation for this class was generated from the following files:
include/sysy/IR/Constant.h
lib/IR/Constant.cpp
lib/IR/IRDump.cpp