Diana: sysy::ir::SimplifyCFG Class Reference
sysy::ir::SimplifyCFG Class Reference
#include <SimplifyCFG.h>
Public Member Functions
SimplifyCFG (bool after)
bool changed ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Static Public Member Functions
static void deleteEdge (BasicBlock *from, BasicBlock *to)
static void addEdge (BasicBlock *from, BasicBlock *to, BasicBlock *origion)
static void redirectEdge (BasicBlock *preFrom, BasicBlock *nowFrom, BasicBlock *to)
static void removeDeadBB (Function *func)
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Private Member Functions
bool uncondTheCondBr (BasicBlock *bb)
bool deleteEmptyBB (BasicBlock *bb)
bool mergeBB (BasicBlock *bb)
bool upperTheBranch (BasicBlock *bb)
bool simplifyPhi (BasicBlock *bb)
Private Attributes
bool isAfterLoopOpt
bool change
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Constructor & Destructor Documentation
SimplifyCFG()
sysy::ir::SimplifyCFG::SimplifyCFG (bool after)
Member Function Documentation
addEdge()
void sysy::ir::SimplifyCFG::addEdge (BasicBlock * from, BasicBlock * to, BasicBlock * origion) static
References sysy::ir::UndefValue::Create(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getPredecessor(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by deleteEmptyBB(), and upperTheBranch().
changed()
bool sysy::ir::SimplifyCFG::changed () inline
References change.
deleteEdge()
void sysy::ir::SimplifyCFG::deleteEdge (BasicBlock * from, BasicBlock * to) static
References sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getPredecessor(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by deleteEmptyBB(), mergeBB(), removeDeadBB(), uncondTheCondBr(), and upperTheBranch().
deleteEmptyBB()
bool sysy::ir::SimplifyCFG::deleteEmptyBB (BasicBlock * bb) private
References addEdge(), deleteEdge(), sysy::ir::BrInstruction::getCond(), sysy::ir::Function::getEntryBlock(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getParent(), sysy::ir::BasicBlock::getPredecessor(), isAfterLoopOpt, and sysy::ir::BasicBlock::isPreHeader().
Referenced by run().
getName()
std::string sysy::ir::SimplifyCFG::getName () inline override virtual
Implements sysy::Pass< Opt >.
mergeBB()
bool sysy::ir::SimplifyCFG::mergeBB (BasicBlock * bb) private
References deleteEdge(), sysy::ir::BrInstruction::getCond(), sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getSuccessor(), sysy::ir::BasicBlock::insertBack(), PrintMsg, and redirectEdge().
Referenced by run().
redirectEdge()
void sysy::ir::SimplifyCFG::redirectEdge (BasicBlock * preFrom, BasicBlock * nowFrom, BasicBlock * to) static
References sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getPredecessor(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by sysy::ir::FunctionInline::inlineAtCall(), and mergeBB().
removeDeadBB()
void sysy::ir::SimplifyCFG::removeDeadBB (Function * func) static
References sysy::ir::BasicBlock::BasicBlockDfs(), deleteEdge(), sysy::ir::Function::getBasicBlockList(), sysy::ir::Function::getEntryBlock(), sysy::ir::BasicBlock::getInstructions(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by sysy::ir::emitIR(), and run().
run()
void sysy::ir::SimplifyCFG::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfsPost(), change, deleteEmptyBB(), sysy::ir::dumpFunction(), sysy::ir::fixed, sysy::ir::Function::getEntryBlock(), sysy::ir::Value::getName(), mergeBB(), PrintMsg, removeDeadBB(), simplifyPhi(), uncondTheCondBr(), and upperTheBranch().
simplifyPhi()
bool sysy::ir::SimplifyCFG::simplifyPhi (BasicBlock * bb) private
References sysy::ir::BasicBlock::getInstructions(), and sysy::ir::BasicBlock::getPredecessor().
Referenced by run().
uncondTheCondBr()
bool sysy::ir::SimplifyCFG::uncondTheCondBr (BasicBlock * bb) private
References sysy::ir::cnt, deleteEdge(), sysy::ir::BasicBlock::getInstructions(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by run().
upperTheBranch()
bool sysy::ir::SimplifyCFG::upperTheBranch (BasicBlock * bb) private
References addEdge(), deleteEdge(), sysy::ir::BrInstruction::getCond(), and sysy::ir::BasicBlock::getInstructions().
Referenced by run().
Member Data Documentation
change
bool sysy::ir::SimplifyCFG::change private
Referenced by changed(), and run().
isAfterLoopOpt
bool sysy::ir::SimplifyCFG::isAfterLoopOpt private
Referenced by deleteEmptyBB().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/SimplifyCFG.h
lib/Transform/Utils/SimplifyCFG.cpp