Diana: sysy::mc::Reg Class Reference
sysy::mc::Reg Class Reference
#include <Reg.h>
Public Types
enum Type { VIRTUAL, PHY }
enum Kind { SREG, VREG }
Public Member Functions
bool operator< (const Reg &other)
bool operator== (const Reg &other)
Reg ()
Reg (int _id)
Reg (int _id, Type _type)
Reg (int _id, Type _type, Kind _kind)
std::string getSignature ()
Public Attributes
Type type
Kind kind
int id
int cost = -1
Static Public Attributes
static std::map< Type, std::string > type_map
static std::map< Kind, std::string > kind_map
Member Enumeration Documentation
Kind
enum sysy::mc::Reg::Kind
Enumerator
SREG
VREG
Type
enum sysy::mc::Reg::Type
Enumerator
VIRTUAL
PHY
Constructor & Destructor Documentation
Reg() [1/4]
sysy::mc::Reg::Reg () inline
Reg() [2/4]
sysy::mc::Reg::Reg (int _id) inline
Reg() [3/4]
sysy::mc::Reg::Reg (int _id, Type _type) inline
Reg() [4/4]
sysy::mc::Reg::Reg (int _id, Type _type, Kind _kind) inline
Member Function Documentation
getSignature()
std::string sysy::mc::Reg::getSignature ()
References kind, and SREG.
Referenced by sysy::mc::BinaryReg::gen_asm(), sysy::mc::BinaryImm::gen_asm(), sysy::mc::ComplexMul::gen_asm(), sysy::mc::MoveReg::gen_asm(), sysy::mc::ShiftInstr::gen_asm(), sysy::mc::MoveImm::gen_asm(), sysy::mc::CompareReg::gen_asm(), sysy::mc::CompareImm::gen_asm(), sysy::mc::LoadImm::gen_asm(), sysy::mc::LoadReg::gen_asm(), sysy::mc::StoreImm::gen_asm(), sysy::mc::StoreReg::gen_asm(), sysy::mc::LoadGlobal::gen_asm(), sysy::mc::LoadFP::gen_asm(), sysy::mc::Convert::gen_asm(), and sysy::mc::Bic::gen_asm().
operator<()
bool sysy::mc::Reg::operator< (const Reg & other) inline
References id.
operator==()
bool sysy::mc::Reg::operator== (const Reg & other) inline
References id, and type.
Member Data Documentation
cost
int sysy::mc::Reg::cost = -1
id
int sysy::mc::Reg::id
Referenced by operator<(), operator==(), sysy::mc::remove_multi_load(), sysy::mc::Regallocator::spill(), and sysy::mc::Regallocator::spill_v().
kind
Kind sysy::mc::Reg::kind
Referenced by getSignature(), and sysy::mc::Block::instSelection().
kind_map
std::map< Reg::Kind, std::string > sysy::mc::Reg::kind_map static
Initial value:
= {
    {Reg::SREG, "sreg"}, {Reg::VREG, "vreg"}
}
type
Type sysy::mc::Reg::type
Referenced by operator==().
type_map
std::map< Reg::Type, std::string > sysy::mc::Reg::type_map static
Initial value:
= {
    {Reg::PHY, "physical"}, {Reg::VIRTUAL, "virtual"}
}
The documentation for this class was generated from the following files:
include/sysy/Target/Reg.h
lib/Target/Reg.cpp