Diana: sysy::ir::BrInstruction Class Reference
sysy::ir::BrInstruction Class Reference
#include <Instructions.h>
Public Member Functions
BrInstruction (Value *_cond, BasicBlock *_trueBlock, BasicBlock *_falseBlock, BasicBlock *_father)
BrInstruction (BasicBlock *_trueBlock, BasicBlock *_father)
Value * getCond ()
void setUnconditional (BasicBlock *to)
void setConditional (Value *cond, BasicBlock *trueBB, BasicBlock *falseBB)
BasicBlock * getTrueBlock ()
BasicBlock * getFalseBlock ()
void replaceTarget (BasicBlock *from, BasicBlock *to)
std::string getSignature () override
Public Member Functions inherited from sysy::ir::TerminatorInstruction
TerminatorInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
TerminatorInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Private Attributes
bool unconditional
Additional Inherited Members
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
BrInstruction() [1/2]
sysy::ir::BrInstruction::BrInstruction (Value * _cond, BasicBlock * _trueBlock, BasicBlock * _falseBlock, BasicBlock * _father)
References sysy::ir::User::addOperand().
BrInstruction() [2/2]
sysy::ir::BrInstruction::BrInstruction (BasicBlock * _trueBlock, BasicBlock * _father)
References sysy::ir::User::addOperand(), and sysy::ir::ConstantInt::get().
Member Function Documentation
getCond()
Value* sysy::ir::BrInstruction::getCond () inline
References sysy::ir::User::operands, and unconditional.
Referenced by sysy::ir::LoopInfo::computeExitingBlocks(), sysy::ir::SimplifyCFG::deleteEmptyBB(), getSignature(), sysy::ir::SimplifyCFG::mergeBB(), and sysy::ir::SimplifyCFG::upperTheBranch().
getFalseBlock()
BasicBlock * sysy::ir::BrInstruction::getFalseBlock ()
References sysy::ir::User::operands.
Referenced by getSignature(), and replaceTarget().
getSignature()
std::string sysy::ir::BrInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References getCond(), getFalseBlock(), sysy::ir::getLabel(), sysy::ir::Type::getSignature(), getTrueBlock(), sysy::ir::Value::getType(), and sysy::ir::nameIs().
getTrueBlock()
BasicBlock * sysy::ir::BrInstruction::getTrueBlock ()
References sysy::ir::User::operands.
Referenced by getSignature(), and replaceTarget().
replaceTarget()
void sysy::ir::BrInstruction::replaceTarget (BasicBlock * from, BasicBlock * to)
References getFalseBlock(), getTrueBlock(), sysy::ir::User::replaceOperandWith(), and unconditional.
setConditional()
void sysy::ir::BrInstruction::setConditional (Value * cond, BasicBlock * trueBB, BasicBlock * falseBB)
References sysy::ir::User::addOperand(), sysy::ir::User::replaceOperandWith(), and unconditional.
setUnconditional()
void sysy::ir::BrInstruction::setUnconditional (BasicBlock * to)
References sysy::ir::ConstantInt::get(), sysy::ir::User::operands, sysy::ir::User::replaceOperandWith(), and unconditional.
Member Data Documentation
unconditional
bool sysy::ir::BrInstruction::unconditional private
Referenced by getCond(), replaceTarget(), setConditional(), and setUnconditional().
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/Instructions.cpp
lib/IR/IRDump.cpp