Diana: SysYParser::MulExpContext Class Reference
SysYParser::MulExpContext Class Reference
#include <SysYParser.h>
Public Member Functions
MulExpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
UnaryExpContext * unaryExp ()
MulExpContext * mulExp ()
antlr4::tree::TerminalNode * MUL ()
antlr4::tree::TerminalNode * DIV ()
antlr4::tree::TerminalNode * MOD ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
MulExpContext()
SysYParser::MulExpContext::MulExpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::MulExpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
DIV()
tree::TerminalNode * SysYParser::MulExpContext::DIV ()
References SysYParser::DIV.
Referenced by sysy::SysYVisitor::visitMulExp().
getRuleIndex()
size_t SysYParser::MulExpContext::getRuleIndex () const override virtual
References SysYParser::RuleMulExp.
MOD()
tree::TerminalNode * SysYParser::MulExpContext::MOD ()
References SysYParser::MOD.
MUL()
tree::TerminalNode * SysYParser::MulExpContext::MUL ()
References SysYParser::MUL.
Referenced by sysy::SysYVisitor::visitMulExp().
mulExp()
SysYParser::MulExpContext * SysYParser::MulExpContext::mulExp ()
Referenced by sysy::SysYVisitor::visitMulExp().
unaryExp()
SysYParser::UnaryExpContext * SysYParser::MulExpContext::unaryExp ()
Referenced by sysy::SysYVisitor::visitMulExp().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp