Diana: SysYParser::ConstInitValContext Class Reference
SysYParser::ConstInitValContext Class Reference
#include <SysYParser.h>
Public Member Functions
ConstInitValContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
ConstExpContext * constExp ()
antlr4::tree::TerminalNode * LCBRA ()
antlr4::tree::TerminalNode * RCBRA ()
std::vector< ConstInitValContext * > constInitVal ()
ConstInitValContext * constInitVal (size_t i)
std::vector< antlr4::tree::TerminalNode * > COMMA ()
antlr4::tree::TerminalNode * COMMA (size_t i)
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
ConstInitValContext()
SysYParser::ConstInitValContext::ConstInitValContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::ConstInitValContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
COMMA() [1/2]
std::vector< tree::TerminalNode * > SysYParser::ConstInitValContext::COMMA ()
References SysYParser::COMMA.
COMMA() [2/2]
tree::TerminalNode * SysYParser::ConstInitValContext::COMMA (size_t i)
References SysYParser::COMMA.
constExp()
SysYParser::ConstExpContext * SysYParser::ConstInitValContext::constExp ()
Referenced by sysy::SysYVisitor::constInitValDfs(), and sysy::SysYVisitor::visitConstInitVal().
constInitVal() [1/2]
std::vector< SysYParser::ConstInitValContext * > SysYParser::ConstInitValContext::constInitVal ()
Referenced by sysy::SysYVisitor::constInitValDfs(), and sysy::SysYVisitor::visitConstInitVal().
constInitVal() [2/2]
SysYParser::ConstInitValContext * SysYParser::ConstInitValContext::constInitVal (size_t i)
getRuleIndex()
size_t SysYParser::ConstInitValContext::getRuleIndex () const override virtual
References SysYParser::RuleConstInitVal.
LCBRA()
tree::TerminalNode * SysYParser::ConstInitValContext::LCBRA ()
References SysYParser::LCBRA.
RCBRA()
tree::TerminalNode * SysYParser::ConstInitValContext::RCBRA ()
References SysYParser::RCBRA.
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp