Diana: sysy::ir::ADCE Class Reference
sysy::ir::ADCE Class Reference
#include <ADCE.h>
Public Member Functions
ADCE ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void removeUselessStore (BasicBlock *bb)
bool isUsefulInstr (Instruction *instr)
void findAliveCode (Instruction *instr)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
ADCE()
sysy::ir::ADCE::ADCE ()
References sysy::Pass< Opt >::getFinish(), and sysy::Pass< Opt >::getRelated().
Member Function Documentation
findAliveCode()
void sysy::ir::ADCE::findAliveCode (Instruction * instr) private
References sysy::ir::AliveBB, sysy::ir::AliveCode, sysy::ir::dumpBasickBlock(), sysy::ir::Instruction::getBasicBlock(), sysy::ir::User::getOprands(), and PrintMsg.
getName()
std::string sysy::ir::ADCE::getName () inline override virtual
Implements sysy::Pass< Opt >.
isUsefulInstr()
bool sysy::ir::ADCE::isUsefulInstr (Instruction * instr) private
References sysy::ir::CallInstruction::isPureCall().
removeUselessStore()
void sysy::ir::ADCE::removeUselessStore (BasicBlock * bb) private
run()
void sysy::ir::ADCE::run (Function * func) override
References sysy::ir::AliveCode, sysy::ir::BasicBlock::BasicBlockDfs(), sysy::ir::Function::getEntryBlock(), sysy::ir::Value::getName(), and PrintMsg.
The documentation for this class was generated from the following files:
include/sysy/Transform/Scalar/ADCE.h
lib/Transform/Scalar/ADCE.cpp