Diana: SysYParser::UnaryOpContext Class Reference
SysYParser::UnaryOpContext Class Reference
#include <SysYParser.h>
Public Member Functions
UnaryOpContext (antlr4::ParserRuleContext *parent, size_t invokingState)
virtual size_t getRuleIndex () const override
antlr4::tree::TerminalNode * ADD ()
antlr4::tree::TerminalNode * SUB ()
antlr4::tree::TerminalNode * NOT ()
virtual antlrcpp::Any accept (antlr4::tree::ParseTreeVisitor *visitor) override
Constructor & Destructor Documentation
UnaryOpContext()
SysYParser::UnaryOpContext::UnaryOpContext (antlr4::ParserRuleContext * parent, size_t invokingState)
Member Function Documentation
accept()
antlrcpp::Any SysYParser::UnaryOpContext::accept (antlr4::tree::ParseTreeVisitor * visitor) override virtual
ADD()
tree::TerminalNode * SysYParser::UnaryOpContext::ADD ()
References SysYParser::ADD.
Referenced by sysy::SysYVisitor::visitUnaryExp().
getRuleIndex()
size_t SysYParser::UnaryOpContext::getRuleIndex () const override virtual
References SysYParser::RuleUnaryOp.
NOT()
tree::TerminalNode * SysYParser::UnaryOpContext::NOT ()
References SysYParser::NOT.
Referenced by sysy::SysYVisitor::visitUnaryExp().
SUB()
tree::TerminalNode * SysYParser::UnaryOpContext::SUB ()
References SysYParser::SUB.
Referenced by sysy::SysYVisitor::visitUnaryExp().
The documentation for this class was generated from the following files:
include/sysy/Frontend/SysYParser.h
lib/Frontend/SysYParser.cpp