Diana: sysy::ir::Type Class Reference
sysy::ir::Type Class Reference abstract
#include <Type.h>
Public Types
enum TypeID {
FloatTyID = 0, VoidTyID, LabelTyID, IntegerTyID,
FunctionTyID, PointerTyID, ArrayTyID, FixedVectorTyID,
ScalableVectorTyID, UndefTyID
}
Public Member Functions
bool isFloatTy ()
bool isVoidTy ()
bool isLabelTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned width)
bool isFunctionTy ()
bool isPointerTy ()
bool isVectorTy ()
bool isArrayTy ()
bool isUndefTy ()
virtual Type * getInnerType ()=0
virtual std::string getSignature ()=0
virtual size_t getAllocatedSize ()=0
Static Public Member Functions
static Type * getFloatTy ()
static Type * getVoidTy ()
static Type * getUndefTy ()
static Type * getFunctionTy (Type *_retType, std::vector< Type * > _argType, bool isVarArg)
static Type * getLabelTy ()
static Type * getIntegerTy (unsigned width)
static Type * getInt1Ty ()
static Type * getInt32Ty ()
static Type * getInt8Ty ()
static Type * getPointerTy (Type *inner)
static Type * getArrayTy (Type *inner, unsigned size)
static Type * getInt8PtrTy ()
static Type * getInt32PtrTy ()
static Type * getFloatPtrTy ()
Protected Member Functions
Type (TypeID id)
TypeID getTypeId ()
unsigned getSize ()
Private Attributes
TypeID ID
unsigned size
Friends
bool sameType (Type *x, Type *y)
Member Enumeration Documentation
TypeID
enum sysy::ir::Type::TypeID
Enumerator
FloatTyID
32-bit floating point type
VoidTyID
type with no size
LabelTyID
Labels.
IntegerTyID
Arbitrary bit width integers.
FunctionTyID
Functions.
PointerTyID
Pointers.
ArrayTyID
Arrays.
FixedVectorTyID
Fixed width SIMD vector type.
ScalableVectorTyID
Scalable SIMD vector type.
UndefTyID
Constructor & Destructor Documentation
Type()
sysy::ir::Type::Type (TypeID id) inline explicit protected
Member Function Documentation
getAllocatedSize()
virtual size_t sysy::ir::Type::getAllocatedSize () pure virtual
Implemented in sysy::ir::FunctionType, sysy::ir::ArrayType, sysy::ir::PointerType, sysy::ir::IntegerType, sysy::ir::FloatType, sysy::ir::UndefType, sysy::ir::VoidType, and sysy::ir::LableType.
getArrayTy()
Type * sysy::ir::Type::getArrayTy (Type * inner, unsigned size) static
References sysy::ir::ArrayType::get(), and size.
getFloatPtrTy()
Type * sysy::ir::Type::getFloatPtrTy () static
References sysy::ir::PointerType::getFloatPtrTy().
getFloatTy()
Type * sysy::ir::Type::getFloatTy () static
References sysy::ir::FloatType::get().
Referenced by sysy::ast::AstType2IrType(), sysy::ir::IRBuilder::CreateFAdd(), sysy::ir::IRBuilder::CreateFDiv(), sysy::ir::IRBuilder::CreateFMul(), sysy::ir::IRBuilder::CreateFNeg(), sysy::ir::IRBuilder::CreateFRem(), sysy::ir::IRBuilder::CreateFSub(), sysy::ir::IRBuilder::CreateSIToFP(), sysy::ir::PointerType::getFloatPtrTy(), sysy::ir::irEmit(), and sysy::ir::simplifyInstruction().
getFunctionTy()
Type * sysy::ir::Type::getFunctionTy (Type * _retType, std::vector< Type * > _argType, bool isVarArg) static
References sysy::ir::FunctionType::get(), and sysy::ir::isVarArg.
getInnerType()
virtual Type* sysy::ir::Type::getInnerType () pure virtual
Implemented in sysy::ir::FunctionType, sysy::ir::ArrayType, sysy::ir::PointerType, sysy::ir::IntegerType, sysy::ir::FloatType, sysy::ir::UndefType, sysy::ir::VoidType, and sysy::ir::LableType.
Referenced by sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::IRBuilder::CreateMemCpyInline(), sysy::ir::emitInitial(), sysy::ir::getPtrPtr(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::GlobalValue::getValueType(), sysy::mc::Block::instSelection(), sysy::ir::irEmit(), and sysy::ir::isAliasByGVToArg().
getInt1Ty()
Type * sysy::ir::Type::getInt1Ty () static
References sysy::ir::IntegerType::getInt1Ty().
Referenced by sysy::ir::IRBuilder::CreateFCmpUEQ(), sysy::ir::IRBuilder::CreateFCmpUGE(), sysy::ir::IRBuilder::CreateFCmpUGT(), sysy::ir::IRBuilder::CreateFCmpULE(), sysy::ir::IRBuilder::CreateFCmpULT(), sysy::ir::IRBuilder::CreateFCmpUNE(), sysy::ir::IRBuilder::CreateICmpEQ(), sysy::ir::IRBuilder::CreateICmpNE(), sysy::ir::IRBuilder::CreateICmpSGE(), sysy::ir::IRBuilder::CreateICmpSGT(), sysy::ir::IRBuilder::CreateICmpSLE(), sysy::ir::IRBuilder::CreateICmpSLT(), sysy::ir::ConstantInt::get(), and sysy::ir::irEmit().
getInt32PtrTy()
Type * sysy::ir::Type::getInt32PtrTy () static
References sysy::ir::PointerType::getInt32PtrTy().
getInt32Ty()
Type * sysy::ir::Type::getInt32Ty () static
References sysy::ir::IntegerType::getInt32Ty().
Referenced by sysy::ast::AstType2IrType(), sysy::ir::ScalarEvolution::BIV2SCEV(), sysy::ir::IRBuilder::CreateAdd(), sysy::ir::IRBuilder::CreateFPToSI(), sysy::ir::IRBuilder::CreateMul(), sysy::ir::IRBuilder::CreateNeg(), sysy::ir::IRBuilder::CreateSDiv(), sysy::ir::IRBuilder::CreateSRem(), sysy::ir::IRBuilder::CreateSub(), sysy::ir::GVN::doPerInstr(), sysy::ir::ConstantInt::get(), sysy::ir::getElementPtr(), sysy::ir::getIDX(), sysy::ir::PointerType::getInt32PtrTy(), sysy::ir::getPtrPtr(), sysy::ir::AllocaInstruction::getSize(), sysy::ir::irEmit(), sysy::ir::LoopParallel::runOnLoop(), and sysy::ir::simplifyInstruction().
getInt8PtrTy()
Type * sysy::ir::Type::getInt8PtrTy () static
References sysy::ir::PointerType::getInt8PtrTy().
Referenced by sysy::ir::IRBuilder::CreateMemCpyInline().
getInt8Ty()
Type * sysy::ir::Type::getInt8Ty () static
References sysy::ir::IntegerType::getInt8Ty().
Referenced by sysy::ir::ConstantInt::get(), and sysy::ir::PointerType::getInt8PtrTy().
getIntegerTy()
Type * sysy::ir::Type::getIntegerTy (unsigned width) static
References sysy::ir::IntegerType::get().
getLabelTy()
Type * sysy::ir::Type::getLabelTy () static
References sysy::ir::LableType::get().
getPointerTy()
Type * sysy::ir::Type::getPointerTy (Type * inner) static
References sysy::ir::PointerType::get().
Referenced by sysy::ir::GlobalValue::Create(), and sysy::ir::irEmit().
getSignature()
virtual std::string sysy::ir::Type::getSignature () pure virtual
Implemented in sysy::ir::FunctionType, sysy::ir::ArrayType, sysy::ir::PointerType, sysy::ir::IntegerType, sysy::ir::FloatType, sysy::ir::UndefType, sysy::ir::VoidType, and sysy::ir::LableType.
Referenced by sysy::ir::BinaryInstrcution::getSignature(), sysy::ir::GlobalValue::getSignature(), sysy::ir::Function::Arg::getSignature(), sysy::ir::UnaryInstruction::getSignature(), sysy::ir::Function::getSignature(), sysy::ir::CallInstruction::getSignature(), sysy::ir::BrInstruction::getSignature(), sysy::ir::RetInstruction::getSignature(), sysy::ir::StoreInstruction::getSignature(), sysy::ir::PointerType::getSignature(), sysy::ir::LoadInstruction::getSignature(), sysy::ir::ArrayType::getSignature(), sysy::ir::GEPInstruction::getSignature(), sysy::ir::FunctionType::getSignature(), sysy::ir::AllocaInstruction::getSignature(), sysy::ir::PhiInstruction::getSignature(), and sysy::ir::MemPhiInstruction::getSignature().
getSize()
unsigned sysy::ir::Type::getSize () inline protected
References size.
getTypeId()
TypeID sysy::ir::Type::getTypeId () inline protected
References ID.
Referenced by isArrayTy(), isFloatTy(), isFunctionTy(), isIntegerTy(), isLabelTy(), isPointerTy(), isUndefTy(), isVectorTy(), and isVoidTy().
getUndefTy()
Type * sysy::ir::Type::getUndefTy () static
References sysy::ir::UndefType::get().
getVoidTy()
Type * sysy::ir::Type::getVoidTy () static
References sysy::ir::VoidType::get().
Referenced by sysy::ir::createGlobalInit(), sysy::ir::irEmit(), sysy::ir::MemorySSA::queueLoadMemPhi(), and sysy::ir::MemorySSA::queueStoreMemPhi().
isArrayTy()
bool sysy::ir::Type::isArrayTy () inline
References ArrayTyID, and getTypeId().
Referenced by sysy::ir::MemorySSA::computeArrayInfo(), sysy::ir::Constant::getZero(), sysy::ir::irEmit(), sysy::ir::Memory2Reg::isAllocaPromotable(), and sysy::ir::LoopParallel::isParallelizable().
isFloatTy()
bool sysy::ir::Type::isFloatTy () inline
References FloatTyID, and getTypeId().
Referenced by sysy::mc::Function::analyseFunc(), sysy::mc::Function::get_reg(), sysy::ir::Constant::getZero(), sysy::mc::Block::instSelection(), sysy::ir::irEmit(), sysy::ir::isSameType(), and sysy::ir::CleanExitBasicBlock::run().
isFunctionTy()
bool sysy::ir::Type::isFunctionTy () inline
References FunctionTyID, and getTypeId().
isIntegerTy() [1/2]
bool sysy::ir::Type::isIntegerTy () inline
References getTypeId(), and IntegerTyID.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::emitInitial(), sysy::ir::getConstantArray(), sysy::ir::Constant::getZero(), sysy::ir::irEmit(), sysy::ir::isSameType(), and sysy::ir::CleanExitBasicBlock::run().
isIntegerTy() [2/2]
bool sysy::ir::Type::isIntegerTy (unsigned width)
isLabelTy()
bool sysy::ir::Type::isLabelTy () inline
References getTypeId(), and LabelTyID.
isPointerTy()
bool sysy::ir::Type::isPointerTy () inline
References getTypeId(), and PointerTyID.
Referenced by sysy::ir::IRBuilder::CreateInBoundsGEP(), sysy::ir::irEmit(), and sysy::ir::Memory2Reg::isAllocaPromotable().
isUndefTy()
bool sysy::ir::Type::isUndefTy () inline
References getTypeId(), and UndefTyID.
isVectorTy()
bool sysy::ir::Type::isVectorTy () inline
References FixedVectorTyID, getTypeId(), and ScalableVectorTyID.
isVoidTy()
bool sysy::ir::Type::isVoidTy () inline
References getTypeId(), and VoidTyID.
Referenced by sysy::ir::RetInstruction::isVoidRet().
Friends And Related Function Documentation
sameType
bool sameType (Type * x, Type * y) friend
Member Data Documentation
ID
TypeID sysy::ir::Type::ID private
Referenced by getTypeId().
size
unsigned sysy::ir::Type::size private
Referenced by getArrayTy(), and getSize().
The documentation for this class was generated from the following files:
include/sysy/IR/Type.h
lib/IR/Type.cpp