Diana: sysy::ir::BasicBlock Class Reference
sysy::ir::BasicBlock Class Reference
#include <BasicBlock.h>
Public Types
using iterator = std::list< Instruction * >::iterator
using reverse_iterator = std::list< Instruction * >::reverse_iterator
Public Member Functions
BasicBlock (const std::string name, bool isPreHeader)
BasicBlock (const std::string name, Function *func, bool isPreHeader)
std::list< Instruction * > & getInstructions ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
void setIdom (BasicBlock *bb)
BasicBlock * getIdom ()
void setDomLevel (int level)
int getDomLevel ()
std::set< BasicBlock * > & getDoms ()
std::vector< BasicBlock * > & getDomTree ()
std::vector< BasicBlock * > & getDomFrontier ()
std::vector< BasicBlock * > & getSuccessor ()
std::vector< BasicBlock * > & getPredecessor ()
void setIpdom (BasicBlock *bb)
BasicBlock * getIpdom ()
void setPdomLevel (int level)
int getPdomLevel ()
std::set< BasicBlock * > & getPdoms ()
std::vector< BasicBlock * > & getPdomTree ()
std::vector< BasicBlock * > & getPdomFrontier ()
BasicBlock::iterator insertInstr (iterator iter, Instruction *instr)
void insertBack (Instruction *instr)
void insertBeforeTerminal (Instruction *instr)
void insertFront (Instruction *instr)
void insertAfterPhi (Instruction *instr)
void setRank (Instruction *instr, int _rank)
void rankReorder ()
int getRank (const Instruction *instr)
std::string getSignature () override
Function * getParent ()
void setParent (Function *func)
bool isPreHeader ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static BasicBlock * Create (const std::string &name, bool isPreHeader=false)
static BasicBlock * Create (const std::string &name, Function *theFunction, bool isPreHeader=false)
static void BasicBlockDfs (BasicBlock *bb, std::function< bool(BasicBlock *)> func)
static void BasicBlockDfs (BasicBlock *pre, BasicBlock *bb, std::function< bool(BasicBlock *, BasicBlock *)> func)
static void BasicBlockDfsInv (BasicBlock *bb, std::function< bool(BasicBlock *)> func)
static void BasicBlockDfsInv (BasicBlock *pre, BasicBlock *bb, std::function< bool(BasicBlock *, BasicBlock *)> func)
static void BasicBlockDfsPost (BasicBlock *bb, std::function< bool(BasicBlock *)> cond, std::function< void(BasicBlock *)> action)
static void DomTreeDfsPost (BasicBlock *bb, std::function< bool(BasicBlock *)> cond, std::function< void(BasicBlock *)> action)
Private Attributes
Function * father
std::list< Instruction * > instructions
std::unordered_map< const Instruction *, int > rank
std::vector< BasicBlock * > successor
std::vector< BasicBlock * > predecessor
std::set< BasicBlock * > dom
BasicBlock * idom = nullptr
std::vector< BasicBlock * > domTreeEdge
std::vector< BasicBlock * > domFrontier
int domLevel
std::set< BasicBlock * > pdom
BasicBlock * ipdom = nullptr
std::vector< BasicBlock * > pdomTreeEdge
std::vector< BasicBlock * > pdomFrontier
int pdomLevel
bool preHeader
Additional Inherited Members
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Member Typedef Documentation
iterator
using sysy::ir::BasicBlock::iterator = std::list<Instruction*>::iterator
reverse_iterator
using sysy::ir::BasicBlock::reverse_iterator = std::list<Instruction*>::reverse_iterator
Constructor & Destructor Documentation
BasicBlock() [1/2]
sysy::ir::BasicBlock::BasicBlock (const std::string name, bool isPreHeader) inline
Referenced by Create().
BasicBlock() [2/2]
sysy::ir::BasicBlock::BasicBlock (const std::string name, Function * func, bool isPreHeader) inline
Member Function Documentation
BasicBlockDfs() [1/2]
void sysy::ir::BasicBlock::BasicBlockDfs (BasicBlock * bb, std::function< bool(BasicBlock *)> func) static
References getSuccessor().
Referenced by BasicBlockDfs(), sysy::ir::IdomGen::getDfnum(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::SimplifyCFG::removeDeadBB(), sysy::ir::SplitCriticalEdge::run(), sysy::ir::ADCE::run(), sysy::ir::FunctionVertify::run(), sysy::ir::EliminatePhi::run(), sysy::ir::GCM::run(), sysy::ir::DCE::run(), and sysy::ir::Memory2Reg::run().
BasicBlockDfs() [2/2]
void sysy::ir::BasicBlock::BasicBlockDfs (BasicBlock * pre, BasicBlock * bb, std::function< bool(BasicBlock *, BasicBlock *)> func) static
References BasicBlockDfs(), and getSuccessor().
BasicBlockDfsInv() [1/2]
void sysy::ir::BasicBlock::BasicBlockDfsInv (BasicBlock * bb, std::function< bool(BasicBlock *)> func) static
References getPredecessor().
Referenced by BasicBlockDfsInv(), sysy::ir::Memory2Reg::computeLiveIn(), and sysy::ir::IpdomGen::getDfnum().
BasicBlockDfsInv() [2/2]
void sysy::ir::BasicBlock::BasicBlockDfsInv (BasicBlock * pre, BasicBlock * bb, std::function< bool(BasicBlock *, BasicBlock *)> func) static
References BasicBlockDfsInv(), and getPredecessor().
BasicBlockDfsPost()
void sysy::ir::BasicBlock::BasicBlockDfsPost (BasicBlock * bb, std::function< bool(BasicBlock *)> cond, std::function< void(BasicBlock *)> action) static
References getSuccessor().
Referenced by sysy::ir::LoopInfo::run(), sysy::ir::SimplifyCFG::run(), and sysy::ir::GVN::run().
begin()
iterator sysy::ir::BasicBlock::begin () inline
References instructions.
Referenced by sysy::ir::CreateEntryBlockAlloca(), and sysy::ir::globalInit().
Create() [1/2]
BasicBlock * sysy::ir::BasicBlock::Create (const std::string & name, bool isPreHeader = false) static
References BasicBlock(), isPreHeader(), and sysy::ir::Value::name.
Referenced by sysy::ir::createGlobalInit(), sysy::ir::SplitCriticalEdge::cutKeyEdge(), sysy::ir::EliminatePhi::cutKeyEdge(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::irEmit(), and sysy::ir::ConstructExitBasicBlock::run().
Create() [2/2]
BasicBlock * sysy::ir::BasicBlock::Create (const std::string & name, Function * theFunction, bool isPreHeader = false) static
References BasicBlock(), sysy::ir::Function::getBasicBlockList(), isPreHeader(), and sysy::ir::Value::name.
DomTreeDfsPost()
void sysy::ir::BasicBlock::DomTreeDfsPost (BasicBlock * bb, std::function< bool(BasicBlock *)> cond, std::function< void(BasicBlock *)> action) static
References getDomTree().
Referenced by sysy::ir::LoopInfo::run().
end()
iterator sysy::ir::BasicBlock::end () inline
References instructions.
Referenced by sysy::ir::IRBuilder::insertInstr(), and sysy::ir::IRBuilder::SetInsertPoint().
getDomFrontier()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getDomFrontier () inline
References domFrontier.
Referenced by sysy::ir::DomFrontierGen::computeDF(), and sysy::ir::Memory2Reg::run().
getDomLevel()
int sysy::ir::BasicBlock::getDomLevel () inline
References domLevel.
Referenced by sysy::ir::lcaCompute().
getDoms()
std::set<BasicBlock*>& sysy::ir::BasicBlock::getDoms () inline
References dom.
Referenced by sysy::ir::DomTreeGen::computeAllDom(), and sysy::ir::GCM::schduleEarly().
getDomTree()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getDomTree () inline
References domTreeEdge.
Referenced by sysy::ir::DomTreeGen::computeAllDom(), sysy::ir::DomFrontierGen::computeDF(), sysy::ir::DomTreeGen::computeDomLevel(), and DomTreeDfsPost().
getIdom()
BasicBlock* sysy::ir::BasicBlock::getIdom () inline
References idom.
Referenced by sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::lcaCompute(), and sysy::ir::GCM::schduleLate().
getInstructions()
std::list<Instruction*>& sysy::ir::BasicBlock::getInstructions () inline
References instructions.
Referenced by sysy::ir::SimplifyCFG::addEdge(), sysy::ir::SplitCriticalEdge::cutKeyEdge(), sysy::ir::EliminatePhi::cutKeyEdge(), sysy::ir::SimplifyCFG::deleteEdge(), sysy::ir::SimplifyCFG::deleteEmptyBB(), sysy::ir::IRCopier::getLoopCopy(), insertAfterPhi(), sysy::mc::Block::instSelection(), sysy::ir::irEmit(), sysy::ir::EliminatePhi::isNeedToCut(), sysy::ir::SimplifyCFG::mergeBB(), sysy::ir::SimplifyCFG::redirectEdge(), sysy::ir::SimplifyCFG::removeDeadBB(), sysy::ir::DCE::removeUselessStore(), sysy::ir::Memory2Reg::renameAllocaInBB(), sysy::ir::EliminatePhi::run(), sysy::ir::Memory2Reg::run(), sysy::ir::GCM::schduleEarly(), sysy::ir::GCM::schduleLate(), sysy::ir::SimplifyCFG::simplifyPhi(), sysy::ir::SimplifyCFG::uncondTheCondBr(), and sysy::ir::SimplifyCFG::upperTheBranch().
getIpdom()
BasicBlock* sysy::ir::BasicBlock::getIpdom () inline
References ipdom.
getParent()
Function* sysy::ir::BasicBlock::getParent () inline
References father.
Referenced by sysy::ir::SimplifyCFG::deleteEmptyBB(), sysy::ir::LoopInfo::getLoopDepth(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::irEmit(), sysy::ir::GCM::schduleEarly(), and sysy::ir::GCM::schduleLate().
getPdomFrontier()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getPdomFrontier () inline
References pdomFrontier.
Referenced by sysy::ir::PostDomFrontierGen::computeRDF().
getPdomLevel()
int sysy::ir::BasicBlock::getPdomLevel () inline
References pdomLevel.
getPdoms()
std::set<BasicBlock*>& sysy::ir::BasicBlock::getPdoms () inline
References pdom.
Referenced by sysy::ir::PostDomTreeGen::computeAllPostDom().
getPdomTree()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getPdomTree () inline
References pdomTreeEdge.
Referenced by sysy::ir::PostDomTreeGen::computeAllPostDom(), sysy::ir::PostDomTreeGen::computePostDomLevel(), and sysy::ir::PostDomFrontierGen::computeRDF().
getPredecessor()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getPredecessor () inline
References predecessor.
Referenced by sysy::ir::SimplifyCFG::addEdge(), BasicBlockDfsInv(), sysy::ir::PostDomFrontierGen::computeRDF(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::SplitCriticalEdge::cutKeyEdge(), sysy::ir::EliminatePhi::cutKeyEdge(), sysy::ir::SimplifyCFG::deleteEdge(), sysy::ir::SimplifyCFG::deleteEmptyBB(), sysy::ir::IRCopier::getFunctionCopy(), sysy::ir::FunctionInline::inlineAtCall(), sysy::ir::SplitCriticalEdge::isNeedToCut(), sysy::ir::SimplifyCFG::redirectEdge(), sysy::ir::ConstructExitBasicBlock::run(), and sysy::ir::SimplifyCFG::simplifyPhi().
getRank()
int sysy::ir::BasicBlock::getRank (const Instruction * instr) inline
References rank.
Referenced by sysy::ir::Instruction::getRank(), sysy::ir::less(), sysy::ir::ArrayInfo::cmps::operator()(), sysy::ir::ArrayInfo::cmpl::operator()(), sysy::ir::cmps::operator()(), sysy::ir::cmpl::operator()(), sysy::ir::GVInfo::cmps::operator()(), and sysy::ir::GVInfo::cmpl::operator()().
getSignature()
std::string sysy::ir::BasicBlock::getSignature () override virtual
Implements sysy::ir::Value.
References sysy::ir::getLabel(), instructions, predecessor, and successor.
getSuccessor()
std::vector<BasicBlock*>& sysy::ir::BasicBlock::getSuccessor () inline
References successor.
Referenced by sysy::ir::SimplifyCFG::addEdge(), BasicBlockDfs(), BasicBlockDfsPost(), sysy::ir::DomFrontierGen::computeDF(), sysy::ir::IRBuilder::CreateBr(), sysy::ir::IRBuilder::CreateCondBr(), sysy::ir::SplitCriticalEdge::cutKeyEdge(), sysy::ir::EliminatePhi::cutKeyEdge(), sysy::ir::SimplifyCFG::deleteEdge(), sysy::ir::SplitCriticalEdge::isNeedToCut(), sysy::ir::EliminatePhi::isNeedToCut(), sysy::ir::SimplifyCFG::mergeBB(), sysy::ir::SimplifyCFG::redirectEdge(), sysy::ir::SimplifyCFG::removeDeadBB(), sysy::ir::Memory2Reg::run(), and sysy::ir::SimplifyCFG::uncondTheCondBr().
insertAfterPhi()
void sysy::ir::BasicBlock::insertAfterPhi (Instruction * instr)
References getInstructions().
insertBack()
void sysy::ir::BasicBlock::insertBack (Instruction * instr) inline
References instructions.
Referenced by sysy::ir::IRBuilder::insertInstr(), and sysy::ir::SimplifyCFG::mergeBB().
insertBeforeTerminal()
void sysy::ir::BasicBlock::insertBeforeTerminal (Instruction * instr)
References instructions, and sysy::ir::Instruction::reSetBasicBlock().
Referenced by sysy::ir::LSR::eraseSingleMul().
insertFront()
void sysy::ir::BasicBlock::insertFront (Instruction * instr) inline
References instructions.
Referenced by sysy::ir::LSR::eraseSingleMul(), sysy::ir::LCSSA::getIncomingValAtBB(), sysy::ir::MemorySSA::queueLoadMemPhi(), sysy::ir::Memory2Reg::queuePhi(), and sysy::ir::MemorySSA::queueStoreMemPhi().
insertInstr()
BasicBlock::iterator sysy::ir::BasicBlock::insertInstr (iterator iter, Instruction * instr) inline
References instructions.
Referenced by sysy::ir::IRBuilder::insertInstr().
isPreHeader()
bool sysy::ir::BasicBlock::isPreHeader () inline
References preHeader.
Referenced by Create(), and sysy::ir::SimplifyCFG::deleteEmptyBB().
rankReorder()
void sysy::ir::BasicBlock::rankReorder ()
References instructions, and rank.
Referenced by sysy::ir::Memory2Reg::run().
rbegin()
reverse_iterator sysy::ir::BasicBlock::rbegin () inline
References instructions.
Referenced by sysy::ir::GVN::run().
rend()
reverse_iterator sysy::ir::BasicBlock::rend () inline
References instructions.
Referenced by sysy::ir::GVN::run().
setDomLevel()
void sysy::ir::BasicBlock::setDomLevel (int level) inline
References domLevel.
Referenced by sysy::ir::DomTreeGen::computeDomLevel().
setIdom()
void sysy::ir::BasicBlock::setIdom (BasicBlock * bb) inline
References idom.
Referenced by sysy::ir::IdomGen::run().
setIpdom()
void sysy::ir::BasicBlock::setIpdom (BasicBlock * bb) inline
References ipdom.
Referenced by sysy::ir::IpdomGen::run().
setParent()
void sysy::ir::BasicBlock::setParent (Function * func) inline
References father.
Referenced by sysy::ir::irEmit().
setPdomLevel()
void sysy::ir::BasicBlock::setPdomLevel (int level) inline
References pdomLevel.
Referenced by sysy::ir::PostDomTreeGen::computePostDomLevel().
setRank()
void sysy::ir::BasicBlock::setRank (Instruction * instr, int _rank)
References rank.
Member Data Documentation
dom
std::set<BasicBlock*> sysy::ir::BasicBlock::dom private
Referenced by getDoms().
domFrontier
std::vector<BasicBlock*> sysy::ir::BasicBlock::domFrontier private
Referenced by getDomFrontier().
domLevel
int sysy::ir::BasicBlock::domLevel private
Referenced by getDomLevel(), and setDomLevel().
domTreeEdge
std::vector<BasicBlock*> sysy::ir::BasicBlock::domTreeEdge private
Referenced by getDomTree().
father
Function* sysy::ir::BasicBlock::father private
Referenced by getParent(), and setParent().
idom
BasicBlock* sysy::ir::BasicBlock::idom = nullptr private
Referenced by getIdom(), and setIdom().
instructions
std::list<Instruction*> sysy::ir::BasicBlock::instructions private
Referenced by begin(), end(), getInstructions(), getSignature(), insertBack(), insertBeforeTerminal(), insertFront(), insertInstr(), rankReorder(), rbegin(), and rend().
ipdom
BasicBlock* sysy::ir::BasicBlock::ipdom = nullptr private
Referenced by getIpdom(), and setIpdom().
pdom
std::set<BasicBlock*> sysy::ir::BasicBlock::pdom private
Referenced by getPdoms().
pdomFrontier
std::vector<BasicBlock*> sysy::ir::BasicBlock::pdomFrontier private
Referenced by getPdomFrontier().
pdomLevel
int sysy::ir::BasicBlock::pdomLevel private
Referenced by getPdomLevel(), and setPdomLevel().
pdomTreeEdge
std::vector<BasicBlock*> sysy::ir::BasicBlock::pdomTreeEdge private
Referenced by getPdomTree().
predecessor
std::vector<BasicBlock*> sysy::ir::BasicBlock::predecessor private
Referenced by getPredecessor(), and getSignature().
preHeader
bool sysy::ir::BasicBlock::preHeader private
Referenced by isPreHeader().
rank
std::unordered_map<const Instruction*, int> sysy::ir::BasicBlock::rank private
Referenced by getRank(), rankReorder(), and setRank().
successor
std::vector<BasicBlock*> sysy::ir::BasicBlock::successor private
Referenced by getSignature(), and getSuccessor().
The documentation for this class was generated from the following files:
include/sysy/IR/BasicBlock.h
lib/IR/BasicBlock.cpp
lib/IR/IRDump.cpp