Diana: sysy::ir::ConstantFP Class Reference
sysy::ir::ConstantFP Class Reference
#include <Constant.h>
Public Member Functions
ConstantFP (float _value)
bool isZero () override
bool isOne ()
float getValue ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::Constant
Constant (Type *_type, std::vector< Value * > _operands)
Constant (Type *_type)
void setZero ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Static Public Member Functions
static ConstantFP * get (float _value)
static ConstantFP * getZero ()
Static Public Member Functions inherited from sysy::ir::Constant
static Constant * getZero (Type *_type)
static Constant * getString (const std::string &str)
Private Attributes
float value
Additional Inherited Members
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::Constant
bool zeroinitializer = false
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
ConstantFP()
sysy::ir::ConstantFP::ConstantFP (float _value) inline
Referenced by get().
Member Function Documentation
get()
ConstantFP * sysy::ir::ConstantFP::get (float _value) static
References ConstantFP().
Referenced by sysy::ir::constantFold(), sysy::ir::IRBuilder::CreateFNeg(), sysy::ir::createGlobal(), sysy::ir::GVN::doPerInstr(), sysy::ir::getConstantArray(), getZero(), sysy::ir::irEmit(), sysy::ir::CleanExitBasicBlock::run(), and sysy::ir::simplifyInstruction().
getSignature()
std::string sysy::ir::ConstantFP::getSignature () override virtual
Implements sysy::ir::Value.
References value.
getValue()
float sysy::ir::ConstantFP::getValue () inline
References value.
Referenced by sysy::ir::GVN::checkoutTable().
getZero()
ConstantFP * sysy::ir::ConstantFP::getZero () static
References get().
Referenced by sysy::ir::GVN::doPerInstr(), sysy::ir::IPDCE::eraseAllUnuseReturn(), and sysy::ir::Constant::getZero().
isOne()
bool sysy::ir::ConstantFP::isOne () inline
References value.
isZero()
bool sysy::ir::ConstantFP::isZero () inline override virtual
Implements sysy::ir::Constant.
References value.
Member Data Documentation
value
float sysy::ir::ConstantFP::value private
Referenced by getSignature(), getValue(), isOne(), and isZero().
The documentation for this class was generated from the following files:
include/sysy/IR/Constant.h
lib/IR/Constant.cpp
lib/IR/IRDump.cpp