Diana: sysy::ir::PostDomFrontierGen Class Reference
sysy::ir::PostDomFrontierGen Class Reference
#include <PostDomInfo.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void computeRDF (BasicBlock *bb)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
computeRDF()
void sysy::ir::PostDomFrontierGen::computeRDF (BasicBlock * bb) private
References sysy::ir::BasicBlock::getPdomFrontier(), sysy::ir::BasicBlock::getPdomTree(), and sysy::ir::BasicBlock::getPredecessor().
Referenced by run().
getName()
std::string sysy::ir::PostDomFrontierGen::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::PostDomFrontierGen::run (Function * func) override
References computeRDF(), and sysy::ir::Function::getExitBlock().
The documentation for this class was generated from the following files:
include/sysy/Analysis/PostDomInfo.h
lib/Analysis/PostDomInfo.cpp