Diana: compiler.cpp File Reference
compiler.cpp File Reference
#include "sysy/Support/CommandLine.h"
#include "sysy/Frontend/Frontend.h"
#include "sysy/IR/Module.h"
#include "sysy/IR/PassManager.h"
#include "sysy/Target/Module.h"
#include "sysy/Transform/Transform.h"
#include "sysy/IR/IRDump.h"
#include <string>
#include <iostream>
Functions
int main (int argc, char *argv[])
Variables
cmdline::parser cmd
Function Documentation
main()
int main (int argc, char * argv[])
References cmdline::parser::add(), B, cmd, sysy::FrontendMain(), cmdline::parser::get(), sysy::ir::initialIRTransform(), cmdline::parser::parse_check(), and sysy::mc::Module::run().
Variable Documentation
cmd
cmdline::parser cmd
Referenced by main().