Diana: sysy::ir::BasicBlockTarget Class Reference
sysy::ir::BasicBlockTarget Class Reference
#include <IRGen.h>
Public Member Functions
BasicBlock * getEntry ()
BasicBlock * getAfter ()
BasicBlock * getTrue ()
BasicBlock * getFalse ()
void setEntry (BasicBlock *entry)
void setAfter (BasicBlock *after)
void setTrue (BasicBlock *_condTrue)
void exitTrue ()
void setFalse (BasicBlock *_condFalse)
void exitFalse ()
void setLoop (BasicBlock *entry, BasicBlock *after)
void exitLoop ()
void setCond (BasicBlock *_condTrue, BasicBlock *_condFalse)
void exitCond ()
Static Public Member Functions
static BasicBlockTarget & getInstance ()
Private Attributes
std::stack< BasicBlock * > loopEntry
std::stack< BasicBlock * > loopAfter
std::stack< BasicBlock * > condTrue
std::stack< BasicBlock * > condFalse
Member Function Documentation
exitCond()
void sysy::ir::BasicBlockTarget::exitCond () inline
Referenced by sysy::ir::irEmit().
exitFalse()
void sysy::ir::BasicBlockTarget::exitFalse () inline
Referenced by sysy::ir::irEmit().
exitLoop()
void sysy::ir::BasicBlockTarget::exitLoop () inline
Referenced by sysy::ir::irEmit().
exitTrue()
void sysy::ir::BasicBlockTarget::exitTrue () inline
Referenced by sysy::ir::irEmit().
getAfter()
BasicBlock* sysy::ir::BasicBlockTarget::getAfter () inline
Referenced by sysy::ir::irEmit().
getEntry()
BasicBlock* sysy::ir::BasicBlockTarget::getEntry () inline
Referenced by sysy::ir::irEmit().
getFalse()
BasicBlock* sysy::ir::BasicBlockTarget::getFalse () inline
Referenced by sysy::ir::irEmit().
getInstance()
static BasicBlockTarget& sysy::ir::BasicBlockTarget::getInstance () inline static
Referenced by sysy::ir::irEmit().
getTrue()
BasicBlock* sysy::ir::BasicBlockTarget::getTrue () inline
Referenced by sysy::ir::irEmit().
setAfter()
void sysy::ir::BasicBlockTarget::setAfter (BasicBlock * after) inline
setCond()
void sysy::ir::BasicBlockTarget::setCond (BasicBlock * _condTrue, BasicBlock * _condFalse) inline
Referenced by sysy::ir::irEmit().
setEntry()
void sysy::ir::BasicBlockTarget::setEntry (BasicBlock * entry) inline
setFalse()
void sysy::ir::BasicBlockTarget::setFalse (BasicBlock * _condFalse) inline
Referenced by sysy::ir::irEmit().
setLoop()
void sysy::ir::BasicBlockTarget::setLoop (BasicBlock * entry, BasicBlock * after) inline
Referenced by sysy::ir::irEmit().
setTrue()
void sysy::ir::BasicBlockTarget::setTrue (BasicBlock * _condTrue) inline
Referenced by sysy::ir::irEmit().
Member Data Documentation
condFalse
std::stack<BasicBlock*> sysy::ir::BasicBlockTarget::condFalse private
condTrue
std::stack<BasicBlock*> sysy::ir::BasicBlockTarget::condTrue private
loopAfter
std::stack<BasicBlock*> sysy::ir::BasicBlockTarget::loopAfter private
loopEntry
std::stack<BasicBlock*> sysy::ir::BasicBlockTarget::loopEntry private
The documentation for this class was generated from the following file:
include/sysy/IR/IRGen.h