Diana: sysy::ir::LoadInstruction Class Reference
sysy::ir::LoadInstruction Class Reference
#include <Instructions.h>
Public Member Functions
LoadInstruction (Type *_type, Value *_ptr, BasicBlock *_father, std::string _name="")
Value * getPtr ()
Value * getStore ()
void setStore (Value *store)
void removeStore ()
std::string getSignature () override
Public Member Functions inherited from sysy::ir::MemoryInstruction
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
MemoryInstruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
Public Member Functions inherited from sysy::ir::Instruction
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::vector< Value * > _oprands, std::string _name="")
Instruction (Type *_type, InstrKind _kind, BasicBlock *_father, std::string _name="")
InstrKind getKind ()
bool isInteger ()
bool isCmp ()
bool isTerminator ()
bool isCommutative ()
BasicBlock * getBasicBlock ()
BasicBlock * getBasicBlock () const
void reSetBasicBlock (BasicBlock *bb)
int getRank ()
Public Member Functions inherited from sysy::ir::User
User (Type *_type, std::vector< Value * > _operands, std::string _name="")
User (Type *_type, std::string _name="")
void addOperand (Value *_value)
OprandList & getOprands ()
void replaceOperand (unsigned index, Value *_value)
void replaceOperandWith (unsigned index, Value *_value)
void removeOperand (const std::shared_ptr< Use > &use)
void UnUseAll ()
Public Member Functions inherited from sysy::ir::Value
Value (Type *_type, std::string _name="")
std::list< std::shared_ptr< Use > > & getUses ()
void addUse (std::shared_ptr< Use > use)
void removeUse (const std::shared_ptr< Use > &use)
void removeUseIf (std::function< bool(std::shared_ptr< Use >)> func)
void replaceAllUseWith (Value *value)
void removeAllUseWith ()
std::string getName ()
void setName (std::string _name)
Type * getType ()
void setType (Type *_type)
Additional Inherited Members
Public Types inherited from sysy::ir::Instruction
enum InstrKind {
Add = 0, Sub, Mul, SDiv,
SRem, ICmpEQ, ICmpNE, ICmpSLT,
ICmpSGT, ICmpSLE, ICmpSGE, AShr,
LShr, Shl, FAdd, FSub,
FMul, FDiv, FRem, FCmpUEQ,
FCmpUNE, FCmpULT, FCmpUGT, FCmpULE,
FCmpUGE, Neg, Not, FNeg,
FPToSI, SIToFP, BitCast, CondBr,
Br, Call, Ret, Alloca,
Load, Store, InboundGEP, Zext,
Phi, MemPhi, LoadDep, MemCopy,
InsertEle, ExtractEle, Move, Dead
}
Static Public Member Functions inherited from sysy::ir::Instruction
static bool isReverse (Instruction *x, Instruction *y)
Protected Types inherited from sysy::ir::User
using OprandList = std::vector< std::shared_ptr< Use > >
Protected Attributes inherited from sysy::ir::User
OprandList operands
Protected Attributes inherited from sysy::ir::Value
std::string name
Type * type
std::list< std::shared_ptr< Use > > uses
Constructor & Destructor Documentation
LoadInstruction()
sysy::ir::LoadInstruction::LoadInstruction (Type * _type, Value * _ptr, BasicBlock * _father, std::string _name = "") inline
Member Function Documentation
getPtr()
Value* sysy::ir::LoadInstruction::getPtr () inline
References sysy::ir::User::operands.
Referenced by getSignature(), and sysy::ir::GVN::getValueNumber().
getSignature()
std::string sysy::ir::LoadInstruction::getSignature () override virtual
Implements sysy::ir::Instruction.
References getPtr(), sysy::ir::Type::getSignature(), getStore(), sysy::ir::Value::getType(), sysy::ir::getVariable(), and sysy::ir::nameIs().
getStore()
Value * sysy::ir::LoadInst::getStore ()
References sysy::ir::User::operands.
Referenced by getSignature(), and sysy::ir::GVN::getValueNumber().
removeStore()
void sysy::ir::LoadInst::removeStore ()
References sysy::ir::User::operands.
setStore()
void sysy::ir::LoadInst::setStore (Value * store)
References sysy::ir::User::addOperand(), sysy::ir::User::operands, and sysy::ir::User::replaceOperandWith().
The documentation for this class was generated from the following files:
include/sysy/IR/Instructions.h
lib/IR/Instructions.cpp
lib/IR/IRDump.cpp