Diana: sysy::ast::Immediate Class Reference
sysy::ast::Immediate Class Reference
#include <AstType.h>
Public Member Functions
Immediate ()
Immediate (int x)
Immediate (float x)
Immediate (double x)
void operator= (int x)
void operator= (float x)
AstType getType ()
std::string toString () const
template<typename F >
void computeAssign (Immediate x, F func)
template<typename F >
void computeAssign (Immediate x, Immediate y, F func)
void typeCast (AstType type)
int getInt ()
float getFloat ()
Private Attributes
union {
int Integer
float Float
double DoubleFloat
};
AstType type
Constructor & Destructor Documentation
Immediate() [1/4]
sysy::ast::Immediate::Immediate () inline
Immediate() [2/4]
sysy::ast::Immediate::Immediate (int x) inline
Immediate() [3/4]
sysy::ast::Immediate::Immediate (float x) inline
Immediate() [4/4]
sysy::ast::Immediate::Immediate (double x) inline
Member Function Documentation
computeAssign() [1/2]
template<typename F > void sysy::ast::Immediate::computeAssign (Immediate x, F func) inline
References sysy::ast::FLOAT, Float, sysy::ast::INT, Integer, and type.
Referenced by sysy::SysYVisitor::visitAddExp(), sysy::SysYVisitor::visitEqExp(), sysy::SysYVisitor::visitLAndExp(), sysy::SysYVisitor::visitLOrExp(), sysy::SysYVisitor::visitMulExp(), sysy::SysYVisitor::visitRelExp(), and sysy::SysYVisitor::visitUnaryExp().
computeAssign() [2/2]
template<typename F > void sysy::ast::Immediate::computeAssign (Immediate x, Immediate y, F func) inline
References sysy::ast::FLOAT, Float, sysy::ast::INT, Integer, type, and typeCast().
getFloat()
float sysy::ast::Immediate::getFloat () inline
References sysy::ast::FLOAT, Float, and typeCast().
Referenced by sysy::ir::irEmit().
getInt()
int sysy::ast::Immediate::getInt () inline
References sysy::ast::INT, Integer, type, and typeCast().
Referenced by sysy::ir::irEmit().
getType()
AstType sysy::ast::Immediate::getType () inline
References type.
Referenced by sysy::SysYVisitor::visitEqExp(), and sysy::SysYVisitor::visitPrimaryExp().
operator=() [1/2]
void sysy::ast::Immediate::operator= (float x) inline
References sysy::ast::FLOAT, and Float.
operator=() [2/2]
void sysy::ast::Immediate::operator= (int x) inline
References sysy::ast::INT, and Integer.
toString()
std::string sysy::ast::Immediate::toString () const inline
References sysy::ast::FLOAT, Float, sysy::ast::INT, Integer, and type.
Referenced by sysy::ast::NumberNode::getSignature().
typeCast()
void sysy::ast::Immediate::typeCast (AstType type) inline
References sysy::ast::FLOAT, Float, sysy::ast::INT, Integer, and type.
Referenced by computeAssign(), getFloat(), and getInt().
Member Data Documentation
@1
union { ... }
DoubleFloat
double sysy::ast::Immediate::DoubleFloat
Float
float sysy::ast::Immediate::Float
Referenced by computeAssign(), getFloat(), operator=(), toString(), and typeCast().
Integer
int sysy::ast::Immediate::Integer
Referenced by computeAssign(), getInt(), operator=(), toString(), and typeCast().
type
AstType sysy::ast::Immediate::type private
Referenced by computeAssign(), getInt(), getType(), toString(), typeCast(), sysy::SysYVisitor::visitAddExp(), and sysy::SysYVisitor::visitUnaryExp().
The documentation for this class was generated from the following file:
include/sysy/Frontend/AstType.h