Diana: sysy::ir::EliminatePhi Class Reference
sysy::ir::EliminatePhi Class Reference
#include <EliminatePhi.h>
Public Member Functions
EliminatePhi ()
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
bool isNeedToCut (BasicBlock *pre, BasicBlock *bb)
void cutKeyEdge (BasicBlock *from, BasicBlock *to, Function *func)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Constructor & Destructor Documentation
EliminatePhi()
sysy::ir::EliminatePhi::EliminatePhi ()
References sysy::Pass< Opt >::getFinish().
Member Function Documentation
cutKeyEdge()
void sysy::ir::EliminatePhi::cutKeyEdge (BasicBlock * from, BasicBlock * to, Function * func) private
References sysy::ir::BasicBlock::Create(), ErrorMsg, sysy::ir::BasicBlock::getInstructions(), sysy::ir::BasicBlock::getPredecessor(), and sysy::ir::BasicBlock::getSuccessor().
Referenced by run().
getName()
std::string sysy::ir::EliminatePhi::getName () inline override virtual
Implements sysy::Pass< Opt >.
isNeedToCut()
bool sysy::ir::EliminatePhi::isNeedToCut (BasicBlock * pre, BasicBlock * bb) private
References sysy::ir::BasicBlock::getInstructions(), and sysy::ir::BasicBlock::getSuccessor().
run()
void sysy::ir::EliminatePhi::run (Function * func) override
References sysy::ir::BasicBlock::BasicBlockDfs(), cutKeyEdge(), sysy::ir::Function::getBasicBlockList(), sysy::ir::Function::getEntryBlock(), and sysy::ir::BasicBlock::getInstructions().
The documentation for this class was generated from the following files:
include/sysy/Transform/Utils/EliminatePhi.h
lib/Transform/Utils/EliminatePhi.cpp