Diana: sysy::ir::PostDomTreeGen Class Reference
sysy::ir::PostDomTreeGen Class Reference
#include <PostDomInfo.h>
Public Member Functions
void run (Function *func) override
std::string getName () override
Public Member Functions inherited from sysy::Pass< Opt >
virtual ~Pass ()
virtual void run (Opt opt)=0
std::vector< Pass< Opt > * > & getRelated ()
std::vector< Pass< Opt > * > & getFinish ()
Private Member Functions
void computePostDomLevel (BasicBlock *bb, int level)
void computeAllPostDom (BasicBlock *bb)
Additional Inherited Members
Public Types inherited from sysy::Pass< Opt >
using DfsFunc = std::function< void(Pass< Opt > *)>
Static Public Member Functions inherited from sysy::Pass< Opt >
static void relatedDfs (Pass< Opt > *pass, DfsFunc func)
static void finishByDfs (Pass< Opt > *pass, DfsFunc func)
Member Function Documentation
computeAllPostDom()
void sysy::ir::PostDomTreeGen::computeAllPostDom (BasicBlock * bb) private
References sysy::ir::BasicBlock::getPdoms(), sysy::ir::BasicBlock::getPdomTree(), and sysy::ir::pdoms.
Referenced by run().
computePostDomLevel()
void sysy::ir::PostDomTreeGen::computePostDomLevel (BasicBlock * bb, int level) private
References sysy::ir::BasicBlock::getPdomTree(), and sysy::ir::BasicBlock::setPdomLevel().
Referenced by run().
getName()
std::string sysy::ir::PostDomTreeGen::getName () inline override virtual
Implements sysy::Pass< Opt >.
run()
void sysy::ir::PostDomTreeGen::run (Function * func) override
References computeAllPostDom(), computePostDomLevel(), sysy::ir::Function::getBasicBlockList(), sysy::ir::Function::getEntryBlock(), and sysy::ir::pdoms.
The documentation for this class was generated from the following files:
include/sysy/Analysis/PostDomInfo.h
lib/Analysis/PostDomInfo.cpp