Diana: sysy::mc::Regallocator Class Reference
sysy::mc::Regallocator Class Reference
#include <Regallocator.h>
Public Member Functions
void build ()
void simplify ()
void simplify_v ()
void coalesce ()
void freeze ()
Reg * spill ()
Reg * spill_v ()
int get_root (int x)
void add_spill_code (const std::vector< Reg * > &spill_nodes)
void add_spill_code_v (const std::vector< Reg * > &spill_nodes)
void add_spill_code_onlys (const std::vector< Reg * > &spill_nodes)
void add_spill_code_v_onlys (const std::vector< Reg * > &spill_nodes)
bool conservative_check (int u, int v)
void merge (int u, int v)
void for_each_node (std::function< void(int)> f)
Regallocator (Function *_func)
std::vector< int > run (RegAllocStat *stat)
Public Attributes
Function * func
std::vector< Reg * > occur
std::vector< int > phy_occur
std::vector< std::set< Reg * > > interfere_edge
std::map< int, std::set< int > > move_edge
std::vector< std::pair< Reg *, std::vector< Reg * > > > simplify_history
std::set< Reg * > remain_pesudo_nodes
std::vector< Reg * > occur_v
std::vector< int > phy_occur_v
std::vector< std::set< Reg * > > interfere_edge_v
std::map< int, std::set< int > > move_edge_v
std::map< int, double > spill_cost
std::map< int, double > spill_cost_v
std::vector< std::pair< Reg *, std::vector< Reg * > > > simplify_history_v
std::set< Reg * > remain_pesudo_nodes_v
int num =0
Constructor & Destructor Documentation
Regallocator()
sysy::mc::Regallocator::Regallocator (Function * _func)
Member Function Documentation
add_spill_code()
void sysy::mc::Regallocator::add_spill_code (const std::vector< Reg * > & spill_nodes)
References sysy::mc::BinaryImm::ADD, sysy::mc::Function::blocks, func, sysy::mc::Function::offset, sysy::mc::Reg::PHY, sysy::mc::LoadImm::SLOAD, sysy::mc::Function::sp, sysy::mc::Function::spill_count, sysy::mc::StoreImm::SSTORE, and sysy::mc::BinaryImm::SUB.
Referenced by run().
add_spill_code_onlys()
void sysy::mc::Regallocator::add_spill_code_onlys (const std::vector< Reg * > & spill_nodes)
References sysy::mc::Function::blocks, func, merge(), move_edge, sysy::mc::Function::off_reg, sysy::mc::Function::spill_count, sysy::mc::MoveReg::SVMOV, sysy::mc::Reg::VIRTUAL, sysy::mc::Reg::VREG, and sysy::mc::Function::vreg_num.
Referenced by run().
add_spill_code_v()
void sysy::mc::Regallocator::add_spill_code_v (const std::vector< Reg * > & spill_nodes)
References sysy::mc::BinaryImm::ADD, sysy::mc::Function::blocks, func, sysy::mc::Function::offset_v, sysy::mc::Reg::PHY, sysy::mc::Function::sp, sysy::mc::Function::spill_count, sysy::mc::BinaryImm::SUB, sysy::mc::LoadImm::VLOAD, and sysy::mc::StoreImm::VSTORE.
Referenced by run().
add_spill_code_v_onlys()
void sysy::mc::Regallocator::add_spill_code_v_onlys (const std::vector< Reg * > & spill_nodes)
References sysy::mc::BinaryImm::ADD, sysy::mc::Function::blocks, func, merge(), move_edge, sysy::mc::Function::offset_v, sysy::mc::Reg::PHY, sysy::mc::LoadImm::SLOAD, sysy::mc::Function::sp, sysy::mc::Function::spill_count, sysy::mc::Reg::SREG, sysy::mc::StoreImm::SSTORE, and sysy::mc::BinaryImm::SUB.
Referenced by run().
build()
void sysy::mc::Regallocator::build ()
References sysy::mc::allocable(), sysy::mc::Function::blocks, sysy::mc::Function::calc_live(), func, interfere_edge, interfere_edge_v, occur, occur_v, sysy::mc::Reg::PHY, phy_occur, phy_occur_v, sysy::mc::Function::reg_num, remain_pesudo_nodes, remain_pesudo_nodes_v, spill_cost, spill_cost_v, sysy::mc::Reg::SREG, sysy::type, sysy::mc::Reg::VIRTUAL, sysy::mc::Reg::VREG, and sysy::mc::Function::vreg_num.
Referenced by run().
coalesce()
void sysy::mc::Regallocator::coalesce ()
References sysy::mc::Function::blocks, func, interfere_edge, interfere_edge_v, merge(), move_edge, move_edge_v, remain_pesudo_nodes, remain_pesudo_nodes_v, sysy::mc::Reg::SREG, sysy::mc::Reg::VIRTUAL, and sysy::mc::Reg::VREG.
Referenced by run().
conservative_check()
bool sysy::mc::Regallocator::conservative_check (int u, int v)
for_each_node()
void sysy::mc::Regallocator::for_each_node (std::function< void(int)> f)
freeze()
void sysy::mc::Regallocator::freeze ()
get_root()
int sysy::mc::Regallocator::get_root (int x)
merge()
void sysy::mc::Regallocator::merge (int u, int v)
Referenced by add_spill_code_onlys(), add_spill_code_v_onlys(), coalesce(), and run().
run()
vector< int > sysy::mc::Regallocator::run (RegAllocStat * stat)
References add_spill_code(), add_spill_code_onlys(), add_spill_code_v(), add_spill_code_v_onlys(), sysy::mc::allocable(), build(), sysy::mc::RegAllocStat::callee_save_used, coalesce(), func, sysy::mc::RegAllocStat::ifonly, interfere_edge, interfere_edge_v, merge(), move_edge, move_edge_v, num, sysy::mc::Reg::PHY, phy_occur, phy_occur_v, sysy::mc::Function::reg_num, sysy::mc::REGISTER_USAGE, remain_pesudo_nodes, remain_pesudo_nodes_v, simplify(), simplify_history, simplify_history_v, simplify_v(), spill(), sysy::mc::RegAllocStat::spill_cnt, spill_v(), sysy::mc::RegAllocStat::succeed, sysy::mc::Reg::VIRTUAL, and sysy::mc::Function::vreg_num.
Referenced by sysy::mc::Function::reg_allocate().
simplify()
void sysy::mc::Regallocator::simplify ()
References interfere_edge, remain_pesudo_nodes, simplify_history, and sysy::mc::Reg::VIRTUAL.
Referenced by run().
simplify_v()
void sysy::mc::Regallocator::simplify_v ()
References interfere_edge_v, remain_pesudo_nodes_v, simplify_history_v, and sysy::mc::Reg::VIRTUAL.
Referenced by run().
spill()
Reg * sysy::mc::Regallocator::spill ()
References func, sysy::mc::Reg::id, interfere_edge, remain_pesudo_nodes, spill_cost, sysy::mc::Function::spilling_nodes, and sysy::mc::Reg::VIRTUAL.
Referenced by run().
spill_v()
Reg * sysy::mc::Regallocator::spill_v ()
References func, sysy::mc::Reg::id, interfere_edge_v, remain_pesudo_nodes_v, spill_cost_v, sysy::mc::Function::spilling_nodes_v, and sysy::mc::Reg::VIRTUAL.
Referenced by run().
Member Data Documentation
func
Function* sysy::mc::Regallocator::func
Referenced by add_spill_code(), add_spill_code_onlys(), add_spill_code_v(), add_spill_code_v_onlys(), build(), coalesce(), run(), spill(), and spill_v().
interfere_edge
std::vector<std::set<Reg*> > sysy::mc::Regallocator::interfere_edge
Referenced by build(), coalesce(), run(), simplify(), and spill().
interfere_edge_v
std::vector<std::set<Reg*> > sysy::mc::Regallocator::interfere_edge_v
Referenced by build(), coalesce(), run(), simplify_v(), and spill_v().
move_edge
std::map<int, std::set<int> > sysy::mc::Regallocator::move_edge
Referenced by add_spill_code_onlys(), add_spill_code_v_onlys(), coalesce(), and run().
move_edge_v
std::map<int, std::set<int> > sysy::mc::Regallocator::move_edge_v
Referenced by coalesce(), and run().
num
int sysy::mc::Regallocator::num =0
Referenced by run().
occur
std::vector<Reg*> sysy::mc::Regallocator::occur
Referenced by build().
occur_v
std::vector<Reg*> sysy::mc::Regallocator::occur_v
Referenced by build().
phy_occur
std::vector<int> sysy::mc::Regallocator::phy_occur
Referenced by build(), and run().
phy_occur_v
std::vector<int> sysy::mc::Regallocator::phy_occur_v
Referenced by build(), and run().
remain_pesudo_nodes
std::set<Reg*> sysy::mc::Regallocator::remain_pesudo_nodes
Referenced by build(), coalesce(), run(), simplify(), and spill().
remain_pesudo_nodes_v
std::set<Reg*> sysy::mc::Regallocator::remain_pesudo_nodes_v
Referenced by build(), coalesce(), run(), simplify_v(), and spill_v().
simplify_history
std::vector<std::pair<Reg*, std::vector<Reg*> > > sysy::mc::Regallocator::simplify_history
Referenced by run(), and simplify().
simplify_history_v
std::vector<std::pair<Reg*, std::vector<Reg*> > > sysy::mc::Regallocator::simplify_history_v
Referenced by run(), and simplify_v().
spill_cost
std::map<int, double> sysy::mc::Regallocator::spill_cost
Referenced by build(), and spill().
spill_cost_v
std::map<int, double> sysy::mc::Regallocator::spill_cost_v
Referenced by build(), and spill_v().
The documentation for this class was generated from the following files:
include/sysy/Target/Regallocator.h
lib/Target/Regallocator.cpp